### ISSUE TITLE
[Issue] SetupAssist fails to check for "member of" in different language

### ISSUE THREAD

**Issue by worldsdream** [microsoft/CSS-Exchange#1006]
Setup Assist Version 22.05.06.2345
Running the above SetupAssist.ps1

**Expected behavior**
Running SetupAssist.ps1 shows:

Schema Admins                        Failed   Not a member of the Schema Admins Group
Domain Admins                        Failed   Not a member of the Domain Admins Group
Enterprise Admins                    Failed   Not a member of the Enterprise Admins Group

Checking the account, it has all the rights. So it looks like it doesn't respect non-english languages

Can this be confirmed and fixed?

Thanks a lot.

**Comment by dpaulson45** [comment]
Currently, SetupAssist does not detect if we are part of AD groups due to non-english languages. Might need to look into looking up the groups by their SID somehow. Will need to investigate this. Thanks

**Comment by bill-long** [comment]
https://docs.microsoft.com/en-US/windows/security/identity-protection/access-control/security-identifiers

It looks like the SIDs are predictable, but we have to retrieve the domain identifier in order to build the SID. I'm trying to figure out if there's an easier way to do this...

**Comment by bill-long** [comment]
@worldsdream This should be fixed in the release that just went live. Please let us know if not.

**Comment by worldsdream** [comment]
@bill-long tested on a non-english exchange server build and works perfect now.

thanks for the quick fix!
