### ISSUE TITLE
[Issue] - Health Checker shows pla critical services is stopped

### ISSUE THREAD

**Issue by josemi73** [microsoft/CSS-Exchange#1031]
I have just executed Exchange Health Checker version 22.05.11.2121, after installing Exchange 2016 CU 23 SU May 2022, and a critical service is not running:

Exchange Information
--------------------
	Name: SERVER1
	Generation Time: 05/13/2022 10:35:39
	Version: Exchange 2016 CU23
	Build Number: 15.01.2507.009
	Exchange IU or Security Hotfix Detected: 
		Security Update for Exchange Server 2016 Cumulative Update 23 (KB5014261)
	Server Role: Mailbox
	DAG Name: DAGEXCHANGE
	AD Site: Nombre-predeterminado-primer-sitio
	MAPI/HTTP Enabled: True
	Internet Web Proxy: Not Set
	Services Not Running: 
		MSExchangePOP3
	**Critical Services Not Running: 
		pla - Status: Stopped - StartType: Disabled**
	Exchange Server Maintenance: Server is not in Maintenance Mode

What service is that?

**Comment by lusassl-msft** [comment]
@josemi73 PLA is the `Performance Logs & Alerts` service.

_Performance Logs and Alerts Collects performance data from local or remote computers based on preconfigured schedule parameters, then writes the data to a log or triggers an alert. If this service is stopped, performance information will not be collected. If this service is disabled, any services that explicitly depend on it will fail to start._

**Comment by josemi73** [comment]
Thank you @lusassl-msft for the clarification.

I do not know why I have got disabled that service. I will change to Manual then.

Regards.
