### ISSUE TITLE
Microsoft Safety Scanner shows different results than Test-ProxyLogon.ps1 

### ISSUE THREAD

**Issue by zerocarbthirty** [microsoft/CSS-Exchange#109]
**Describe the issue**
I ran Test-ProxyLogon.ps1 it showed that my machine was impacted by the 0day CVEs.
I ran MSERT and it reported nothing on a full scan.
**Expected behavior**

I would expect that both of them would show IOCs or neither of them would show IOCs.

How is anyone supposed to know what is going on if two tools from the same company gives two different results?

**Comment by bill-long** [comment]
Test-ProxyLogon.ps1 and MSERT scan for two different things. They are not expected to show the same results. Please refer to the blog post for details.

**Comment by zerocarbthirty** [comment]
Quote the blog post to me one more time.

**Comment by zerocarbthirty** [comment]
I honestly cannot believe how casual and dismissive you guys at MS are.
Lose more games than the Jets and act like you are a team full of Tom
Bradys. The hubris. I understand it must really difficult to do your job as
a $1.75T company but can you try?

Make some sort of effort. Please? Anything?
