### ISSUE TITLE
[Issue] - Health Checker TLS Settings for all TLS protocols and maybe more.

### ISSUE THREAD

**Issue by parlevjo2** [microsoft/CSS-Exchange#1093]
Exchange Health Checker version 22.06.01.0905

The script eg detects the following
```
        TLSVersion  ServerEnabled  ServerDbD  ClientEnabled  ClientDbD  Configuration
        ----------  -------------  ---------  -------------  ---------  -------------
        1.2         False          False      False          False      Half Disabled
        1.2 ServerEnabledValue: -1 --- Error: Must be a value of 1 or 0.
        1.2 ClientEnabledValue: -1 --- Error: Must be a value of 1 or 0.
                More Information: https://aka.ms/HC-TLSConfigDocs
```

In our environment those settings are:
```
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client]
"Enabled"=dword:ffffffff
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server]
"Enabled"=dword:ffffffff
```

In the documentation https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings it also says that the value can be zero or non zero

In order to override a system default and set a supported (D)TLS or SSL protocol version to the Enabled state, **create a DWORD registry value named "Enabled" with a non-zero value**, and a DWORD registry value named "DisabledByDefault" with a value of zero, under the corresponding version-specific subkey.

The script should not report "Enabled"=dword:ffffffff as an error

**Comment by dpaulson45** [comment]
Our documentation from the Exchange team provides specifically to use a 0 or a 1. While a -1 value does work to **enable** it, makes it harder to understand for some people to follow if it is enabled or not.

There is no benefit to have this value to be a -1 over a value of 1. 

https://techcommunity.microsoft.com/t5/exchange-team-blog/exchange-server-tls-guidance-part-2-enabling-tls-1-2-and/ba-p/607761

Will discuss this internally more, but I am leaning towards following the documentation that the Exchange team provided and not making it complicated and follows the standard of a Boolean of being a 0 or 1.

**Comment by parlevjo2** [comment]
Microsoft self uses also sometimes a value of -1. See [Disable TLS 1.0/1.1 in Skype for Business Server 2015](https://learn.microsoft.com/en-us/skypeforbusiness/manage/topology/disable-tls-1.0-1.1)

`[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\AES 128/128]
"Enabled"=dword:FFFFFFFF
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\AES 256/256]
"Enabled"=dword:FFFFFFFF`

**Comment by parlevjo2** [comment]
Another example here [Restrict the use of certain cryptographic algorithms and protocols in Schannel.dll](https://learn.microsoft.com/en-us/troubleshoot/windows-server/windows-security/restrict-cryptographic-algorithms-protocols-schannel)

9 times:
To allow this cipher algorithm, change the DWORD value data of the Enabled value to **0xffffffff.**
