### ISSUE TITLE
[Issue] - Health Checker ScriptUpdateOnly parameter in a scheduled task

### ISSUE THREAD

**Issue by Xypriz** [microsoft/CSS-Exchange#1098]
**Provide Version Number**
22.05.17.2008

**Describe the issue**
Using the script with the ScriptUpdateOnly parameter in a scheduled task doesn't work anymore since this version expects a confirmation on the update. This was not the case in previous versions of the script.

**Expected behavior**
Being able to use the script with the ScriptUpdateOnly parameter in a scheduled task again. This may be achieved in two ways I think:
- Revert to the old way of update handling 
- Build in something like a -Confirm:$false option

**Script Output**
.\HealthChecker.ps1 -ScriptUpdateOnly

Confirm
Are you sure you want to perform this action?
Performing the operation "Update script to latest version" on target "HealthChecker.ps1".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"):

**Additional context**
n/a

**Comment by dpaulson45** [comment]
@Xypriz thanks for the issue!! Fix will be released shortly.
