### ISSUE TITLE
[Issue] Setup Assist not correctly identifying Current Exchange Build?

### ISSUE THREAD

**Issue by get-itips** [microsoft/CSS-Exchange#1136]
**Describe the issue**
Setup Assist Version 22.07.11.0407

**Expected behavior**
I have just run the Setup Assist on a lab that I have, not because I was troubleshooting a CU install (it's already installed) but because I wanted to test the execution before I do that in a customer, and it seems it did not correctly identify the current Exchange Build, under the Setup Log Reviewer Results section.

**Script Output**
No exception but here is the output:

```
Setup Log Reviewer Results
--------------------------

Setup.exe Run Date: 05/12/2022 19:34:37
Setup.exe Build Number: 15.1.2507.6
Current Exchange Build: 15.1.2308.8
```

**Additional context**
I could dig into the `SetupLogReviewerFunctions.ps1` file and I see that the current build, appears to be determined from the "The locally installed version is" sentence from the ExchangeSetup.log file.

Here is a screenshot where you can see that the Exchange build is 15.1.2507.6 but the Script is reporting an older version.

![image](https://user-images.githubusercontent.com/36666927/180311877-15fa78c6-5ed2-4af7-845f-520aaa113b57.png)

Maybe I am doing something wrong?

Thanks for these great tools,

**Comment by dpaulson45** [comment]
Current Exchange Build in this context is providing what was Exchange Build Number when running setup. When you have issues and you are troubleshooting Exchange Setup Issues, the Current Exchange Build with provide what you are currently on and the Setup Build of what you are trying to install.

**Comment by get-itips** [comment]
Hello @dpaulson45 David
Thanks for your quick reply and clarification. The setup assist script is very useful and I think it would be very useful for other scenarios, for example, when installing SUs and also, it would be useful to run before any CU setup run has been tried, maybe some scenarios that can be included in the script? Thanks for this great tool.

We can close this issue now.
