### ISSUE TITLE
[HealthChecker] allow automation for update

### ISSUE THREAD

**Issue by cdquinn** [microsoft/CSS-Exchange#1139]
I currently have 22.06.01.0905 and I am aware that an update is available.  However I cannot force the script to update in automation with the Confirm:$False switch

Seems to me this should be a simple enough switch to allow since it creates a backup anyway.  As an alternative I would only be able to update when running interactively and skip the version check in automation.

**Comment by dpaulson45** [comment]
This issue should have been solved with a later build. Now in HC, we don't even prompt for do you want to download the latest version. Please just install the latest version. 

#1111 
#1098

**Comment by dpaulson45** [comment]
Closing issue as this should have been resolved.
