### ISSUE TITLE
Docs improvement - Does Extended Authentication work with SSL bridging?

### ISSUE THREAD

**Issue by kevin-olbrich** [microsoft/CSS-Exchange#1151]
Does Extended Authentication work with SSL bridging?
The docs state, ssl offloading (speaking unencrypted HTTP to the backend) breaks Extended Authentication. Is this also the case with SSL bridging where the LB speaks HTTPS (encrypted) to both the client and the frontend (while using a different certificate)?

https://microsoft.github.io/CSS-Exchange/Security/Extended-Protection/#ssl-offloading-scenarios-are-not-supported

**Comment by lusassl-msft** [comment]
@kevin-olbrich we’ve updated the documentation and added the scenario from your question. Please have a look and re-open if any question left.

**Comment by kevin-olbrich** [comment]
@lusassl-msft thank you, the addition clarifies my question completely
