### ISSUE TITLE
[Issue] - Health Checker - clean up recommendations for SchUseStrongCrypto registry settings

### ISSUE THREAD

**Issue by boogieshafer** [microsoft/CSS-Exchange#1153]
**Provide Version Number**
Provide the version of the script that has the issue.
22.08.09.0638

**Describe the issue**
A clear and concise description of the issue.
currently the corrective action output from the HealthChecker script re: the SchUseStrongCrypto registry settings is confusing and if you followed them exactly it would not resolve the issue

additionally the article linked in the output is incomplete
 
**Expected behavior**
the current output does not describe all the locations that are necessary to configure the registry setting to match current suggested Best Practices described here:
https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls

the reg export in that article is the clearest list of settings (copied below)

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\v2.0.50727]
"SystemDefaultTlsVersions"=dword:00000001
"SchUseStrongCrypto"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\v4.0.30319]
"SystemDefaultTlsVersions"=dword:00000001
"SchUseStrongCrypto"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\v2.0.50727]
"SystemDefaultTlsVersions"=dword:00000001
"SchUseStrongCrypto"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\v4.0.30319]
"SystemDefaultTlsVersions"=dword:00000001
"SchUseStrongCrypto"=dword:00000001

**Script Output**
If applicable, add the exception that wasn't handled.
a screenshot the current out put in the script is attached

Note the "SchUseStrongCryptoValue" instead of "SchUseStrongCrypto", and "WowSchUseStrongCryptoValue" which implies its a key of that name instead of "SchUseStrongCrypto" key in the HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\... location

<img width="1225" alt="Screen Shot 2022-08-09 at 9 35 36 PM" src="https://user-images.githubusercontent.com/714141/183818021-42dcbb2d-92b3-4d48-9dfa-4071d3374793.png">

**Additional context**

**Comment by lusassl-msft** [comment]
@boogieshafer the required keys and values for Exchange can be found here: https://aka.ms/HC-TLSGuide

Not sure if I understand you right: You’re unhappy with the description provided under: https://aka.ms/HC-TLSConfigDocs ?

**Comment by boogieshafer** [comment]
@lusassl-msft if you look at the screenshot you can see description of the keys that are missing is confusing

the link that is provided in the HealthChecker output is not the same guide you linked in your response. the currently linked document  does not cover all the settings

**Comment by bill-long** [comment]
What if we turned that table around so that the values in the screenshot above look like this:

Registry Name | Framework | Bitness | Value
-|-|-|-
SystemDefaultTlsVersions | NETv4 | 32 | True
SystemDefaultTlsVersions | NETv4 | 64 | True
SystemDefaultTlsVersions | NETv2 | 32 | False
SystemDefaultTlsVersions | NETv2 | 64 | False
SchUseStrongCrypto | NETv4 | 32 | 
SchUseStrongCrypto | NETv4 | 64 | False
SchUseStrongCrypto | NETv2 | 32 | 
SchUseStrongCrypto | NETv2 | 64 | False

Also, I'm confused why the error says SchUseStrongCryptoValue is NULL - the table doesn't show that. It only shows the 32-bit one (Wow6432NodeSchUseStrongCrypto in this terminology) is NULL. So I can see how this would be confusing. It might be helpful if we highlight the problem values in the table itself - for example, have "NULL" or "<not set>" in red.

**Comment by bill-long** [comment]
It might even be clearer to just show the registry path:

Registry Name | Location | Value
-|-|-
SystemDefaultTlsVersions | Wow6432Node\Microsoft\.NETFramework\v4.0.30319 | True
SystemDefaultTlsVersions | Microsoft\.NETFramework\v4.0.30319 | True
SystemDefaultTlsVersions | Wow6432Node\Microsoft\.NETFramework\v2.0.50727 | False
SystemDefaultTlsVersions | Microsoft\.NETFramework\v2.0.50727 | False
SchUseStrongCrypto | Wow6432Node\Microsoft\.NETFramework\v4.0.30319 | 
SchUseStrongCrypto | Microsoft\.NETFramework\v4.0.30319 | False
SchUseStrongCrypto | Wow6432Node\Microsoft\.NETFramework\v2.0.50727 | 
SchUseStrongCrypto | Microsoft\.NETFramework\v2.0.50727 | False

**Comment by bill-long** [comment]
@boogieshafer I was just testing this in my lab and realized you seem to have a prerelease version of the script. This output does already look slightly different in the released version. I still think we can improve it, but please be sure you're running the one we actually released, which is 22.08.09.1227.

**Comment by bill-long** [comment]
Deleted previous comment, as I confused HealthChecker output with ExchangeExtendedProtection output. Both scripts output these values, but the EEP script is slightly more terse. We might want to unify the output between the two if we can.

**Comment by dpaulson45** [comment]
@bill-long This is because Health Checker is using a calculated value for the `bool` where it assumes that if the value is `null` or `0` we have it set to `false`. However, after recent discovery, different versions of .NET handle this differently.

**Comment by dpaulson45** [comment]
> It might even be clearer to just show the registry path:
> 
> Registry Name	Location	Value
> SystemDefaultTlsVersions	Wow6432Node\Microsoft\.NETFramework\v4.0.30319	True
> SystemDefaultTlsVersions	Microsoft\.NETFramework\v4.0.30319	True
> SystemDefaultTlsVersions	Wow6432Node\Microsoft\.NETFramework\v2.0.50727	False
> SystemDefaultTlsVersions	Microsoft\.NETFramework\v2.0.50727	False
> SchUseStrongCrypto	Wow6432Node\Microsoft\.NETFramework\v4.0.30319	
> SchUseStrongCrypto	Microsoft\.NETFramework\v4.0.30319	False
> SchUseStrongCrypto	Wow6432Node\Microsoft\.NETFramework\v2.0.50727	
> SchUseStrongCrypto	Microsoft\.NETFramework\v2.0.50727	False
> Not sure if we have room to include the HKLM\Software at the beginning of the path as well. But even with this, I don't even really have to go look up any article at this point. I can clearly see what value is set where, and if we flag something in red, we can clearly indicate what we want the user to change.

@lusassl-msft I see you assigned this to yourself. I think we should try this type of a view as this looks pretty good. However, in order to get this, we might need to change the main `Get-AllTlsSettingsFromRegistry` to have it make the most sense. If we do that, we need to be careful about it. 

This might even be the better option for the other TLS values too.

**Comment by lusassl-msft** [comment]
Yep self-assigned it to me as I wanted to look into this. However, if you have time and want to do that, feel free to assign it to yourself. Otherwise I’ll start looking into this within the next few days

**Comment by dpaulson45** [comment]
I have an idea how to make this better, but don't want to change anything just yet because i think this function should get moved to Shared and the other thing we are working on currently should get finalized first.

**Comment by dpaulson45** [comment]
@boogieshafer  does the PR that is open look, clearer as to the problem?
