### ISSUE TITLE
[Issue] - Health Checker - Vulnerability Detected marked as True

### ISSUE THREAD

**Issue by JoelJerkin** [microsoft/CSS-Exchange#1154]
**Provide Version Number**
Provide the version of the script that has the issue.
22.08.09.0638

**Describe the issue**
A clear and concise description of the issue.

Running HealthChecker.ps1, the XML/HTML report Vulnerability Detected as True and Security Vulnerabilities will have DisplayWriteType value as "Red" when no "real" Security Vulnerability is detected, however  Security Vulnerability reports the following output:
IIS module anomalies detected: False

**Expected behavior**
When "Security Vulnerability" reports "IIS module anomalies detected: False", Vulnerability Detected should be False.

**Script Output**
If applicable, add the exception that wasn't handled.

**Additional context**

---
```

<Obj RefId="2493">
<TNRef RefId="153"/>
<ToString>HealthChecker.HtmlServerInformationRow</ToString>
<Props>
<S N="Name">IIS module anomalies detected</S>
<S N="DetailValue">False</S>
<Nil N="TableValue"/>
<Nil N="Class"/>
</Props>
</Obj>

<Obj RefId="2494">
<TNRef RefId="153"/>
<ToString>HealthChecker.HtmlServerInformationRow</ToString>
<Props>
<S N="Name">Security Vulnerabilities</S>
<S N="DetailValue">False<br></S>
<Nil N="TableValue"/>
<S N="Class">Red</S>
</Props>
</Obj>


<Obj RefId="2506">
<TNRef RefId="153"/>
<ToString>HealthChecker.HtmlServerInformationRow</ToString>
<Props>
<S N="Name">Vulnerability Detected</S>
<S N="DetailValue">True</S>
<Nil N="TableValue"/>
<S N="Class">Red</S>
</Props>
</Obj>

```

**Comment by cvocvo** [comment]
Encountered the same issue after rolling out extended protection on Exchange 2019; from the HTML version of the report:

![image](https://user-images.githubusercontent.com/355711/183961149-3fb6ea91-4145-4e07-acf6-08f482784dfb.png)

![image](https://user-images.githubusercontent.com/355711/183961199-1e967347-670c-4a1e-a3df-c30b30d3704d.png)

**Comment by dpaulson45** [comment]
Determined the cause of this. 

When we added in the section of IIS Module check, we added this to the security vulnerability section, now it isn't `null` we flag it as Security Vulnerability detected but the displayed value of the IIS Module section is false, that is why we see a false value in the bottom section.
