### ISSUE TITLE
[Issue] - Health Checker - no indication that Windows Extended Protection is enabled

### ISSUE THREAD

**Issue by boogieshafer** [microsoft/CSS-Exchange#1163]
**Provide Version Number**
Provide the version of the script that has the issue.

22.08.09.0638

**Describe the issue**
A clear and concise description of the issue.

once Windows Extended Protection is enabled (i used the script) i don't see any indication in the healthchecker script that it is enabled aside from no longer seeing the list of IIS virtual directories that previously showed u in the Security Vulnerability section

**Expected behavior**

i would expect to see an indication in the healthchecker script that the Extended Protection is enabled (like for AMSI and Emergency Mitigation Service) given it does indicate when its not configured

**Script Output**
If applicable, add the exception that wasn't handled.

**Additional context**

**Comment by dpaulson45** [comment]
This is correct, by design we are only going to show the current settings of the Extended Protection if something is configured to the unrecommended setting it is a security vulnerability, thus showing the results. 

If there is no security vulnerability, we don't show the results.

In the Exchange Information section, you should see a new property that will show you that Extended Protection is enabled.

**Comment by dpaulson45** [comment]
![image](https://user-images.githubusercontent.com/22776718/184252076-3c6b4d38-04e3-4ca6-8c95-92c2f91cd466.png)


We should see this section, is this not good enough? Or should we have something else?

**Comment by boogieshafer** [comment]
thanks so much i see it now

i missed that line as i was looking for the extended protection stuff down at the bottom

**Comment by dpaulson45** [comment]
> thanks so much i see it now
> 
> i missed that line as i was looking for the extended protection stuff down at the bottom

If you think we should show this in a different fashion, let us know.

**Comment by boogieshafer** [comment]
i can see why you chose to put it in the exchange information section instead of the security settings area. i was expecting it to be in security settings which is how i think i just skipped right over it in my initial scan of the results post implementation

it does feel that there is so much IIS specific setup/tuning now required on these exchange systems that it might be worth having a dedicated "IIS settings" area (which might also be a good place to put security headers information in the future)

thanks so much for all the work you folks do on this tool. its a real time saver for me these days
