### ISSUE TITLE
[Issue] unidentified user is accessing my apps under barkow71@gmail.com. 

### ISSUE THREAD

**Issue by barkowkay** [microsoft/CSS-Exchange#118]
**Describe the issue**
A clear and concise description of what the issue is, including what script you are seeing the error in.

**Expected behavior**

**Script Output**
If applicable, add the exception that you are seeing that wasn't handled.

**Additional context**

**Comment by bill-long** [comment]
I don't see any issue with the scripts here. Can you clarify?

**Comment by barkowkay** [comment]
Found "package" installed on rom, old gmail account gave permission to remotely access,. I have never given permission to remotely access anything on my stuff.

**Comment by bill-long** [comment]
Is this somehow related to the scripts in the CSS-Exchange repo? I'm not seeing the connection to this repository. If you have an issue with a script in this repository, please paste the error you're getting from the script.

**Comment by barkowkay** [comment]
Sorry, it has nothing to do with that.  I was trying anyway I could think of you make sure someone was receiving my emails.  Gmail didn't respond.  However Microsoft did and I sent the file in question.  Sorry for any inconvience.
