### ISSUE TITLE
[Issue] Extended Protection script enforces SchUseStrongCrypto to be set to 1

### ISSUE THREAD

**Issue by lusassl-msft** [microsoft/CSS-Exchange#1197]
**Describe the issue**
Reported via blog post comment: https://techcommunity.microsoft.com/t5/exchange-team-blog/released-august-2022-exchange-server-security-updates/bc-p/3609072/highlight/true#M33803

Based on our documentation, the SchUseStrongCrypto must be explicitly configured via registry but can be set to 0.

_In addition to this, the value of SchUseStrongCrypto registry key should be either set to 1 (recommended) or 0 across all the Exchange Servers in the organization. If this value is not explicitly set, the default value of this key may be interpreted as 0 or 1 depending on the .NET version in use by the Exchange binaries. This can cause TLS mismatch, leading to client connectivity issues._

https://microsoft.github.io/CSS-Exchange/Security/Extended-Protection/#tls-configuration-must-be-consistent-across-all-exchange-servers

**Expected behavior**
The script should continue with the EP configuration if this value is explicitly set to 0 (not recommended but valid)

**Code**
Line 2759++
```
                foreach ($key in $netKeys) {
                    if ($netRegistry[$key].SchUseStrongCrypto -eq $false -or
                        $netRegistry[$key].WowSchUseStrongCrypto -eq $false -or
                        $null -eq $netRegistry[$key].SchUseStrongCryptoValue -or
                        $null -eq $netRegistry[$key].WowSchUseStrongCryptoValue) {
```

**Comment by lusassl-msft** [comment]
@mukeshHCW 
We need to clarify what we expect. If 0 isn't supported, then the documentation must be adjusted. Otherwise a code change is required.

**Comment by mukeshHCW** [comment]
As per our discussion, we can have either value 0 or 1, but should be explicitly set. As the main issue was how if the registry is not set, depending on .NET version it is interpreted differently.
 @anjaneya17 to review this as well.
