### ISSUE TITLE
[Work Item] Improve the Extended Protection TLS registry location screen output for low resolution

### ISSUE THREAD

**Issue by lusassl-msft** [microsoft/CSS-Exchange#1198]
**Describe the work**
The TLS check registry location is being cropped if the screen resolution is low or if the windows size width is set to a low value. We also crop the table output in the log file which is written during the script run.
![image](https://user-images.githubusercontent.com/40993616/186705630-960facdb-7e1e-401b-9b03-18c64eb2f183.png)

**Additional Context**
Check if the `Out-Columns` function handles this properly.

**Comment by dpaulson45** [comment]
The use of `Out-Columns` will work in this scenario. Heath Checker does not truncate the line at all. 

![image](https://user-images.githubusercontent.com/22776718/186932160-72b5a7a9-a2df-440a-8df6-fb52d4c714e0.png)
