### ISSUE TITLE
Clarify CU/SU update requirements for Extended Protection

### ISSUE THREAD

**Issue by lusassl-msft** [microsoft/CSS-Exchange#1216]
**Describe the work**
As discussed in today's meeting, we need to add the following to the Extended Protection FAQ documentation:

Q: _Is it required to install the August 2022 Security Update (SU) if it was already installed on the previous Cumulative Update (CU)?_
A: Yes, it's required to install the August 2022 SU again if you update to a newer CU build (e.g., Exchange Server 2019 CU11 --> Exchange Server 2019 CU12). 
Please remember:
- If you plan to do the update immediately (means CU + SU installation) Extended Protection does not need to be switched off
- If you plan to stay on the CU without installing the SU immediately, you must disable Extended Protection **[link to the rollback documentation]** as the CU without the SU being installed doesn't support Extended Protection and therefore, you'll experience client connectivity issues.

**Comment by dpaulson45** [comment]
Resolved in #1232
