### ISSUE TITLE
Current Exchange Build in this context is providing what was Exchange Build Number when running setup. When you have issues and you are troubleshooting Exchange Setup Issues, the Current Exchange Build with provide what you are currently on and the Setup Build of what you are trying to install.

### ISSUE THREAD

**Issue by Ashcjs** [microsoft/CSS-Exchange#1219]
Current Exchange Build in this context is providing what was Exchange Build Number when running setup. When you have issues and you are troubleshooting Exchange Setup Issues, the Current Exchange Build with provide what you are currently on and the Setup Build of what you are trying to install.

This value is coming from the ExchangeSetup.log file

_Originally posted by @dpaulson45 in https://github.com/microsoft/CSS-Exchange/issues/1136#issuecomment-1191978906_

**Comment by Ashcjs** [comment]
#1214

**Comment by dpaulson45** [comment]
@Ashcjs what is the point of this issue?

**Comment by lusassl-msft** [comment]
Closing this for now. Please file a new issue and formulate the request/question clearly.
