### ISSUE TITLE
Visualization of Exchange Extended Protection status for each webservice

### ISSUE THREAD

**Issue by gitblacker** [microsoft/CSS-Exchange#1223]
**Describe The Request**
The Result of Exchange Extended Protection is showing a list of all Webservices and it status. The problem is, that u can't see, which webservice is correct configured. There is only a warning, that the configuration of the items is noch correct.

**Reason:**
This would make a better vissualization, which service must be configured and which is also correct.

**Additional context**
Make an coloured visualization of the services which is correct configured

**Comment by dpaulson45** [comment]
@gitblacker is this the output of HealthChecker or ExchangeExtendedProtectionManagement? 

You able to provide a screenshot of what you are seeing?

**Comment by lusassl-msft** [comment]
@gitblacker have you had a chance to check the output of the latest version of the script? Is it still unclear or are we good with the way we show it in the latest version?

**Comment by lusassl-msft** [comment]
Closed due to no response.
