### ISSUE TITLE
HealthChecker doesn't skip the MS-Organization-P2P-Access [YYYY] Azure certificate

### ISSUE THREAD

**Issue by lusassl-msft** [microsoft/CSS-Exchange#1245]
**Describe the issue:**
The `MS-Organization-P2P-Access [YYYY]` certificate is still returned by HealthChecker (it should be skipped due to its short life cycle).

Originally addressed in #1119 

**Possible root cause:**
I guess the certificate is not self-signed (that's what we are currently looking for). Need to confirm with finder and if it's not self-signed, switch the flag to IsSelfSigned $false to properly detect and exclude the certificate.

More context:
Self-signed should be the Root certificate in this case (Subject & Issuer: `MS-Organization-P2P-Access [YYYY]`). However, in this case, the certificates with the short life cycle have a GUID as subject and Issuer is `MS-Organization-P2P-Access [YYYY]`). So they are not self-signed.

**Comment by lusassl-msft** [comment]
@JeremyTBradshaw could you please check if the certificate is self-signed or not (via Get-ExchangeCertificate)?

**Comment by lusassl-msft** [comment]
Thanks @JeremyTBradshaw. We've just released an updated version of the script. Please try it and see if it resolves the issue.

**Comment by JeremyTBradshaw** [comment]
@lusassl-msft This did in fact work - Thanks!  At first I was questioning how out of date the version I was using was.  I got if from the github.io page for CSS-Exchange.  I see it was Version 22.08.31.1532.  The reason I say this is that now the entire repo is a requirement for the script to run, whereas with the previous version, HealthChecker.ps1 was working standalone.  All good.

My lab's output is 99% green now, just need to add 112GB of RAM to get to the finish line 😂
