### ISSUE TITLE
[Issue] Search-AdminAuditLog does not work on passive mailbox database server after Extended Protection is enabled

### ISSUE THREAD

**Issue by EPI13760** [microsoft/CSS-Exchange#1256]
After enabling Extended Protection from the august security updates I am unable to execute the Search-AdminAuditlog cmdlet from the passive mailbox database server. The error given is from the MSExchange Management Event log, Error 6 :

Microsoft.Exchange.Management.SystemConfigurationTasks.AdminAuditLogSearchException: The attempt to search the administrator audit log failed. Please try again later. ---> Microsoft.Exchange.Data.ApplicationLogic.AuditLogException: An error occurred while trying to access the audit log. For more details, see the inner exception. ---> System.Net.WebException: The request failed with HTTP status 401: Unauthorized.

Disabling extended protection allows the cmdlet to execute from the passive database server.

Exchange 2019 CU12, health checker script on both servers is fully green after ExchangeExtendedProtectionManagement.ps1 is ran.

**Comment by dpaulson45** [comment]
@EPI13760 If you run the `ExchangeExtendedProtectionManagement.ps1` with the Mitigation for EWS Backend, do you run into the same problem. 

https://microsoft.github.io/CSS-Exchange/Security/Extended-Protection/

**Comment by EPI13760** [comment]
I do not, that solves the issue, thank you.
