### ISSUE TITLE
[Issue] - Health Checker: extended protection should be set to none on the vDir where IP filtering is enabled

### ISSUE THREAD

**Issue by cvocvo** [microsoft/CSS-Exchange#1260]
**Provide Version Number**
Provide the version of the script that has the issue.
latest version: Exchange Health Checker v22.09.21.1420

**Describe the issue**
A clear and concise description of the issue.
We had previously enabled extended protection in August for an on-prem Exchange Server 2019 CU12.
I re-ran the health checker script just to see where we're at with the latest 0day issues and it's flagging something interesting that we didn't notice previously.
After the security issues last year we went a bit further and added IP Address and Domain Restrictions on the virtual directories for ECP, EWS, and Powershell.

Now we're seeing this error and I'm not sure how to handle this:
![image](https://user-images.githubusercontent.com/355711/193629866-f44a4d80-3e3a-41ff-bfa6-5fca857751eb.png)

The documentation doesn't recommend turning off extended protection on virtual directories with IP address restrictions because it reduces security. It also mentions that it applies to the backend, however, the script is flagging the frontend virtual directories.
Our intentionality was to reduce the security footprint a bit last year by reducing which machines can hit these endpoints (/EWS, /ECP, and /Powershell)

**Expected behavior**

Not sure how to handle this; our configuration wasn't flagged in August but is now flagged. Our IP address and domain restrictions are configured on frontend Exchange web services virtual directories (not the backend). Thus the guidance (at least to me) doesn't appear very clear.

**Script Output**
If applicable, add the exception that wasn't handled.

**Additional context**

Any help would be greatly appreciated -- thank you!

**Comment by worldsdream** [comment]
+1

Would love to see some modifications in the health checker script that will give us a better understanding when you have ecp blocked for example.

**Comment by cvocvo** [comment]
> +1
> 
> Would love to see some modifications in the health checker script that will give us a better understanding when you have ecp blocked for example.

Agree; this link you mentioned in 1283 is what I based the idea on as well: https://www.alitajran.com/disable-external-access-to-ecp-exchange/
But I just expanded it out to ECP/EWS/Powershell virtual directories (because we don't have any services that need external access to those that I can't allow via IP.)

**Comment by dpaulson45** [comment]
After a discussion with product group, the stance of having Extended Protection enabled on ECP FE is still required to be considered secure. You can have both IP filtering enabled and EP, if you should choose too. 

For the virtual directories that have the supported value of `Allow` those will not be considered unsecure if set to `None` instead. Only the virtual directories that have the supported value of `Required` if not set to `Required` will be considered unsecure if not set.

**Comment by cvocvo** [comment]
>You can have both IP filtering enabled and EP, if you should choose too.
Great news -- we agree; we want to keep extended protection running (we already have it running) and we want to keep our IP address filtering in IIS. I don't really understand your Allow/Required/None comment and am stretched for time today to dig in and understand, but if it means we can run both on /ECP, /Powershell, and /EWS then we should be all set.
