### ISSUE TITLE
[Issue] - Health Checker Exchange 2019 PageFile report

### ISSUE THREAD

**Issue by d60-wizard** [microsoft/CSS-Exchange#1303]
**Provide Version Number**
22.10.17.1713

**Describe the issue**
Script generate PageFile report:
     "   PageFile: System is set to automatically manage the PageFile Size: 0MB
                Error: On Exchange 2019, the recommended PageFile size is 25% (4096MB) of the total system memory (16384MB).
                More information: https://aka.ms/HC-PageFile"

For Windows Server Core 2019 it is too difficult procedure. We can say that it is impossible.
How critical is it? Maybe it would be better to skip this check? In most cases, the administrator follows the recommendations, uses a sufficient amount of RAM and sets the automatic mode.

**Comment by lusassl-msft** [comment]
@d60-wizard it's one of the most important (and basic) things to have a properly configured pagefile to avoid performance issues and other things. On server core, pagefile can be configured via wmic. We can't remove the check here.

@dpaulson45 should we add the wmic command to the check documentation or should we perhaps even display it on the screen?

**Comment by dpaulson45** [comment]
@lusassl-msft I think just adding it to the docs should be good enough.

@d60-wizard this is an important setting to configure and is rather easy still on Windows Server Core. It is no more difficult than getting files onto the system from the terminal or configuring the name of the computer/IP Address.

**Comment by d60-wizard** [comment]
@lusassl-msft I agree, just adding "note for WS Core" to the doc-page on https://aka.ms/HC-PageFile

@dpaulson45 We don't have direct Powershell cmdlets to manage these parameters. And it's upsetting :(

**Comment by dpaulson45** [comment]
@d60-wizard while there are no PowerShell cmdlets that do this, you can still use a `wmic` cmd to configure your page file. 

```
wmic computersystem  set AutomaticManagedPagefile=False
wmic pagefileset  set InitialSize=1024,MaximumSize=1024
```

This is what I do for my labs.

**Comment by d60-wizard** [comment]
@dpaulson45 Thanks. I've already found it myself. It works
