### ISSUE TITLE
[Issue] - Health Checker - Warning - Missing Configuration File

### ISSUE THREAD

**Issue by tonibert** [microsoft/CSS-Exchange#1310]
**Provide Version Number**
22.10.28.0217

**Describe the issue**
Wrong Warning - Missing Configuration File
Missing: D:\Programme\Sophos\PureMessage\EndUserWebsite\web.config

**Expected behavior**
A message is reported that a file is missing from the Sophos folder. The description reports that the file is checked in the two folders.

C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy
C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess

**Additional context**
We use Sophos on the server.

**Comment by dpaulson45** [comment]
@tonibert - please send the two-output files to ExToolsFeedback@microsoft.com if you are able to.

**Comment by lusassl-msft** [comment]
Thanks @tonibert. @dpaulson45 I will investigate this. Received similar reports from other customers and internals as well.
