### ISSUE TITLE
HealthChecker  Ex2019 mentions

### ISSUE THREAD

**Issue by michelderooij** [microsoft/CSS-Exchange#1311]
HealthChecker doesn't mention Ex2019, only support for "Exchange 2013/2016"

**Comment by dpaulson45** [comment]
It is 100% supported for Exchange 2019. 

https://microsoft.github.io/CSS-Exchange/Diagnostics/HealthChecker/

The comments within the header of the script however doesn't have 2019 mention there. Would need to update this to state something like `HealthChecker is supported on all supported versions of Exchange`

**Comment by michelderooij** [comment]
Exactly that. Thanks
