### ISSUE TITLE
[Feature Request] EOMTv2 to indicate if mitigation is in place, prompt to remove if Nov 2022 patch installed?

### ISSUE THREAD

**Issue by boogieshafer** [microsoft/CSS-Exchange#1344]
**Is your request related to a problem? Please describe.**
A clear and concise description of what the problem is and the results it had on the environment.

not a problem but a request to improve usability of the EOMTv2 script

**Describe The Request**
A clear and concise description of the feature to add to a current tool or a new tool with what we all want to be checking with examples.

i noticed a few things when using the EOMTv2 script today after applying the Nov 2022 updates
- the script DOES currently detect if the Nov 2022 updates are installed
- the script DOES NOT give an indication if the script mitigations are already applied
- using the "-Rollbackmitigations" option seems to take a very long time to complete (was stuck for several minutes at the "starting rollback" status message before completing

suggest a few possible enhancements
- adding indication of whether scripts mitigations have been previously applied
- adding prompt to remove the mitigations if the Nov 2022 updates are already installed

**Additional context**
<img width="998" alt="Screen Shot 2022-11-10 at 10 27 07" src="https://user-images.githubusercontent.com/714141/201180048-40582d2d-7af8-40bf-8cc2-8d3f069a05f9.png">

**Comment by boogieshafer** [comment]
in the logs for EOMTv2 rollback run i'm seeing ~10min time to complete
<img width="497" alt="Screen Shot 2022-11-10 at 12 07 25" src="https://user-images.githubusercontent.com/714141/201195430-7f4690c7-02ee-4c99-9ad9-04353c74a981.png">

**Comment by lusassl-msft** [comment]
Identified the slow call. It's in line `291` --> `$Rules = Get-WebConfiguration -Filter 'system.webServer/rewrite/rules/rule' -Recurse`

**Comment by dpaulson45** [comment]
Same as issue #1259 for the long time for rollback.

**Comment by lusassl-msft** [comment]
@boogieshafer we've addressed the rollback performance issue. It should now run faster. The script should now prompt if the November 2022 SU is installed, and the mitigation is in place. It will not prompt if an older (vulnerable) Exchange build is installed, and the mitigation is in place. This is expected as we always override any existing mitigation automatically to ensure the latest one is in place. However, the mitigation should no longer be used - instead install the November 22 SU.
