### ISSUE TITLE
[Issue] - Health Checker - Cannot convert value "System.Object[]" to type "System.Xml.XmlDocument"

### ISSUE THREAD

**Issue by roytm** [microsoft/CSS-Exchange#1387]
**Provide Version Number**
22.12.19.1649

**Describe the issue**
Failed to Health Checker against Exchange Server

**Expected behavior**
execute successfully

**Script Output**
Exchange Health Checker version 22.12.19.1649
Failed to Health Checker against CHSEXCH01

There appears to have been some errors in the script. To assist with debugging of the script, please send the HealthChecker-Debug_*.txt, HealthChecker-Errors.json, and .xml file to ExToolsFeedback@microsoft.com.
Output Debug file written to .\HealthChecker-Debug_20221220103922.txt

**Additional context**
The other member of DAG can run the script successfully.

**Comment by dpaulson45** [comment]
Can you provide the debug information as the script provides to [ExToolsFeedback@microsoft.com](mailto:ExToolsFeedback@microsoft.com)

**Comment by roytm** [comment]
Sill no luck. I have compared the applicationHost.config file with the one on another DAG member can run Healthchecker, pretty much the same.
