### ISSUE TITLE
Server 2012 Test-ProxyLogon.ps1 Exchange 2010 Import-CSV error

### ISSUE THREAD

**Issue by Bf2multi100** [microsoft/CSS-Exchange#141]
I was able to try running the Test-ProxyLogon.ps1 on our server 2012r2 with PS v4, since our original exchange server was 2008r2. 

However, the script errored out at line 122 character 66, screenshot below.

I ensured the PS v4 was being used and opened a new powershell window on the server:

![image](https://user-images.githubusercontent.com/77888222/110324905-38f44f80-7fdc-11eb-975b-d1a4dcab37f7.png)

The account running the script is a domain admin.

**Comment by bill-long** [comment]
Please see here regarding 2010 support: https://github.com/microsoft/CSS-Exchange/issues/108#issuecomment-793045938

Closing as duplicate of #108
