### ISSUE TITLE
Silent-Mode possible for scriptings?

### ISSUE THREAD

**Issue by airathere** [microsoft/CSS-Exchange#1411]
we are using HealthChecker for several scriptings and it would be preferred, if there is an additional "silent" parameter for it.
e.g. running "HealthChecker.ps1 -ScriptUpdateOnly" results in
...
No update of the script performed.
Do you like the script? Visit https://aka.ms/HC-Feedback to rate it and to provide feedback.
...
which is not preferred by us due to several scriptings running after it - so the output we are generating has too much infos we don't like to see.

Is there a possibility to implement this in future versions?

**Comment by dpaulson45** [comment]
@airathere are you talking about just the update functionality or the entire output possibility that Health Checker does provide?

**Comment by airathere** [comment]
it would be nice to have it for all parameters, so "-ScriptUpdateOnly" was only an example. We are also using the others, like checking for vuln reports ect.

**Comment by bill-long** [comment]
PowerShell already supports redirecting all output to $null. I don't think we need to implement this in the script. Syntax:

```
.\HealthChecker.ps1 *>$null
```

Example:

![image](https://user-images.githubusercontent.com/4518572/210605272-af78784f-3990-482a-9263-94fb1886e9b9.png)

Redirecting output streams is documented here:

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_redirection

**Comment by airathere** [comment]
We run, as mentioned at the beginning, the HealthChecker in scripts.
So here for example, i run test.ps1:

`Add-PSSnapin Microsoft.Exchange*
$mylogtemp = "C:\temp"
$myscriptpath = "C:\scripts"

cd $myscriptpath
.\HealthChecker.ps1 -ScriptUpdateOnly -OutputFilePath $mylogtemp *>$null`

Result:
we get an unwanted output:

`PS C:\> C:\Users\Administrator.INTRA\Desktop\test.ps1
No update of the script performed.
Do you like the script? Visit https://aka.ms/HC-Feedback to rate it and to provide feedback.

PS C:\Scripts>`

**Comment by airathere** [comment]
You are right ;-)
After your hint we recognized, that it has to do with the PS Version we are laying on.
e.g. on older machines (wss 2012r2 or 2016) we have this problem, with the new ones (wss 2019, 2022) not.
so: solved!
