### ISSUE TITLE
[Issue]errors when running on exc2016

### ISSUE THREAD

**Issue by scivi92** [microsoft/CSS-Exchange#143]
Ran Ok Saturday but version since throw errors:
Running on Exchange management shell locally on server 2016 with exc 2016,
also tried running remote powershell from latest build Windows 10 machine and loading EMS but same errors.
Go back to the ps1 I downloaded saturday and I get no errors....

+ <html lang="en" >
+                  ~
Missing file specification after redirection operator.
At C:\temp\Test-ProxyLogon.ps1:168 char:35
+                 {&quot;hydro-click&quot;=&gt;&quot;{\&quot;event_type ...
+                                   ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\temp\Test-ProxyLogon.ps1:168 char:42
+                 {&quot;hydro-click&quot;=&gt;&quot;{\&quot;event_type ...
+                                          ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.                                                                   At C:\temp\Test-ProxyLogon.ps1:168 char:54                                                                              +                 {&quot;hydro-click&quot;=&gt;&quot;{\&quot;event_type ...                                             +                                                      ~                                                                The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\temp\Test-ProxyLogon.ps1:168 char:71
+ ...       {&quot;hydro-click&quot;=&gt;&quot;{\&quot;event_type\&quot;:\& ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\temp\Test-ProxyLogon.ps1:168 char:79
+ ... quot;hydro-click&quot;=&gt;&quot;{\&quot;event_type\&quot;:\&quot;ana ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\temp\Test-ProxyLogon.ps1:168 char:101
+ ... =&gt;&quot;{\&quot;event_type\&quot;:\&quot;analytics.click\&quot;,\& ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\temp\Test-ProxyLogon.ps1:168 char:108
+ ... quot;{\&quot;event_type\&quot;:\&quot;analytics.click\&quot;,\&quot;p ...
+                                                                  ~
Missing expression after unary operator ','.
At C:\temp\Test-ProxyLogon.ps1:168 char:108
+ ... uot;{\&quot;event_type\&quot;:\&quot;analytics.click\&quot;,\&quot;pa ...
+                                                                 ~
Unexpected token '\' in expression or statement.
At C:\temp\Test-ProxyLogon.ps1:168 char:109
+ ... ot;{\&quot;event_type\&quot;:\&quot;analytics.click\&quot;,\&quot;pay ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingFileSpecification**Describe the issue**
A clear and concise description of what the issue is, including what script you are seeing the error in.

**Expected behavior**

**Script Output**
If applicable, add the exception that you are seeing that wasn't handled.

**Additional context**

**Comment by bill-long** [comment]
There are no ampersand characters in the script. Please make sure you download the script from the download link on the [Security page](https://github.com/microsoft/CSS-Exchange/tree/main/Security):

![image](https://user-images.githubusercontent.com/4518572/110339700-110de780-7fee-11eb-8f5e-b319551b7391.png)

I think you might have downloaded the web page or something.

**Comment by scivi92** [comment]
Got it thanks, I was right-clicking from the file list above and it was downloading from: https://github.com/microsoft/CSS-Exchange/blob/main/Security/Test-ProxyLogon.ps1
