### ISSUE TITLE
[Issue] VMWare tools vss_manifests.zip identified suspicious when its normal.

### ISSUE THREAD

**Issue by cypherstream** [microsoft/CSS-Exchange#145]
**Describe the issue**
"SuspiciousArchive","C:\ProgramData\VMware\VMware Tools\vss_manifests.zip","vss_manifests.zip"

**Expected behavior**
vss_manifests.zip seems to be a normal VSS debug logging interaction between vmware tools and veeam backups.

**Script Output**
Other suspicious files found: 1

**Additional context**
Opening the archive file noted as suspicious C:\ProgramData\VMware\VMware Tools\vss_manifests.zip shows a bunch of xml files
backup.xml, writer1.xml through writer15.xml.  Most files being only a few KB to 32KB in size, but writer7.xml being 5,055 KB in size.  The text in these files look benign and not suspicious at all.  A google search on this file shows legitimate internet postings.  I suggest omitting this file from the search results.

**Comment by bill-long** [comment]
I'm not sure we should whitelist anything. If we whitelist vss_manifests.zip, bad actors can simply change their code to save files in vss_manifests.zip, know that we won't flag it.

**Comment by bill-long** [comment]
This is a "won't fix" for now.
