### ISSUE TITLE
Unable to find type [pscredential]: make sure that the assembly containing this type is loaded.

### ISSUE THREAD

**Issue by badseedjr** [microsoft/CSS-Exchange#148]
**Describe the issue**
When running the script locally on the CAS server or remotely using the get-exchangeserver command, it returns an error

**Expected behavior**
Script output and testing

**Script Output**
Unable to find type [pscredential]: make sure that the assembly containing this type is loaded.

**Additional context**
Exchange 2010.

**Comment by bill-long** [comment]
Duplicate of #108 . Please see that issue for the workaround but you will immediately run into more issues.
