### ISSUE TITLE
[Issue] - Health Checker 23.02.16.1810 throwing new error about Bin Search folder

### ISSUE THREAD

**Issue by boogieshafer** [microsoft/CSS-Exchange#1506]
**Provide Version Number**
23.02.16.1810

**Describe the issue**
in the 23.02.16.1810 version i'm seeing a new error for "Bin Search Folder Not Found"

havent seen this issue before in previous runs and i'm now seeing it on all instances 

also didnt see it on feb 14 in wake of the installs of the feb updates

**Expected behavior**
unclear what the issue is as looking at the linked article the suggested values for the bin search path appear to match exactly

**Script Output**
"Bin Search Folder Not Found"

**Additional context**

**Comment by dpaulson45** [comment]
This link should be included below the error message at some point. https://aka.ms/HC-BinSearchFolder

Please follow the documentation there.

**Comment by hellofaduck** [comment]
Same problem, but evething on my exchange DAG works fine...

**Comment by cefi1846** [comment]
Same here.  Everything works perfectly.  The binserch paths are fully qualified and accessible in Explorer.  bug?

**Comment by dpaulson45** [comment]
After making the change in commit https://github.com/microsoft/CSS-Exchange/commit/7d58536ed7d508db0c8bc256b38769332429aa4f with using `-Raw` changed how we are required to analyze the `web.config` files.

Could revert the change, but then we increase the export size by about 300%. So instead working on changing the analyzing logic to handle this in the new format.
