### ISSUE TITLE
[Issue] - ExchangeExtendedProtectionManagement.ps1 - "This script requires to be run inside of Exchange Management Shell"

### ISSUE THREAD

**Issue by 10kingsam** [microsoft/CSS-Exchange#1507]
**Describe the issue**
Version 23.02.14.1742 (latest at time of writing) of the ExchangeExtendedProtectionManagement.ps1 script

When running .\ExchangeExtendedProtectionManagement.ps1 I get a warning saying that the script needs to be run in Exchange Management Shell, despite the fact that that's where I'm running it.

None of the switches change this

Exchange 2019 (15.02.1118.25) Latest CU and SU

**Expected behavior**
The script should be able to run

**Script Output**
The Debug.txt file generated

[02/17/2023 11:59:30] : Starting Logger Instance 02/17/2023 11:59:30
[02/17/2023 11:59:30] : Calling: Confirm-ExchangeShell
[02/17/2023 11:59:30] : Passed: LoadExchangeShell: True
[02/17/2023 11:59:32] : Exchange PowerShell Module already loaded.
[02/17/2023 11:59:32] : WARNING: This script requires to be run inside of Exchange Management Shell. Please run on an Exchange Management Server or an Exchange Server with Exchange Management Shell.
[02/17/2023 11:59:32] : Do you have feedback regarding the script? Please email ExToolsFeedback@microsoft.com.

**Additional context**
The issue was mentioned here, but it was apparently resolved.

https://techcommunity.microsoft.com/t5/exchange-team-blog/an-update-to-the-exchange-server-extended-protection-script-is/bc-p/3638447

**Comment by 10kingsam** [comment]
I am still experiencing this issue with the latest version of the script (23.03.01.1646), but I can confirm that disabling SerializedDataSigning seems to fix it.

Happy to run the EEPM script first and then enable SerializedDataSigning if this is a suitable workaround and won't cause issues?

**Comment by lusassl-msft** [comment]
@10kingsam could you please try to run the latest version and share the verbose / debug log with us? We added some additional logging to get a better understanding of the issue. Thanks

**Comment by 10kingsam** [comment]
Please see below the log generated from the latest version of the script (including the object type).

Let me know if there is anything else I can do to help diagnose this, thank you.

[03/03/2023 10:02:47] : Starting Logger Instance 03/03/2023 10:02:47
[03/03/2023 10:02:47] : Calling: Confirm-ExchangeShell
[03/03/2023 10:02:47] : Passed: LoadExchangeShell: True
[03/03/2023 10:02:49] : Type is: PSObject BaseType is: System.Object
[03/03/2023 10:02:49] : Exchange PowerShell Module already loaded.
[03/03/2023 10:02:49] : WARNING: This script requires to be run inside of Exchange Management Shell. Please run on an Exchange Management Server or an Exchange Server with Exchange Management Shell.
[03/03/2023 10:02:49] : Do you have feedback regarding the script? Please email ExToolsFeedback@microsoft.com.

**Comment by lusassl-msft** [comment]
@10kingsam I'm still trying to repro the behavior but wasn't successful yet. Can you please share the repro steps. My understanding from your initial comment is the following:

1. Enable Serialized Data Signing
2. Start Exchange Management Shell on an Exchange Server 2019 running the latest CU and SU (is it a Windows Core server?)
3. Run the latest version of the .\ExchangeExtendedProtectionManagement.ps1 script without specifying any parameter

Result: `[03/03/2023 10:02:49] : WARNING: This script requires to be run inside of Exchange Management Shell. Please run on an Exchange Management Server or an Exchange Server with Exchange Management Shell.` is being displayed and execution of the script stops

Is this correct?

**Comment by 10kingsam** [comment]
Hi, that understanding is exactly correct.

[HealthChecker-BENDER-20230303141212.txt](https://github.com/microsoft/CSS-Exchange/files/10882877/HealthChecker-BENDER-20230303141212.txt)


I have attached the output of the HealthChecker script to confirm these (I know there are some other issues in there, it is all being worked on). Hopefully this will confirm the Data Signing setting and the CU/SU version and possibly help with the diagnostics.

I can also confirm that the .\ExchangeExtendedProtectionManagement.ps1 script has the same output (This script requires to be run....) whether parameters are specified or not

**Comment by dpaulson45** [comment]
> Hi, that understanding is exactly correct.
> 
> [HealthChecker-BENDER-20230303141212.txt](https://github.com/microsoft/CSS-Exchange/files/10882877/HealthChecker-BENDER-20230303141212.txt)
> 
> I have attached the output of the HealthChecker script to confirm these (I know there are some other issues in there, it is all being worked on). Hopefully this will confirm the Data Signing setting and the CU/SU version and possibly help with the diagnostics.
> 
> I can also confirm that the .\ExchangeExtendedProtectionManagement.ps1 script has the same output (This script requires to be run....) whether parameters are specified or not

Being that you ran an older version of `HealthChecker.ps1`, makes me wonder if you are running the latest version of `ExchangeExtendedProtectionManagement.ps1`. Please download the latest version of the script [here](https://github.com/microsoft/CSS-Exchange/releases/latest/download/ExchangeExtendedProtectionManagement.ps1) and see if the same issues still occur. If it does, please provide the output again so we can confirm.

**Comment by 10kingsam** [comment]
My apologies, I ran an old version of the HealthChecker script (was already on the server) knowing that it would auto-update, but didn't notice that the auto update failed.

I can assure you that I am downloading the latest version of the EEPM script, directly from the Github releases directory.

Please see attached an output from the latest HealthChecker.ps1 script (manually downloaded)

[HealthChecker-BENDER-20230303153419.txt](https://github.com/microsoft/CSS-Exchange/files/10883567/HealthChecker-BENDER-20230303153419.txt)

Please also see the log output of the EEPM script below (very latest version, release from about 30 minutes ago, looks like it now includes the version number)

[ExchangeExtendedProtectionManagement-20230303034028-Debug.txt](https://github.com/microsoft/CSS-Exchange/files/10883592/ExchangeExtendedProtectionManagement-20230303034028-Debug.txt)

**Comment by dpaulson45** [comment]
@10kingsam what I think is going on is the difference between Health Checker and EEPM. 

EEPM requires you to be in EMS. Meaning, you can't use Connect to Exchange Servers using remote PowerShell. - https://learn.microsoft.com/en-us/powershell/exchange/connect-to-exchange-servers-using-remote-powershell?view=exchange-ps
Runing EEPM this way does cause a failure like you are seeing but it should occur with SerializedDataSigning enabled and not enabled. Therefore, it shouldn't matter if you have SerializedDataSigning enabled or not so that is where I am confused about why this isn't working for you.

Health Checker is designed where we support it being run within Remote PowerShell as well.

The only thing I haven't tested is from a Tools Machine. If you are running it from there, that might be the problem. Try running this from an Exchange Server.

**Comment by 10kingsam** [comment]
I have been running this on an Exchange Server directly, please see attached a screenshot that shows the EMS windows and the Exchange services running 

![Exchange](https://user-images.githubusercontent.com/68732863/223104611-d5a8a59f-45aa-4eab-a8e6-7ddbbffa3acc.png)

As far as I am aware this is a pretty basic on-prem Windows 2019 Server with Exchange 2019 installed.

I am happy to gather any data/run any scripts on the server that may help diagnose this.

Thank you for your help and time thus far

**Comment by 10kingsam** [comment]
Get-ExchangeCertificate just had empty columns as below

![Get-ExchangeCertificate](https://user-images.githubusercontent.com/68732863/224009776-fc43683a-3a11-42bd-be90-abfba0884803.png)

Looks like most things are on "Lowest", please see a .txt file generated from running "Get-EventLogLevel > C:\loglevel.txt" below

[loglevel.txt](https://github.com/microsoft/CSS-Exchange/files/10930877/loglevel.txt)

**Comment by 10kingsam** [comment]
Your comment above about Get-ExchangeCertificate and Serialization not working pointed me in the right direction.

Looks like the internal Exchange Auth Certificate had expired (my fault for missing that on the Serialization prerequisites).

After running MonitorExchangeAuthCertificate.ps1 and letting it renew the cert, the Get-ExchangeCertificate command returned data in the columns.

Then doing steps two and three of Serialization again (Refresh the VariantConfiguration and restart the World Wide Web Publishing service and the Windows Process Activation Service (WAS)) allowed EEPM to run as expected.


As the docs say, having an expired Auth certificate means Serialization doesn't work, but it looks like when it is "enabled" and not working that causes the EEPM script to fail with "This script requires to be run inside of Exchange Management Shell".

My apologies for missing that, thank you both for all of your help on this.

**Comment by Julien-nl** [comment]
i have been following the post very closley.
i am facing the same issue, certificate was expired and i have renew it.
i still cannot run the scripts too. and also the owa is not opening comes back with Microsoft.Exchange.Security.OAuth.OAuthTokenRequestFailedException X-OWA-Version 15.2.1258.23 X-FEServer EX01-DLS.
i am not trying to hijack your post, but if i have to open a new threat let me know thank you

**Comment by dpaulson45** [comment]
@Julien-nl it seems that you might have more issues that just with the script. We can't troubleshoot the environment issues here, please open a case to have someone investigate this.
