### ISSUE TITLE
ExchangeExtendedProtection - Always asks for authorization

### ISSUE THREAD

**Issue by Asmund22** [microsoft/CSS-Exchange#1513]
Describe the issue
Microsoft Exchange 2019 CU12 Feb23SU
After applying ExchangeExtendedProtectionManagement, on some client devices, Outlook keeps asking for the password without accepting the correct password, asking for it over and over again

Expected behavior
ExtendedProtection enabled and successful authorization in Windows Outlook

Additional context
If in IIS in the DefaultWebSite branch in the MAPI section turn off mandatory Windows authentication, Outlook already starts to let into the user interface, but asks for the password again, if you click "Cancel" for a while the connection works and you can even send the letter, but after a while again asks for the password and does not accept the correct one. But this is not a solution to the problem, just writing a note, what the problem may be related (may be)

**Comment by lusassl-msft** [comment]
@Asmund22 this sounds like some configuration in your environment isn't configured as expected to work with Exchange Exteded Protection.

It could be related to NTLMv1, SSL-Offloading, third party applications intercepting the connection etc. .

Please check the Exchange Extended Protection documentation:
https://microsoft.github.io/CSS-Exchange/Security/Extended-Protection/

You should open a Microsoft support case if you need troubleshooting assistance.
