### ISSUE TITLE
[Work Item] Update Test-ExchAVExclusions to follow latest recommendations

### ISSUE THREAD

**Issue by ParaGlideRocks** [microsoft/CSS-Exchange#1517]
Recently EHLO blog has published the latest recommendations regarding AV exclusions for Exchange. Please modify the Test-ExchAVExclusions to not check these folders:

%SystemRoot%\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files
%SystemRoot%\System32\Inetsrv

Source
https://techcommunity.microsoft.com/t5/exchange-team-blog/update-on-the-exchange-server-antivirus-exclusions/ba-p/3751464

**Comment by dpaulson45** [comment]
@ParaGlideRocks this should be done within the latest release of the script. Try it out.

**Comment by lusassl-msft** [comment]
For reference: Exclusions updated via PR #1516

**Comment by lusassl-msft** [comment]
And another one: PR #1531

**Comment by lusassl-msft** [comment]
Should be fixed now. Please let us know if something is still wrong.
