### ISSUE TITLE
ExperfWiz.ps1

### ISSUE THREAD

**Issue by startochka** [microsoft/CSS-Exchange#1522]
Administrator-confirm seems to be missing.
Confirm-Administrator.ps1 script missing.

**Comment by dpaulson45** [comment]
@startochka `Confirm-Administrator` function is within the script. What is the error you are getting? Please provide more context.

**Comment by lusassl-msft** [comment]
@startochka please download the script from here: https://github.com/microsoft/CSS-Exchange/releases/tag/v23.02.28.1737

**Comment by startochka** [comment]
> @startochka `Confirm-Administrator` function is within the script. What is the error you are getting? Please provide more context.
I'll try to execute scripts from here https://github.com/microsoft/CSS-Exchange/blob/main/Performance/ExPerfWiz/ExPerfWiz.ps1
if you look at this script you will see administrator-confirm.ps1 at line 22. this file is missing and function couldn't be initialize (line 344) when you trying to execute experfwiz.ps1

**Comment by lusassl-msft** [comment]
@startochka this is expected as the final script needs to be built by our build and release pipeline. Download it from here and you should be good: https://github.com/microsoft/CSS-Exchange/releases

**Comment by startochka** [comment]
> @startochka this is expected as the final script is built by our build and release pipeline. Download it from here and you should be good: https://github.com/microsoft/CSS-Exchange/releases

Thank you very much. If it possible pls add direct link to the latest release of this script at https://microsoft.github.io/CSS-Exchange/Performance/ExPerfWiz/

Thanks again

**Comment by lusassl-msft** [comment]
@startochka yep, we can do that.
