### ISSUE TITLE
Extended Protection authorization issue

### ISSUE THREAD

**Issue by Asmund22** [microsoft/CSS-Exchange#1533]
Hi. Please tell me if anyone has encountered this problem. 
I followed the manual "https://microsoft.github.io/CSS-Exchange/Security/Extended-Protection/" strictly.  After enabling Extended Protection on some users' devices, Outlook does not connect, keeps asking for password and does not let me authorize. The problem is not NTLM or SLL unloading. 
After that, I rolled back the script and started enabling all the settings manually one by one in IIS. And this problem appeared when I enabled Windows Authentication (Extended Security) in DefaultWebSite under RPC. This problem occurs not on all devices in the local network, but only on some, a pattern I have not identified.

**Comment by Asmund22** [comment]
> @Asmund22 did you verify that the Outlook client isn't forced to use NTLMv1 as the article provides?
> 
> ![image](https://user-images.githubusercontent.com/22776718/222449206-1457a21c-3ec9-4142-8f3c-fbe0bf4e77c3.png)
> 
> If you are still having issues with connectivity, then you must open a ticket for investigation. The issues on GitHub are for issues with running the script. Not for issues with the product. The script is to assist you with enabling Extended Protection against your Exchange Server correctly.

I'm sure all clients only use NTLMv2.

**Comment by dpaulson45** [comment]
> I'm sure all clients only use NTLMv2.

Then you would likely need to open a case to troubleshoot the issue to determine why your environment is experiencing the problem.

**Comment by dpaulson45** [comment]
Closing issue, no issue with script.
