### ISSUE TITLE
[Issue] - Health Checker

### ISSUE THREAD

**Issue by thmeyer-msft** [microsoft/CSS-Exchange#1675]
**Provide Version Number**
23.03.23.1504

**Describe the issue**
Old edge servers still in report, new edge servers missing

**Expected behavior**
The current edge servers are in the report
![Screenshot 2023-04-25 134653](https://user-images.githubusercontent.com/51437404/234267010-a51438bf-d9eb-45ba-82c9-cb9e256ce87b.png)

**Comment by dpaulson45** [comment]
How is the script being run? Health Checker doesn't work remotely against Edge Servers because you shouldn't have the same creds to access the Edge Server as you do the Mailbox Exchange Servers.

**Comment by thmeyer-msft** [comment]
Hi David, 
it runs on the exchange sever as regular Exchange Admin, and yes you're right the Edge servers do have other credentials...
The point is, why the new servers doesn't get recognized and the old does....

**Comment by dpaulson45** [comment]
This actually appears to be coming from our Hybrid information data collection. After creating the new edge servers, did you run the HCW?

**Comment by dpaulson45** [comment]
That data is coming from `Get-HybridConfiguration` on the server itself.

**Comment by dpaulson45** [comment]
Closing out issue as this should be an issue within the environment not Health Checker, as this data is collected via `Get-HybridConfiguration`. If that isn't the case, please reopen with more information.
