### ISSUE TITLE
Unable to assign permissions to Public Folders through Outlook after running ExchangeExtendedProtectionManagement.ps1 

### ISSUE THREAD

**Issue by MAF-BAI** [microsoft/CSS-Exchange#1681]
Recently ran the Exchange Extended Protection script on our on prem Exchange 2016 CU23 server. Since then, I am unable to apply permissions to Public Folders through Outlook. I receive error "The modified Permissions cannot be saved".  Before I roll back the script, I wanted to see if there are any known issues or workarounds for this error.

**Comment by dpaulson45** [comment]
@MAF-BAI are you sure that all your Exchange 2016 servers are on the same build? There is an issue if you had the public folder hierarchy mailbox on a lower version. 

https://microsoft.github.io/CSS-Exchange/Security/Extended-Protection/

If you are on the latest version for all your servers, then try to roll back and see if the issue persists. If it doesn't continue, please let us know.

**Comment by MAF-BAI** [comment]
We only have one Exchange Server.

I did try to rollback using the following command:
C:\> .\ExchangeExtendedProtectionManagement.ps1 -RollbackType "RestoreIISAppConfig"
But it didn’t seem to rollback. Previously when running the HealthChecker script, it would indicate that Extended Protection wasn’t configured. After the rollback, I expected to run HealthChecker and receive the same indication and it does not have that indication. I am still not able to apply permissions through Outlook, but I am not sure that the rollback worked.

Melissa

**Comment by MAF-BAI** [comment]
Thank you. I had misread the message. I thought the script ran and was showing succeeded, but it was a success message on the script update. I reran the command and it shows it was successfully restored. Confirmation when running HealthChecker, it shows Extended Protection is not enabled. Not sure why I lost the ability to assign permissions through Outlook, but functionality is restored after rollback. Thanks.

**Comment by lusassl-msft** [comment]
@MAF-BAI this issue has been fixed with the latest Exchange Server Security Update (https://techcommunity.microsoft.com/t5/exchange-team-blog/released-june-2023-exchange-server-security-updates/ba-p/3845326). 

See: https://support.microsoft.com/en-us/topic/extended-protection-doesn-t-support-public-folder-client-permissions-management-through-outlook-bd2037b5-40e0-413a-b368-746b3f5439ee
