### ISSUE TITLE
[Work Item] Adjustment of Extended Protection callout

### ISSUE THREAD

**Issue by johage** [microsoft/CSS-Exchange#1685]
**Describe the work**
Currently when Extended Protection isn't configured we have the phrasing being used:
"Extended Protection isn't configured as expected"

I think the phrasing should handle two scenarios instead:
All Values are None - Extended Protection is not configured.
One or more Values are NOT None - Extended Protection is not configured as expected.

**Additional Context**
The goal is to add more clarity around whether or not the customer has TRIED to configure EP and done so incorrectly or not.

**Comment by dpaulson45** [comment]
@lusassl-msft What do you think about this? With the new change that is coming soon, do you think that this is needed?

**Comment by dpaulson45** [comment]
@lusassl-msft Can you take a look at this?

**Comment by lusassl-msft** [comment]
@dpaulson45 yes, I will take a look here. Have self-assigned it to me.

**Comment by dpaulson45** [comment]
After a conversation with Josh, we just need to provide that if Extended Protection is not configured at all provide that it is not configured vs stating not configured as expected.
