### ISSUE TITLE
CompareExchangeHashes.ps1 Generating "NoHashMatch" for entire install [Issue]

### ISSUE THREAD

**Issue by michaelfischler** [microsoft/CSS-Exchange#170]
**Describe the issue**
I've run this script against three Exchange 2013 servers and all three produce a ~15,000 row CSV with every entry stating "NoHashMatch." Two are were recently upgraded to 15.0.1497.2, one is on 15.0.847.32, and the script does appear to be recognizing and downloading the proper baseline.zip. Let me know if there's any more info I can provide to assist - I can attach the CSV if that's useful.

**Comment by h0mz** [comment]
Same issue here.

**Comment by rahmnstein** [comment]
Same here! CU23 with patch installed

What version number would that be? 

CompareExchangeHashes.ps1 seems to think 15.0.1497.2 but it also finds files which is 15.0.1497.12 that it cannot validate the hash for.

(Import-Csv .\15.0.1497.2_result.csv | select -ExpandProperty filepath ) -replace '.*?((prem\\)?[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+|Current(2)?).*','$1' | Group-Object | sort count | ft count,name -AutoSize

Count Name             
----- ----             
    5 15.0.1497.12
    5 Current
 2105 prem\15.0.847.32 
 2285 Current2         
 2285 prem\15.0.1497.12

The first two with count 5 is the files below:

 C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\15.0.1497.12\scripts\premium\uglobal.js
 C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\Current\scripts\premium\uglobal.js

And the difference between them and the one that comes with CU23 installmedia is a version number:

 InputObject                 SideIndicator
-----------                 -------------
var g_ver = "15.0.1497.0";  =>           
var g_ver = "15.0.1497.12"; <=

**Comment by ericwbentley** [comment]
I believe I'm having the same issue. I'm using the latest version of CompareExchangeHashes.ps1, downloaded from release v21.03.09.1826.
It looks like it's comparing my install to multiple baselines, even though it initially matched version 15.1.2176.2 correctly

```
[PS] C:\Script>.\CompareExchangeHashes.ps1
[03/09/2021 10:07:17] Started...
Found exchange version: 15.1.2176.2
Can't find local baseline for 15.1.2044.8
Loading C:\Script\baseline_15.1.2044.8.zip from GitHub...
Can't find local baseline for 15.1.2044.12
Loading C:\Script\baseline_15.1.2044.12.zip from GitHub...
Can't find local baseline for 15.1.2044.4
Loading C:\Script\baseline_15.1.2044.4.zip from GitHub...
Can't find local baseline for 15.1.2176.9
Loading C:\Script\baseline_15.1.2176.9.zip from GitHub...
Can't find local baseline for 15.1.1531.3
Loading C:\Script\baseline_15.1.1531.3.zip from GitHub...
Can't find local baseline for 15.1.2176.2
Loading C:\Script\baseline_15.1.2176.2.zip from GitHub...
Can't find local baseline for 15.1.1979.3
Loading C:\Script\baseline_15.1.1979.3.zip from GitHub...
BaselineData - 15.1.2044.8 15.1.2044.12 15.1.2044.4 15.1.2176.9 15.1.1531.3 15.1.2176.2 15.1.1979.3 15.1.2176.2
```

Resulted in a ~13,000 line .csv with every line being NoHashMatch. It also includes duplicate lines, the same file is matched 6 or 7 times

**Comment by psykokwak4** [comment]
> Looks better but still finds all files in owa\prem\15.0.847.32 on my two 2013 installs. I see that I have a baseline file downloaded for that version which is strange: baseline_15.0.847.32

could you share script output? do you have `Loaded baseline for 15.0.847.32, hashes number <number>`?

and will changing the below line
https://github.com/microsoft/CSS-Exchange/blob/d95e5e70a17a8baaa3661c507a32418f044091d5/Security/CompareExchangeHashes.ps1#L565
to
` $vdir_paths | Where-Object { Test-Path $_ } | ForEach-Object { Get-ChildItem -Directory -Path $_ -Recurse } | Where-Object { $VALID_VERSIONS[$_.Name] -eq $true } | ForEach-Object { $versions[$_.Name] = $true } `

help? currently script assumes versions can only be found from vdir physical path's top level subfolders

**Comment by michaelfischler** [comment]
I ran the latest script on the same 3 servers and now get ~150-200 MB CSVs with ~30-40,000 rows.

**Comment by psykokwak4** [comment]
> I ran the latest script on the same 3 servers and now get ~150-200 MB CSVs with ~30-40,000 rows.

please wait for next PR/release for this fix

**Comment by anshuldube** [comment]
This issue should be fixed. please feel free to reopen if it still persists.
