### ISSUE TITLE
[Issue] - Set-ExchAVExclusions  - OICE exclusion

### ISSUE THREAD

**Issue by nelemos** [microsoft/CSS-Exchange#1714]
About the script Set-ExchAVExclusions I noticed a strange behaviour about OICE exclusions.
It is managed this way:
 
#'$env:SystemRoot\Temp\OICE_<GUID>'
        $possibleOICEFolders = Get-ChildItem $env:SystemRoot\temp -Directory -Filter OICE_*.0
        $possibleOICEFolders | ForEach-Object {
            if ( $_.Name.Length -gt 41) {
                $possibleGUID = $_.Name.Substring(5, 36)
                $result = [System.Guid]::Empty
                if ( [System.Guid]::TryParse($possibleGUID, [System.Management.Automation.PSReference]$result) ) {
                    $BaseFolders.Add($_.FullName.ToLower())
                }
            }
 
 
I understand that the OICE* folder must already exists to be added in the exclusion list. But, AFAIK, that kind of folder could be created after, during Exchange “life”.
So I think a generic exclusion should be used instead, such as:
%SystemRoot%\Temp\OICE_????????-????-????-????-????????????.0

As stated here :
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-extension-file-exclusions-microsoft-defender-antivirus?view=o365-worldwide#use-wildcards-in-the-file-name-and-folder-path-or-extension-exclusion-lists

An asterisk “*” in a folder exclusion will stand in place for a single folder

So, cannot be used like OICE_*. 

But:
The “?” replaces a single character in a folder name.

**Comment by lusassl-msft** [comment]
@iserrano76 can you have a look at this one?

**Comment by lusassl-msft** [comment]
@iserrano76 I’ve assigned this one to you

**Comment by dpaulson45** [comment]
> @iserrano76 I’ve assigned this one to you

If this isn't already included in the current PR, DO NOT add it. Make it a different PR. We are already doing a lot with that PR.

**Comment by lusassl-msft** [comment]
Yup should be a new one if we decide to add but let’s focus on the current ones first

**Comment by iserrano76** [comment]
sure, I have many things right now, I will start with AMSI, following the process exclusions and I will continue with this one.
