### ISSUE TITLE
[Issue] - Health Checker - -OutputFilePath not honored for -BuildHtmlServersReport

### ISSUE THREAD

**Issue by JeremyTBradshaw** [microsoft/CSS-Exchange#1717]
**Provide Version Number**
Version 23.05.08.1516

**[DO-OVER] Describe the issue**
When supplying -BuildHtmlServersReport and -OutputFilePath, -OutputFilePath is not honored, instead current directory is where it lands.  This seems to be due to `Out-File` on line 7835 (as of this version).

**Describe the issue**
When I supply -OutputFilePath, the destination that I supply is only honored for certain outputs.  For example, the server TXT and XML files land where I want, but the Debug file, as well as the script updater log, both land in the script calling user's $PWD.  When I try to figure out what's going on in the code, it looks like this should be handled by the function Invoke-SetOutputInstanceLocation, which seems to be called in all the right places.  But it's clearly not working.  The thing that that is most pressing is that the HTML report is landing somewhere other than what is specified in -OutputFilePath (lands in System32 when I use Scheduled Tasks).

**Expected behavior**
I expect that all of the script's output files would land in the specified OutputFilePath.

**Script Output**
N/A, I'm not getting errors and the script is up to date.

**Additional context**
N/A

**Comment by JeremyTBradshaw** [comment]
I found the issue for the HTML report.  It is this line (line 7835 as of the current date/version):

```PowerShell
$htmlReport | Out-File $HtmlReportFile -Encoding UTF8
```

$HtmlReportFile is one of the main script's parameters, with default value of "ExchangeAllServersReport.html".  Out-File every else in the script is given the path of $Script:OutputFilePath, minus one other place where I think I can also spot why the debug log also doesn't honor -OutputFilePath...

Function Write-LoggerInstance uses `Out-File $LoggerInstance.FullPath`, and `$LoggerInstance` comes from the function Get-NewLoggerInstance, which uses `Get-Location` to set its path.  So there you have it.  Both these things need to be updated with support for `$Script:OutputFilePath`.

**Comment by dpaulson45** [comment]
How are you testing/running the script so the debug log is showing up in the current directory? When I run it, the debug log is written to the value provided in `-OutputFilePath`.

**Comment by JeremyTBradshaw** [comment]
Hi @dpaulson45, Please excuse me.  I am moving too fast.  The issue is limited to just the HTML report.  The other things - my own sloppy testing. I was failing to supply -OutputFilePath when running with just -ScriptUpdateOnly.  This was happening immediately before the next 2 runs of the script where I'd first get the XMl's and then generate the HTML report.  So the initial (1st of 3 runs) update-only run was leading me to make some false assumptions.

Issue is only with -BuildHtmlServersReport, which sends the HTML report out to current directory, per my explanation about line 7835.

**Comment by dpaulson45** [comment]
@JeremyTBradshaw that was a mistake internally on running the release pipeline. I kicked off the release pipeline again. So an actual update of HC will occur here shortly.

**Comment by JeremyTBradshaw** [comment]
Amazing.  Thanks very much!
