### ISSUE TITLE
CompareExchangeHashes

### ISSUE THREAD

**Issue by tomtummetott** [microsoft/CSS-Exchange#173]
**Describe the issue**
Looks like I get an alert for every single file

**Expected behavior**

**Script Output**
Example:
```
VDir: [ Exchange Back End/Public ] PDir: [ D:\Exchange Server\V15\ClientAccess\owa ] FileName: [ microsoft.exchange.clients.owa2.client.commonstrings.localized.min.js ] FilePath: [ D:\Exchange Server\V15\ClientAccess\owa\prem\15.1.1531.3\scripts\bs-latn-ba\microsoft.exchange.clients.owa2.client.commonstrings.localized.min.js ] is extra or edited on this server
VDir: [ Exchange Back End/Public ] PDir: [ D:\Exchange Server\V15\ClientAccess\owa ] FileName: [ microsoft.exchange.clients.owa2.client.connectorstrings.localized.min.js ] FilePath: [ D:\Exchange Server\V15\ClientAccess\owa\prem\15.1.1531.3\scripts\bs-latn-ba\microsoft.exchange.clients.owa2.client.connectorstrings.localized.min.js ] is extra or edited on this server
VDir: [ Exchange Back End/Public ] PDir: [ D:\Exchange Server\V15\ClientAccess\owa ] FileName: [ microsoft.exchange.clients.owa2.client.coredeferredstrings.localized.min.js ] FilePath: [ D:\Exchange Server\V15\ClientAccess\owa\prem\15.1.1531.3\scripts\bs-latn-ba\microsoft.exchange.clients.owa2.client.coredeferredstrings.localized.min.js ] is extra or edited on this server
VDir: [ Exchange Back End/Public ] PDir: [ D:\Exchange Server\V15\ClientAccess\owa ] FileName: [ microsoft.exchange.clients.owa2.client.csearch.strings.localized.min.js ] FilePath: [ D:\Exchange Server\V15\ClientAccess\owa\prem\15.1.1531.3\scripts\bs-latn-ba\microsoft.exchange.clients.owa2.client.csearch.strings.localized.min.js ] is extra or edited on this server
VDir: [ Exchange Back End/Public ] PDir: [ D:\Exchange Server\V15\ClientAccess\owa ] FileName: [ microsoft.exchange.clients.owa2.client.extensibilitystrings.localized.min.js ] FilePath: [ D:\Exchange Server\V15\ClientAccess\owa\prem\15.1.1531.3\scripts\bs-latn-ba\microsoft.exchange.clients.owa2.client.extensibilitystrings.localized.min.js ] is extra or edited on this server
VDir: [ Exchange Back End/Public ] PDir: [ D:\Exchange Server\V15\ClientAccess\owa ] FileName: [ microsoft.exchange.clients.owa2.client.extstrings.localized.min.js ] FilePath: [ D:\Exchange Server\V15\ClientAccess\owa\prem\15.1.1531.3\scripts\bs-latn-ba\microsoft.exchange.clients.owa2.client.extstrings.localized.min.js ] is extra or edited on this server
VDir: [ Exchange Back End/Public ] PDir: [ D:\Exchange Server\V15\ClientAccess\owa ] FileName: [ microsoft.exchange.clients.owa2.client.filesstrings.localized.min.js ] FilePath: [ D:\Exchange Server\V15\ClientAccess\owa\prem\15.1.1531.3\scripts\bs-latn-ba\microsoft.exchange.clients.owa2.client.filesstrings.localized.min.js ] is extra or edited on this server
VDir: [ Exchange Back End/Public ] PDir: [ D:\Exchange Server\V15\ClientAccess\owa ] FileName: [ microsoft.exchange.clients.owa2.client.frameworkstrings.localized.min.js ] FilePath: [ D:\Exchange Server\V15\ClientAccess\owa\prem\15.1.1531.3\scripts\bs-latn-ba\microsoft.exchange.clients.owa2.client.frameworkstrings.localized.min.js ] is extra or edited on this server
VDir: [ Exchange Back End/Public ] PDir: [ D:\Exchange Server\V15\ClientAccess\owa ] FileName: [ microsoft.exchange.clients.owa2.client.ftstrings.localized.min.js ] FilePath: [ D:\Exchange Server\V15\ClientAccess\owa\prem\15.1.1531.3\scripts\bs-latn-ba\microsoft.exchange.clients.owa2.client.ftstrings.localized.min.js ] is extra or edited on this server
VDir: [ Exchange Back End/Public ] PDir: [ D:\Exchange Server\V15\ClientAccess\owa ] FileName: [ microsoft.exchange.clients.owa2.client.helppanelstrings.localized.min.js ] FilePath: [ D:\Exchange Server\V15\ClientAccess\owa\prem\15.1.1531.3\scripts\bs-latn-ba\microsoft.exchange.clients.owa2.client.helppanelstrings.localized.min.js ] is extra or edited on this server
```

I got approximately 494,000 hits and a result-file size of 330MB

If you need more info, let me know.

Thanks in advance,
Andre

**Comment by stef-sjz** [comment]
Having the same issue here,
My 15.1.2176.2_result.xml file size is 471Mo

**Comment by anshuldube** [comment]
We are looking a this issue. Andre: What is the exchange version or the result file name?

**Comment by jadit1** [comment]
Also having the same issue.
File name was: 15.0.1497.2_result

**Comment by NAV-Management** [comment]
On our side as well: 15.1.2176.2_result.xml with 156MB size and around 200.000 lines.
PS: It's a german (de-de) 2012 R2 Server, don't know if this could be a problem.

**Comment by stetze88** [comment]
I have the Same Problem on an German Exchange 2019 CU 8.

**Comment by corsch** [comment]
I have the same issue with a German Exchange Server 15.0.1497.2

**Comment by anshuldube** [comment]
> Having the same issue here,
> My 15.1.2176.2_result.xml file size is 471Mo

Could you please re-run with the latest CompareExchangeHashes.ps1 from https://github.com/microsoft/CSS-Exchange/releases/latest? It seems like an older version of the script was used here since the result file is an xml. The new version of the script generates a csv file.
Thanks,
Anshul

**Comment by tomtummetott** [comment]
Readme pointed to an older version of the script. Issue seems to be resolved with current version.

**Comment by NAV-Management** [comment]
with CompareExchangeHashes.ps1 in v21.03.09.0338 I got a useful csv-file and result was OK as well.

**Comment by anshuldube** [comment]
Would you be able to share a part of the result that shows the error?
We believe it could be due to localized files.

**Comment by taleteller** [comment]
@anshuldube Sure ...
```
"NoHashMatch","Exchange Back End/owa/","uglobal.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\15.0.1497.10\scripts\premium\uglobal.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa"
"NoHashMatch","Exchange Back End/owa/","uglobal.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\15.0.1497.12\scripts\premium\uglobal.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa"
"NoHashMatch","Exchange Back End/owa/","uglobal.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\15.0.1497.7\scripts\premium\uglobal.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa"
"NoHashMatch","Exchange Back End/owa/","uglobal.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\15.0.1497.8\scripts\premium\uglobal.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa"
"NoHashMatch","Exchange Back End/owa/","Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\15.0.516.30\Owa2\ext\def\am-et\Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa"
"NoHashMatch","Exchange Back End/owa/","Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\15.0.516.30\Owa2\ext\def\ar\Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa"
"NoHashMatch","Exchange Back End/owa/","Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\15.0.516.30\Owa2\ext\def\bg\Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa"
"NoHashMatch","Exchange Back End/owa/","Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\15.0.516.30\Owa2\ext\def\bn-in\Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa"
"NoHashMatch","Exchange Back End/owa/","Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\15.0.516.30\Owa2\ext\def\ca\Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa"
"NoHashMatch","Exchange Back End/owa/","Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\15.0.516.30\Owa2\ext\def\cs\Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa"
...
"NoHashMatch","Exchange Back End/owa/","boot.anonymous.mouse.strings.localized.min.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\Current2\version\scripts\el\boot.anonymous.mouse.strings.localized.min.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa"
"NoHashMatch","Exchange Back End/owa/","boot.dogfood.mouse.strings.localized.min.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\Current2\version\scripts\el\boot.dogfood.mouse.strings.localized.min.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa"
"NoHashMatch","Exchange Back End/owa/","boot.mouse.strings.localized.min.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\Current2\version\scripts\el\boot.mouse.strings.localized.min.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa"
...
"NoHashMatch","Exchange Back End/Exchange","Microsoft.Exchange.Clients.Owa2.Client.Weather.Strings.localized.min.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\prem\15.0.847.32\scripts\zh-hans\Microsoft.Exchange.Clients.Owa2.Client.Weather.Strings.localized.min.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa"
"NoHashMatch","Exchange Back End/Exchange","Microsoft.Exchange.Clients.Owa2.Client.Attach.FP.Strings.localized.min.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\prem\15.0.847.32\scripts\zh-hant\Microsoft.Exchange.Clients.Owa2.Client.Attach.FP.Strings.localized.min.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa"

```
The first four lines are a bit different, everything else end on `.Localized.js` or `.localized.min.js`. As said previously this is runs a German Version 15.0.1497.2. I got a few other versions, but their scripts still running.

**Comment by anshuldube** [comment]
> @anshuldube Sure ...
> 
> ```
> "NoHashMatch","Exchange Back End/owa/","uglobal.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\15.0.1497.10\scripts\premium\uglobal.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa"
> "NoHashMatch","Exchange Back End/owa/","uglobal.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\15.0.1497.12\scripts\premium\uglobal.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa"
> "NoHashMatch","Exchange Back End/owa/","uglobal.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\15.0.1497.7\scripts\premium\uglobal.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa"
> "NoHashMatch","Exchange Back End/owa/","uglobal.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\15.0.1497.8\scripts\premium\uglobal.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa"
> "NoHashMatch","Exchange Back End/owa/","Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\15.0.516.30\Owa2\ext\def\am-et\Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa"
> "NoHashMatch","Exchange Back End/owa/","Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\15.0.516.30\Owa2\ext\def\ar\Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa"
> "NoHashMatch","Exchange Back End/owa/","Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\15.0.516.30\Owa2\ext\def\bg\Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa"
> "NoHashMatch","Exchange Back End/owa/","Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\15.0.516.30\Owa2\ext\def\bn-in\Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa"
> "NoHashMatch","Exchange Back End/owa/","Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\15.0.516.30\Owa2\ext\def\ca\Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa"
> "NoHashMatch","Exchange Back End/owa/","Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\15.0.516.30\Owa2\ext\def\cs\Microsoft.Exchange.Clients.Owa2.Client.ExtensionStrings.Localized.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa"
> ...
> "NoHashMatch","Exchange Back End/owa/","boot.anonymous.mouse.strings.localized.min.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\Current2\version\scripts\el\boot.anonymous.mouse.strings.localized.min.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa"
> "NoHashMatch","Exchange Back End/owa/","boot.dogfood.mouse.strings.localized.min.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\Current2\version\scripts\el\boot.dogfood.mouse.strings.localized.min.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa"
> "NoHashMatch","Exchange Back End/owa/","boot.mouse.strings.localized.min.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\Current2\version\scripts\el\boot.mouse.strings.localized.min.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa"
> ...
> "NoHashMatch","Exchange Back End/Exchange","Microsoft.Exchange.Clients.Owa2.Client.Weather.Strings.localized.min.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\prem\15.0.847.32\scripts\zh-hans\Microsoft.Exchange.Clients.Owa2.Client.Weather.Strings.localized.min.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa"
> "NoHashMatch","Exchange Back End/Exchange","Microsoft.Exchange.Clients.Owa2.Client.Attach.FP.Strings.localized.min.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\prem\15.0.847.32\scripts\zh-hant\Microsoft.Exchange.Clients.Owa2.Client.Attach.FP.Strings.localized.min.js","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa"
> ```
> 
> The first four lines are a bit different, everything else end on `.Localized.js` or `.localized.min.js`. As said previously this is runs a German Version 15.0.1497.2. I got a few other versions, but their scripts still running.

Seems like we are missing baselines for:
15.0.1497.10
15.0.1497.12
15.0.516.30
15.0.847.32
versions, we are working on getting these fixed.
Could you also help us with getting a sample file hash: 
Get-FileHash -Path "C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\Current2\version\scripts\el\boot.anonymous.mouse.strings.localized.min.js"

**Comment by taleteller** [comment]
@anshuldube That would be 
```
Algorithm       Hash                                                                   Path                                                                                                                                                                      
---------       ----                                                                   ----                                                                                                                                                                      
SHA256          5BCAF3D957CCB824254823D1A463F6C86886236AA16816F9BD3764E742825891       C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\Current2\version\scripts\el\boot.anonymous.mouse.strings.localized.min.js                                 
```

**Comment by anshuldube** [comment]
Can you please download the latest version of the script from: https://github.com/microsoft/CSS-Exchange/releases/latest/download/CompareExchangeHashes.ps1 and re-run.

**Comment by taleteller** [comment]
Aborts with `LoadFromGitHub : C:\Users\Administrator.PROMO10\baseline_15.0.516.30.zip not found...`

**Comment by anshuldube** [comment]
> Aborts with `LoadFromGitHub : C:\Users\Administrator.PROMO10\baseline_15.0.516.30.zip not found...`

This issue is tracked with: https://github.com/microsoft/CSS-Exchange/issues/222

**Comment by anshuldube** [comment]
duplicate.
