### ISSUE TITLE
[Issue] Latest release version for the ExPerfAnalyzer generates "The '<' operator is reserved for future use" exception

### ISSUE THREAD

**Issue by gabymuntean** [microsoft/CSS-Exchange#1731]
**Describe the issue**
Provide the version of the script that has the issue.
https://github.com/microsoft/CSS-Exchange/releases/latest/download/ExPerfAnalyzer.ps1

**Expected behavior**
A clear and concise description of what the issue is, including the script name.
I got the following error when running it from the above location (59KB in size), in PS 7.0
ExPerfAnalyzer.ps1:257
Line |
 257 |          ></command-palette-mode>
     |           ~
     | The '<' operator is reserved for future use.

Running the script from this location: blob:https://github.com/896f3f27-3001-425e-b788-7c2b5a90ec45 (42KB in size), by clicking raw file under https://github.com/microsoft/CSS-Exchange/blob/main/Performance/ExPerfAnalyzer.ps1, didn't generate any issue.

**Script Output**
If applicable, add the exception that wasn't handled.
It is strange, that after running successfully the script in raw format, then I could run the latest release version (https://github.com/microsoft/CSS-Exchange/releases/latest/download/ExPerfAnalyzer.ps1), but if I analyzed a .BLG file, I got multiple exceptions, as the ones below, but in the end the .BLG file got processed.

D:\Daily_Performance_Logs\ExPerfAnalyzerLatest.ps1:714
Line |
 714 |          $obj.CounterName = ($FullCounterSamplePath.Substring($FullCou …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
InvalidOperation: D:\Daily_Performance_Logs\ExPerfAnalyzerLatest.ps1:715
Line |
 715 |          if (($FullCounterSamplePath.Contains("(")) -and
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
SetValueInvocationException: D:\Daily_Performance_Logs\ExPerfAnalyzerLatest.ps1:836
Line |
 836 |          $svrData.StartTime = ($svr.Group[0].RawData | Sort-Object Tim …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception setting "StartTime": "Cannot convert null to type "System.DateTime"."
SetValueInvocationException: D:\Daily_Performance_Logs\ExPerfAnalyzerLatest.ps1:837
Line |
 837 |          $svrData.EndTime = ($svr.Group[0].RawData | Sort-Object TimeS …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception setting "EndTime": "Cannot convert null to type "System.DateTime"."

**Additional context**
Running the raw version against a .BLG file didn't generate any error.

I also compared the raw file, with the latest release version and could find only the license and version information at the comments before the script code begins and the script signature at the end.

**Comment by gabymuntean** [comment]
It seems this behavior appear if PS 7 is used; when using Windows Powershell 5.1 the issue isn't there.

**Comment by lusassl-msft** [comment]
I don’t think that the script has been tested to run with PS Core. @dpaulson45 we could add a check to prevent the script running with PS Core until we support it.
