### ISSUE TITLE
[Work Item] - HSTS check for HealthChecker

### ISSUE THREAD

**Issue by johage** [microsoft/CSS-Exchange#1748]
**Describe the work**
We're seeing more customers enable HSTS when this isn't officially supported by Exchange - https://learn.microsoft.com/en-us/iis/get-started/whats-new-in-iis-10-version-1709/iis-10-version-1709-hsts

**Additional Context**
We can check this and advise it be disabled for each Site like so:
**(Get-IISSite -Name "Default Web Site").HSTS
(Get-IISSite -Name "Exchange Back End").HSTS**

**Comment by dpaulson45** [comment]
We currently collect this information already within Health Checker (Get-IISWebSite.ps1). 

![image](https://github.com/microsoft/CSS-Exchange/assets/22776718/8d1ee093-a846-4d9a-b14c-567488df59dc)

We just need to know what we want to display. Do we just want to know if this is enabled? Configured a particular way?

**Comment by johage** [comment]
***@***.***

Thanks,

Josh Hagen
Exchange Technical Advisor
Tier 3 Business hours: 8:00AM-8:00PM Central
Microsoft Exchange
701.492.6842
Working hours: Monday-Friday 7:00-4:00PM Central

I am committed to providing excellent service and I value your feedback. I welcome comments about what I did right, as well as suggestions for how I can continue to improve my service in the future. Microsoft is committed to providing world-class service, so your input regarding the entire support process is highly valued. Please send your comments to me or my manager Travis Hedrick ***@***.******@***.***>)

Exchange 2013 has reached End of Life as of April 11, 2023. If you want to see more information on this click here - https://docs.microsoft.com/en-us/microsoft-365/enterprise/exchange-2013-end-of-support?view=o365-worldwide#what-does-end-of-support-mean

Exchange 2010 has reached End of Life as of October 13, 2020 please review this link if you have questions about this - https://docs.microsoft.com/en-us/microsoft-365/enterprise/exchange-2010-end-of-support?view=o365-worldwide

**Comment by johage** [comment]
Confirmed with testing that enabling HSTS itself doesn't break EMS but configuring the HTTPS -> HTTP redirect will break this, for obvious reasons:
enabled             : False
redirectHttpToHttps : True

So I'd say a callout if it's Enabled, and then a LARGER callout that redirecting HTTP traffic to HTTPS will absolutely break EMS functionality.

**Comment by worldsdream** [comment]
So configuring HSTS on Exchange Server like the below link explains is how it should be, right?

https://www.alitajran.com/hsts-exchange-server/

**Comment by lusassl-msft** [comment]
@worldsdream HSTS was not officially tested on Exchange Server yet and should therefore be considered as unsupported.
