### ISSUE TITLE
[Work Item] Improve RBA-Summary by checking WorkSpaces as well. 

### ISSUE THREAD

**Issue by Shanefe** [microsoft/CSS-Exchange#1774]
**Describe the work**
Extend existing script to analyze Workspaces as well as Rooms. 

**Additional Context**

Should be done by Shanefe

**Comment by dpaulson45** [comment]
@Shanefe did this get completed in the PR #1767 ?

**Comment by dpaulson45** [comment]
@Shanefe did this work item get completed?

**Comment by Shanefe** [comment]
Yes, it can be closed, etc.

________________________________
