### ISSUE TITLE
[Issue] Running CompareExchangeHashes.ps1 gives error : baseline_ 15.1.2106.2.zip not found... please open issue on https://github.com/microsoft/CSS-Exchange/issues, we will work on it

### ISSUE THREAD

**Issue by elmar2021** [microsoft/CSS-Exchange#178]
**Describe the issue**
A clear and concise description of what the issue is, including what script you are seeing the error in.

**Expected behavior**

**Script Output**
If applicable, add the exception that you are seeing that wasn't handled.

**Additional context**

**Comment by anshuldube** [comment]
Can you please download the latest version of the script from: https://github.com/microsoft/CSS-Exchange/releases/latest/download/CompareExchangeHashes.ps1 and re-run.

**Comment by anshuldube** [comment]
This should be fixed now.
