### ISSUE TITLE
[Issue] - Health Checker uses wrong quotes in HC Get-HealthCheckerData function

### ISSUE THREAD

**Issue by levi-rogers** [microsoft/CSS-Exchange#1788]
**Provide Version Number**
Provide the version of the script that has the issue.
23.07.20.2143

**Describe the issue**
A clear and concise description of the issue.
Bad characters lines 13467,13468 - the quotes are not the "right" kind of quotes.  

**Expected behavior**

**Script Output**
If applicable, add the exception that wasn't handled.
PS C:\Scripts\Tools> .\HealthChecker.ps1
At C:\Scripts\Tools\HealthChecker.ps1:13468 char:29
+             $reg.OpenSubKey(â€œSOFTWARE\Microsoft\Windows NT\CurrentV ...
+                             ~
Missing ')' in method call.
At C:\Scripts\Tools\HealthChecker.ps1:13468 char:29
+             $reg.OpenSubKey(â€œSOFTWARE\Microsoft\Windows NT\CurrentV ...
+                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token 'â€œSOFTWARE\Microsoft\Windows' in expression or statement.
At C:\Scripts\Tools\HealthChecker.ps1:13457 char:13
+         try {
+             ~
Missing closing '}' in statement block or type definition.
At C:\Scripts\Tools\HealthChecker.ps1:13468 char:79
+ ... OpenSubKey(â€œSOFTWARE\Microsoft\Windows NT\CurrentVersionâ€^C

**Additional context**

**Comment by levi-rogers** [comment]
That is where I downloaded it from.  Can I attach an updated fixed section here?

**Comment by levi-rogers** [comment]
``            $reg = [Microsoft.Win32.RegistryKey]::OpenRemoteBaseKey("LocalMachine", $ComputerName)
            $reg.OpenSubKey("SOFTWARE\Microsoft\Windows NT\CurrentVersion") | Out-Null

In the current version those quotes were not the right ascii character - someone was probably using a web editor when they copy pasted.

**Comment by levi-rogers** [comment]
Yep that was the one - let me know when the update has been committed and I will retest for you from the download link.

**Comment by lusassl-msft** [comment]
We will do. Thanks for reporting this issue!
