### ISSUE TITLE
[Issue] Get-AgeInDays fails on non-English locales?

### ISSUE THREAD

**Issue by abochmann** [microsoft/CSS-Exchange#179]
**Describe the issue**
We have a couple of systems where the LogAgeDays.csv contains empty values only. The log files exist though, and are accessible when running the (Get-ChildItem ...).CreationTime - call manually. No error is reported by the script

Our current suspicion is that this happens when the Exchange host system is a Windows with a locale other than English. 

**Expected behavior**
The log age reporting works regardless of system locale.

**Script Output**
Example empty csv:
```
#TYPE System.Management.Automation.PSCustomObject
"Oabgen","Ecp","AutodProxy","EasProxy","EcpProxy","EwsProxy","MapiProxy","OabProxy","OwaProxy","OwaCalendarProxy","PowershellProxy","RpcHttpProxy"
"","","","","","","","","","","",""
```

**Comment by bill-long** [comment]
Hrm, I changed my regional settings but it seems to be fine with commas:

![image](https://user-images.githubusercontent.com/4518572/110493725-834afe80-80b8-11eb-88c0-0444d7b01a92.png)

It's even perfectly happy to return decimals for some servers and commas for others, depending on the regional settings of the target server:

![image](https://user-images.githubusercontent.com/4518572/110493829-98c02880-80b8-11eb-9609-6cc5f815aeb7.png)

**Comment by abochmann** [comment]
Hrm.

In our testing, we removed the Get-AgeInDays subroutine and then got the actual date in the output. We'll try some more to get this tracked down.

**Comment by 2d4d** [comment]
we got negative numbers from one machine:

#TYPE System.Management.Automation.PSCustomObject
"Oabgen","Ecp","AutodProxy","EasProxy","EcpProxy","EwsProxy","MapiProxy","OabProxy","OwaProxy","OwaCalendarProxy","PowershellProxy","RpcHttpProxy"
"-55,5","-55,2","-55,4","-55,4","-55,4","-55,4","-55,4","-55,4","-55,4","-55,4","-55,4","-55,4"

**Comment by abochmann** [comment]
I tried the version from #183 and now get correct output 👍

```
#TYPE System.Management.Automation.PSCustomObject
"Oabgen","Ecp","AutodProxy","EasProxy","EcpProxy","EwsProxy","MapiProxy","OabProxy","OwaProxy","OwaCalendarProxy","PowershellProxy","RpcHttpProxy"
"10,6","11,8","10,8","10,8","10,8","10,8","10,9","10,8","10,8","10,9","10,9","10,8"
```

(Short times due to log rotation...)
