### ISSUE TITLE
[Issue] - Health Checker - AES256-CBC Protected Content Support doesn't work remotely

### ISSUE THREAD

**Issue by PrayingMoses** [microsoft/CSS-Exchange#1799]
**Provide Version Number**
23.08.08.2112

**Describe the issue**
If a remote MSX Server is being queried (e.g. .\HealthChecker.ps1 -Server <Servername>)  it shows:

AES256-CBC Protected Content Support: True
This build supports AES256-CBC protected content, but the configuration is not complete. Exchange Server is not able to decrypt protected messages which could impact eDiscovery and Journaling tasks. If you use Rights Management Service (RMS) on-premises, please follow the instructions as outlined in the documentation: https://aka.ms/ExchangeCBCKB
(yellow)

if executed locally on the same system queried remote before:
*AES256-CBC Protected Content Support: True* (green)

**Expected behavior**
Clear and consistent report about the correct enabling of the "AES256-CBC Protected Content Support", regardless if healthchecker was executed locally or a remote system was checked.

**Script Output**
n/a

**Additional context**
n/a

**Comment by dpaulson45** [comment]
Problem code is here:

https://github.com/microsoft/CSS-Exchange/blob/ab051365806660f9f64ed1a624b9506c5b601dde/Diagnostics/HealthChecker/DataCollection/ExchangeInformation/Get-ExchangeAES256CBCDetails.ps1#L41

inside of a remote script block, we are trying to use a variable. Works locally because we don't execute the local instance in a remote script block. 

```
AES256-CBC encryption for information protection is supported by this Exchange Server build
Calling: Invoke-ScriptBlockHandler
Running Invoke-Command without argument list
Failed to run Invoke-ScriptBlockHandler - 
Calling: 
Error Excluded Count: 10
Error Count: 10
Error Origin Info: VNext-E19A.VNext.local
Test-Path : Cannot bind argument to parameter 'Path' because it is null.
Inner Exception: System.Management.Automation.RemoteException: Cannot bind argument to parameter 'Path' because it is null.
Position Message: At C:\Users\Han\Desktop\HealthChecker.ps1:513 char:17
+                 $returnValue = Invoke-Command @params
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Remote Position Message: At line:1 char:18
+  Test-Path -Path $regPathToCheck
+                  ~~~~~~~~~~~~~~~
Script Stack: at <ScriptBlock>, <No file>: line 1
Exiting: Invoke-ScriptBlockHandler
Calling: Invoke-ScriptBlockHandler
Running Invoke-Command without argument list
Failed to run Invoke-ScriptBlockHandler - 
```

**Comment by PrayingMoses** [comment]
@dpaulson45 thank you very much, for the fix and for the Health Checker!
