### ISSUE TITLE
[Issue] http-vuln-cve2021-26855.nse string.match expected string, got nil

### ISSUE THREAD

**Issue by Schorsch1705** [microsoft/CSS-Exchange#180]
Hi,

for me the NMAP Script throws an error at string.match.
Error is: string expected, got nil

Any idea?

Thanks

**Comment by justinhendricksmsft** [comment]
This is fixed in PR #203

**Comment by Schorsch1705** [comment]
Great, now it works. Thanks.
I can add the information, that this happened with the URL Rewrite active as interim mitigation. But now it doesn't even matter.
