### ISSUE TITLE
[Issue] - ExchangeExtendedProtectionManagement.ps1 - "This script requires to be run inside of Exchange Management Shell"

### ISSUE THREAD

**Issue by Julien-nl** [microsoft/CSS-Exchange#1808]
Describe the issue
Version 23.08.10.1807 (latest at time of writing) of the ExchangeExtendedProtectionManagement.ps1 script

When running .\ExchangeExtendedProtectionManagement.ps1 I get a warning saying that the script needs to be run in Exchange Management Shell, despite the fact that that's where I'm running it.

None of the switches change this

Exchange Augustus 2023 15.02.1258.023 Latest CU and SU

Expected behavior
The script should be able to run

Script Output
The Debug.txt file generated

[[PS] C:\Users\SERV\Downloads>.\ExchangeExtendedProtectionManagement.ps1
Version 23.08.10.1807
WARNING: This script requires to be run inside of Exchange Management Shell. Please run on an Exchange Management Server or an Exchange Server with Exchange Management Shell.
Do you have feedback regarding the script? Please email ExToolsFeedback@microsoft.com.
[PS] C:\Users\SERV\Downloads>Get-ExchangeCertificate

Thumbprint                                Services   Subject
----------                                --------   -------

[PS] C:\Users\SERV\Downloads>Get-ExchangeDiagnosticInfo -Process Microsoft.Exchange.Directory.TopologyService -Component VariantConfiguration -Argument Refresh

RunspaceId  : 94980a54-0780-4f32-ae30-63ba61b11850
Result      : <Diagnostics>
                <ProcessInfo>
                  <id>6060</id>
                  <serverName>EX02</serverName>
                  <startTime>2023-08-11T12:45:26.6388638Z</startTime>
                  <currentTime>2023-08-11T14:15:05.2892953Z</currentTime>
                  <lifetime>01:29:38.6504315</lifetime>
                  <threadCount>15</threadCount>
                  <handleCount>1534</handleCount>
                  <workingSet>136.7 MB (143,310,848 bytes)</workingSet>
                  <fastTrainExchangeVersion>15.2.1258.23</fastTrainExchangeVersion>
                </ProcessInfo>
                <Components>
                  <VariantConfiguration>
                    <Overrides Updated="2023-08-11T14:15:05.305299Z">
                      <SettingOverride>
                        <Name>EnableSigningVerification</Name>
                        <Reason>Enabling Signing Verification</Reason>
                        <ModifiedBy>SERV.local/Users/SERV B.V.</ModifiedBy>
                        <ComponentName>Data</ComponentName>
                        <SectionName>EnableSerializationDataSigning</SectionName>
                        <Status>Accepted</Status>
                        <Message>This override synced to the server but whether it applies to the services running on this server depends on the override parameters, current configuration and the context.</Message>
                        <Parameters>
                          <Parameter>Enabled=true</Parameter>
                        </Parameters>
                      </SettingOverride>
                    </Overrides>
                  </VariantConfiguration>
                </Components>
              </Diagnostics>
Identity    :
IsValid     : True
ObjectState : New

**Comment by dpaulson45** [comment]
@Julien-nl please provide the correct debug output.

your log states it is from Feb 17th.

**Comment by Julien-nl** [comment]
@dpaulson45 
i apologies it was a mistake between copy and past
i have updated the error.

**Comment by dpaulson45** [comment]
> @dpaulson45 i apologies it was a mistake between copy and past i have updated the error.

@Julien-nl please provide the information in the debug log output. Not the screen output.

**Comment by Julien-nl** [comment]
@dpaulson45 i noticed the Microsoft Exchange Server Auth Certificate was expired, after renewing it and waited 30 min stuff start working.
i am able to run the script.
i apologies for the false alarm
