### ISSUE TITLE
[Issue] CompareExchangeHashes.ps1 does not count Exchange version 15.1.1913.7 that is missing from baseline

### ISSUE THREAD

**Issue by NicBot79** [microsoft/CSS-Exchange#181]
CompareExchangeHashes.ps1 doesn't download baseline for Exchange security fix 15.1.1913.7.

https://support.microsoft.com/en-us/topic/description-of-the-security-update-for-microsoft-exchange-server-2019-and-2016-february-11-2020-94ac1ebb-fb8a-b536-9240-a1cab0fd1c9f

**Comment by anshuldube** [comment]
We are preparing baseline for this version.

**Comment by anshuldube** [comment]
Can you please take the latest version of the script from https://github.com/microsoft/CSS-Exchange/releases/latest/download/CompareExchangeHashes.ps1 and try again?

**Comment by anshuldube** [comment]
This should be fixed now.
