### ISSUE TITLE
[Issue] baseline_15.1.2106.2.checksum.txt not found...

### ISSUE THREAD

**Issue by altani** [microsoft/CSS-Exchange#185]
**Describe the issue**
The checskum is downlod from release (.zip also)
Checksum is present on the folder when script searching files but can't find the checksum file to load it.

**Comment by anshuldube** [comment]
Can you please download the latest version of the script from: https://github.com/microsoft/CSS-Exchange/releases/latest/download/CompareExchangeHashes.ps1 and re-run.

**Comment by altani** [comment]
Thanks, the script works
