### ISSUE TITLE
[Issue] CrossTenantMailboxMigrationValidation.ps1 Saying no to remove proxy addresses not part of the target organization still says all proxies are ok

### ISSUE THREAD

**Issue by GuyGroeneveld** [microsoft/CSS-Exchange#1863]
**Describe the issue**
Version 23.08.31.0940

**Expected behavior**
If we say no to remove the proxy addresses relating to unknown domain, we should not have the green line telling us that the target mailuser proxyaddresses are all part of are all ok

**Script Output**
If applicable, add the exception that wasn't handled.

**Additional context**
We don't handle the case when we don't say yes here:

Write-Host ">> Error: LegacyExchangeDN not found as an X500 ProxyAddress on Target Object. LegacyExchangeDN expected on target object: $($SourceObject.LegacyExchangeDN)" -ForegroundColor Red
                    if (!$TargetObject.IsDirSynced) {
                        $LegDNAddOption = Read-Host "Would you like to add it? (Y/N)"
                        Write-Host " Your input: $($LegDNAddOption)"
                        if ($LegDNAddOption.ToLower() -eq "y") {
                            Write-Verbose -Message "Informational: Adding LegacyExchangeDN as a proxyAddress on TARGET object"
                            Set-TargetMailUser $TargetIdentity -EmailAddresses @{Add = "X500:" + $SourceObject.LegacyExchangeDN }
                            #Reload TARGET object into variable as it has been changed
                            $TargetObject = Get-TargetMailUser $TargetIdentity
                        }
                    } else {
                        Write-Host ">> Error: The object is DirSynced and this is not a change that can be done directly on EXO. Please do the change on-premises and perform an AADConnect delta sync" -ForegroundColor Red
                    }

**Comment by guruxp** [comment]
Discussed with Guy and the previous code is not where the issue relies, but this one:

                Write-Verbose -Message "Informational: Checking for EmailAddresses on TARGET object that are not on the TARGET accepted domains list"
                foreach ($Address in $TargetObject.EmailAddresses) {
                    if ($Address.StartsWith("SMTP:") -or $Address.StartsWith("smtp:")) {
                        if ($TargetTenantAcceptedDomains.DomainName -notcontains $Address.Split("@")[1]) {
                            if (!$TargetObject.IsDirSynced) {
                                Write-Host ">> Error:"$Address" is not part of your organization, would you like to remove it? (Y/N): " -ForegroundColor Red -NoNewline
                                $RemoveAddressOption = Read-Host
                                Write-Host " Your input: "$RemoveAddressOption
                                if ($RemoveAddressOption.ToLower() -eq "y") {
                                    Write-Host "Informational: Removing the EmailAddress"$Address" from the TARGET object"
                                    Set-TargetMailUser $TargetIdentity -EmailAddresses @{Remove = $Address }
                                    #Reload TARGET object into variable as it has been changed
                                    $TargetObject = Get-TargetMailUser $TargetIdentity
                                }
                            } else {
                                Write-Host ">> Error:"$Address" is not part of your organization. The object is DirSynced and this is not a change that can be done directly on EXO. Please do remove the address from on-premises and perform an AADConnect delta sync" -ForegroundColor Red
                            }
                        }
                    } else {
                        Write-Host ">> Target MailUser ProxyAddresses are all part of the target organization" -ForegroundColor Green
                    }
                }

I'll do the change during the day.

**Comment by guruxp** [comment]
@dpaulson45, injected https://github.com/microsoft/CSS-Exchange/pull/1873 and ready for review. Minor changes took place
