### ISSUE TITLE
[Issue] - Health Checker shows wrong CU?

### ISSUE THREAD

**Issue by Pacman1988** [microsoft/CSS-Exchange#1866]
**Provide Version Number**
Exchange Health Checker version 23.04.04.1055

**Describe the issue**
Version shows wrong old CU? Should be CU13 with this build number?
Version: ***Exchange 2019 CU12***
    Build Number: 15.02.1258.025
        Exchange IU or Security Hotfix Detected:
                Security Update for ***Exchange Server 2019 Cumulative Update 13*** (KB5026261)

**Expected behavior**
Should show CU13 on version, because build number matches 15.02.1258.025?
<html>
<body>

Exchange Server 2019 CU13 Aug23SUv2 | August 15, 2023 | 15.2.1258.25 | 15.02.1258.025
-- | -- | -- | --

</body>
</html>

https://learn.microsoft.com/en-us/exchange/new-features/build-numbers-and-release-dates?view=exchserver-2019

**Script Output**
Exchange Information
--------------------
        Name: server
        Generation Time: 10/27/2023 09:00:03
        Version: Exchange 2019 CU12
        Build Number: 15.02.1258.025
        Exchange IU or Security Hotfix Detected:
                Security Update for Exchange Server 2019 Cumulative Update 13 (KB5026261)
                Security Update for Exchange Server 2019 Cumulative Update 13 (KB5030524)

**Comment by lusassl-msft** [comment]
@Pacman1988 we had an issue with the auto-update function in the version that you use. Please download the latest version of the script manually.

More details about the issue can be found here: https://techcommunity.microsoft.com/t5/exchange-team-blog/issue-with-css-exchange-script-update-function-caused-automatic/ba-p/3803772
