### ISSUE TITLE
[Work Item] HealthChecker, Add a check for Exchange Trusted Subsystem being a member of machine local administrators group

### ISSUE THREAD

**Issue by peschmi-msft** [microsoft/CSS-Exchange#1886]
**Describe the work**
If the Exchange Trusted Subsystem is not member of the local administrators group of the machine, this will break authorization between Exchange Servers like in reseeding the Content Index (2016) and likely causing other side effects which remain undetected. 
It seems like the local Administrator Group is often managed by the AD Team through Group Policy Management which overrides the
post-setup group members and can lead to missing the Exchange Trusted Subsystem as a member.

**Additional Context**
A check could probably be implemented like this:

`$rootDSE = [ADSI]("LDAP://$([System.DirectoryServices.ActiveDirectory.Domain]::GetComputerDomain().Name)/RootDSE")
$exchangeTrustedSubsystemDN = ("CN=Exchange Trusted Subsystem,OU=Microsoft Exchange Security Groups," + 
$rootDSE.rootDomainNamingContext)
$TrustedSubsystemSID=(Get-ADGroup $exchangeTrustedSubsystemDN).SID.Value
$LocalAdminsgGroupSID="S-1-5-32-544" #well-known-SID

if ((Get-LocalGroupMember -SID $LocalAdminsgGroupSID | ? {$_.SID -eq $TrustedSubsystemSID}).count -ne 1)
  {Write-Warning "Exchange Trusted Subsystem is not a member of the Local Administrator Group"}`

**Comment by dpaulson45** [comment]
What other permissions/group membership should we be checking for here for the Exchange Server?

**Comment by Sureshbd** [comment]
Exchange server is part of the following groups.
Get-ADPrincipalGroupMembership (Get-ADComputer n2).DistinguishedName |ft name

name
----
Domain Computers
Exchange Servers
Exchange Trusted Subsystem
Managed Availability Servers
Exchange Install Domain Servers
