### ISSUE TITLE
[Issue] - Health Checker stuck in loop when processing IIS information

### ISSUE THREAD

**Issue by sriccio** [microsoft/CSS-Exchange#1915]
**Provide Version Number**
23.12.18.2042

**Describe the issue**
The scripts hangs indefinitely on "Analyzing data"

**Expected behavior**
Sript finishing and returning results

**Script Output**
A tail on the debug file shows that it loops indefinitely on the following lines, until the script is interrupted (ctrl-c)

```
Working on currentKey: Default Web Site/aspnet_client
authLocation was NULL, but shouldn't be a problem we just use the parent.
Working on currentKey: Default Web Site/aspnet_client
authLocation was NULL, but shouldn't be a problem we just use the parent.
Working on currentKey: Default Web Site/aspnet_client
authLocation was NULL, but shouldn't be a problem we just use the parent.
Working on currentKey: Default Web Site/aspnet_client
authLocation was NULL, but shouldn't be a problem we just use the parent.
Working on currentKey: Default Web Site/aspnet_client
authLocation was NULL, but shouldn't be a problem we just use the parent.
Working on currentKey: Default Web Site/aspnet_client`
... a thousand more ..
```

**Additional context**
Rolling back to verrsion 23.12.08.2252 fixes the issue

**Comment by lusassl-msft** [comment]
@sriccio thanks for reporting this. We're actively investigating this issue. Can you please reach out to us by email (ExToolsFeedback[at]microsoft[dot]com)? We have a test build that should work. It would be great if you could run it and share the debug log `(-SaveDebugLog)` with us.
