### ISSUE TITLE
[Issue] SourceSideValidations - Get-MailboxDatabase Identity not found

### ISSUE THREAD

**Issue by DrSleez** [microsoft/CSS-Exchange#1922]
**Describe the issue**
When running the script two issues appear when trying to execute Get-MailboxDatabase with the Get-Mailbox -PublicFolder function.

**Expected behavior**
The cmdlet Get-MailboxDatabase should return the appropiate Database and in this case the ServerName

**Script Output**
```powershell
Die Argumenttransformation für den Parameter "Identity" kann nicht verarbeitet werden. Der Wert "PFDatabase" vom Typ
"Deserialized.Microsoft.Exchange.Data.Directory.ADObjectId" kann nicht in den Typ
"Microsoft.Exchange.Configuration.Tasks.DatabaseIdParameter" konvertiert werden.
    + CategoryInfo          : InvalidData: (:) [Get-MailboxDatabase], ParameterBindin...mationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Get-MailboxDatabase 
```

**Solution idea**
In our case it was necessary to pass the name parameter of the mailbox to the cmdlet. E.g. 
(Get-MailboxDatabase (Get-Mailbox -PublicFolder (Get-OrganizationConfig).RootPublicFolderMailbox.HierarchyMailboxGuid.ToString()).Database.Name).Server.Name in the function Get-FolderData 
And  $db = Get-MailboxDatabase $_.Database.Name -Status in line 2616 in the check if anyDatabase is down.
Script Version: 23.12.08.2252
Version: Exchange 2019 CU13 Nov23SU
Build Number: 15.02.1258.028

**Comment by lusassl-msft** [comment]
This behavior is caused by a known issue with Serialized Data Signing (https://learn.microsoft.com/en-us/exchange/plan-and-deploy/post-installation-tasks/security-best-practices/exchange-serialization-payload-sign?view=exchserver-2019#november-2023-su).
