### ISSUE TITLE
[Issue] - Health Checker - Current Auth Certificate shows False

### ISSUE THREAD

**Issue by jtsai8585** [microsoft/CSS-Exchange#1925]
On Exchange Server 2016 latest patches
v23.12.21.1339
Provide the version of the script that has the issue.

Current Auth Certificate result = false even if it is valid checked by monitorExchangeAuthCertificate.ps1 and 
(Get-AuthConfig).CurrentCertificateThumbprint | Get-ExchangeCertificate | Format-List Subject, Thumbprint, NotAfter, NotBefore
Internal Server Certificate = True
A clear and concise description of the issue.

Should be True since certificate is configured and valid.

Internal Transport Certificate	True
Current Auth Certificate	False
Next Auth Certificate	False
SAN Certificate	True
Namespaces...
Certificate <empty>
Lifetime in days	1779  << cert
If applicable, add the exception that wasn't handled.

Invalid results for the auth certificate

**Comment by dpaulson45** [comment]
@jtsai8585 Are you looking at the correct cert? In the Certificates section, you will see `Current Auth Certificate: False` for all certificates except the one cert that is the auth cert.

In the post you provided that `Internal Transport Certificate: True` and `SAN Certificate: True` which is **NOT** typical for the Auth cert.

**Comment by jtsai8585** [comment]
I see what you mean now.  Each cert have all four types listed.
Thanks.
