### ISSUE TITLE
Health checker should check if a custom EXO connector is present

### ISSUE THREAD

**Issue by richfaj** [microsoft/CSS-Exchange#1976]
**Is your request related to a problem? Please describe.**
Health checker should check if a custom EXO connector is present. Can be done by checking the presence of tenant EOP mx endpoint in smarthost or presence of hybrid mail routing domain.

**Describe The Request**
Customers can create a custom send connector that may not be properly configured to relay mail to Office 365.
For example, a mismatch in server FQDN and certificate may present the wrong certificate.

**Additional context**

**Comment by bill-long** [comment]
Discussed with Richard. We want to add the following logic:

Where the following condition is true:

* Send connector is using a *.mail.protection.outlook.com smart host
 or
* Send connector is using DNS routing to *.mail.onmicrosoft.com

The connector is misconfigured if the following requirements are not met:

* TLSCertificateName is set
* CloudServicesMailEnabled is True

Optionally, we may want to consider a warning if the following requirements are not met:

* TLSAuthLevel is set to DomainValidation
* TLSDomain is set to mail.protection.outlook.com

**Comment by dpaulson45** [comment]
How about something like this? 

![image](https://github.com/microsoft/CSS-Exchange/assets/22776718/f5b776ca-91c6-4b37-aad5-cf64e129881f)


Still need to look into the optional stuff and create a link and doc.

Please verify wording we would like to use for the misconfigured decision and the optional.

**Comment by stanalek** [comment]
Misconfigured to properly send to EXO in "all scenarios" is confusing. Just say it is misconfigured to send authenticated, internal mail to EXO.
Also connector name could be long - I would make sure you can handle this scenario: Send Connector is misconfigured: _Conn Name_

**Comment by richfaj** [comment]
Would also be good to surface that this is a **custom** connector (not created by HCW).

**Comment by dpaulson45** [comment]
Current updated wording/view: 

![image](https://github.com/microsoft/CSS-Exchange/assets/22776718/d436517d-43a1-4238-b251-d9155d0af5c1)
