### ISSUE TITLE
[Issue] - Health Checker "Failed to Health Checker against"

### ISSUE THREAD

**Issue by TCSITom** [microsoft/CSS-Exchange#1977]
**Provide Version Number**
24.02.07.2153, 24.01.23.1802

**Describe the issue**
When attempting to run HealthChecker.ps1 after the Holidays, it requested to update to 24.01.23.1802 from 23.11.29.1401.  That proceeded ok and I re-ran HealthChecker.ps1 to see where our Exchange server was at.  However it only gave me the output:

"Exchange Health Checker version 24.01.23.1802
Failed to Health Checker against EX19"

Since then I waited for an update to EHC and today noticed that we got 24.02.07.2153.  It gives the same results.  I've tried rebooting Exchange, with no change and  I always run EMS elevated.

Setup is fairly straightforward:

Single Forest, Single Domain, all VM's on a single host.  AD & Exchange are separate VMs.  Exchange Server 2019 is a single server deployment with all roles on one VM:

ProductVersion   FileVersion      FileName
--------------   -----------      --------
15.02.1258.028   15.02.1258.028   C:\Program Files\Microsoft\Exchange Server\V15\bin\ExSetup.exe

We are an MSP and we have 2 confirmed Exchange servers - ours which is detailed above, but also a Customer deployment of Exchange 2016 that is doing the same thing.  I am confirming with my team but I think we have 2 others that are similarly affected for a possible total of 4 deployments all exhibiting the same result.

I checked for any other issues related to the "Failed to Health Checker against" type messages and did find two in the Issues section.  They referenced being able to recreate a similar issue with a path problem to "exsetup.exe", however ours seems ok in that regard:

"[PS] >get-command exsetup.exe

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     ExSetup.exe                                        15.2.12... C:\Program Files\Microsoft\Exchange Server\V15\bin\ExSetup.exe"

And our path variable has the Exchange Bin path in it:

"PATH=; ;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\dotnet\;C:\Program Files\WindowsPowerShell\Scripts;**C:\Program Files\Microsoft\Exchange Server\V15\bin**;C:\Program Files\Microsoft\Exchange Server\V15\Bin\Search\Ceres\Native\;C:\Program Files\AzureConnectedMachineAgent\;"

Lastly, I restored a copy of HealthChecker.ps1 from December:

".\HealthChecker.ps1

Confirm
Are you sure you want to perform this action?
Performing the operation "Update script to latest version" on target "HealthChecker.ps1".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): n
Exchange Health Checker version 23.11.29.1401"

I let 23.11.29.1401 run and it ran correctly and provided a proper report as expected with no "red" errors or correctable items needing to be addressed.

I immediately went back and tried to re-run 24.02.07.2153 and it produced the same error and did not run correctly.

**Expected behavior**
I expected EHC to run, but it did not, just giving us the below output.

**Script Output**
Exchange Health Checker version 24.02.07.2153
Failed to Health Checker against EX19

and

Exchange Health Checker version 24.01.23.1802
Failed to Health Checker against EX19
 
 From the last two versions of the script.

23.11.29.1401 partial log showing correct results:

Exchange Health Checker version 23.11.29.1401
Virtual Machine detected.  Certain settings about the host hardware cannot be detected from the virtual machine.  Verify on the VM Host that:

    - There is no more than a 1:1 Physical Core to Virtual CPU ratio (no oversubscribing)
    - If Hyper-Threading is enabled do NOT count Hyper-Threaded cores as physical cores
    - Do not oversubscribe memory or use dynamic memory allocation

Although Exchange technically supports up to a 2:1 physical core to vCPU ratio, a 1:1 ratio is strongly recommended for performance reasons.  Certain third party Hyper-Visors such as VMWare have their own guidance.

VMWare recommends a 1:1 ratio.  Their guidance can be found at https://aka.ms/HC-VMwareBP2019.
Related specifically to VMWare, if you notice you are experiencing packet loss on your VMXNET3 adapter, you may want to review the following article from VMWare:  https://aka.ms/HC-VMwareLostPackets.

For further details, please review the virtualization recommendations on Microsoft Docs here: https://aka.ms/HC-Virtualization.

Exchange Information
--------------------
	Name: *redacted*
	Generation Time: 02/07/2024 18:24:45
	Version: Exchange 2019 CU13 Nov23SU
	Build Number: 15.02.1258.028
	Exchange IU or Security Hotfix Detected: 
		Security Update for Exchange Server 2019 Cumulative Update 13 (KB5026261)
		Security Update for Exchange Server 2019 Cumulative Update 13 (KB5029388)
		Security Update for Exchange Server 2019 Cumulative Update 13 (KB5030524)
		Security Update for Exchange Server 2019 Cumulative Update 13 (KB5030877)
		Security Update for Exchange Server 2019 Cumulative Update 13 (KB5032146)
	Server Role: Mailbox
	DAG Name: Standalone Server
	AD Site: Default-First-Site-Name
	MRS Proxy Enabled: True

**Comment by TCSITom** [comment]
I also just confirmed, with a copy of the restored HealthChecker.ps1 version 23.11.29.1401 - it also runs correctly on the customer's Exchange 2016 mentioned above.

**Comment by dpaulson45** [comment]
@TCSITom please provide the debug log from the failed version of the script and send it to ExToolsFeedback@microsoft.com

```
.\HealthChecker.ps1 -SaveDebugLog
```

**Comment by TCSITom** [comment]
@lusassl-msft  and @dpaulson45  - I've just emailed the debug logs from our EX19 and our Customer's EX16 servers.

Thanks!

**Comment by dpaulson45** [comment]
The inner error that is causing this problem:

```
Exception calling "Add" with "2" argument(s): "Item has already been added. Key in dictionary: 'Default Web Site/CustomSite/Pages'  Key being added: 'Default Web Site/CustomSite/Pages'"
Inner Exception:    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
Position Message: At C:\HealthChecker.ps1:4211 char:13
+             $ipFilterSettings.Add($appKey, (New-Object System.Collect ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Script Stack: at Get-IPFilterSetting<Process>, C:\HealthChecker.ps1: line 4211
at Invoke-AnalyzerIISInformation, C:\HealthChecker.ps1: line 4763
at Invoke-AnalyzerEngine, C:\HealthChecker.ps1: line 8627
at Get-HealthCheckerData, C:\HealthChecker.ps1: line 15412
at Invoke-HealthCheckerMainReport, C:\HealthChecker.ps1: line 15493
at <ScriptBlock><End>, C:\HealthChecker.ps1: line 16304
at <ScriptBlock>, <No file>: line 1
```

https://github.com/microsoft/CSS-Exchange/blob/ce4285865f3cb4debb5030afc65585fd9554a65c/Diagnostics/HealthChecker/Analyzer/Get-IPFilterSetting.ps1#L19
