### ISSUE TITLE
CompareExchangeHashes.ps1 [\version\] in Baselines

### ISSUE THREAD

**Issue by crbartlett84** [microsoft/CSS-Exchange#198]
It seems that anything with a filepath \version\ in the baseline files are not getting correctly compared. I have done some manual compares and they match, however when using the baselines through the powershell script NoHashMatch. 

I suspect this is because the filepath is \version\ whereas the actual includes a version number, I would have thought that the baselines would already have the version numbers in the Path, wondering if this is a miss?

Anything that has a Path that doesnt have a version number in it, ie root directories and such all process correctly and output no error.

**Comment by anshuldube** [comment]
Can you please take the latest version of the script from https://github.com/microsoft/CSS-Exchange/releases/latest//download/CompareExchangeHashes.ps1 and try again? 
We have made some fixes and uploaded baseline hashes. 
Also could you also share the output from the script?

**Comment by anshuldube** [comment]
This issue is fixed.
