### ISSUE TITLE
[Work Item] Add Analyze Parameter to ExchangeExtendedProtectionManagement script

### ISSUE THREAD

**Issue by Sureshbd** [microsoft/CSS-Exchange#1991]
**Describe the work**
Due to the recent release of CU14 & EP enablement it would be good if we can have additional parameter for EP script.
Either -Analyze or -Report or -Scan wherein it scans all the servers.
We then could send a consolidated plan to address the issue reported by the scan by reviewing the log.
An alternate option would be to execute the script in read only mode by default without performing changes.

**Additional Context**
Any other context here.

**Comment by dpaulson45** [comment]
In the meantime, `-WhatIf` will work to do what you are looking for.

**Comment by Sureshbd** [comment]
[like]  Suresh Babu D reacted to your message:
________________________________
