### ISSUE TITLE
[Issue] - Health Checker throwing a warning for TlsDomain, but unable to change

### ISSUE THREAD

**Issue by dzampino** [microsoft/CSS-Exchange#1999]
**Provide Version Number**
v24.02.13.1755

**Describe the issue**
We are now receiving a warning that "TLSDomain not set to mail.protection.outlook.com" for our send connector to Exchange Online Protection.

**Expected behavior**
Our TlsAuthLevel is set to "CertificateValidation". Running `Get-SendConnector | Set-SendConnector -TlsDomain 'mail.protection.outlook.com'` results in the following error message: `Set-SendConnector: The TLSDomain parameter can only be set if the TLSAuthLevel parameter is set to DomainValidation.` Additionally, the More Information link https://aka.ms/HC-ExoConnectorIssue is currently going to https://microsoft.github.io/CSS-Exchange/ instead of https://microsoft.github.io/CSS-Exchange/Diagnostics/HealthChecker/ExoConnectorCheck/

**Comment by dpaulson45** [comment]
In the output, it should provide which Send connector is the problem. What you attempted to do is set ALL your send connectors to that value, which is likely wrong.

I have addressed the aka.ms link, it might take a while to replicate.

**Comment by dzampino** [comment]
We only have the one, but I did try manually specifying it and received the same error message.

`Set-SendConnector -Identity "MX to EOP" -TlsDomain 'mail.protection.outlook.com'
Set-SendConnector: The TLSDomain parameter can only be set if the TLSAuthLevel parameter is set to DomainValidation.`

Here is the send connector (obfuscated):
`AddressSpaces                : {smtp:*;1}
AuthenticationCredential     :
CloudServicesMailEnabled     : True
Comment                      :
ConnectedDomains             : {}
ConnectionInactivityTimeOut  : 00:10:00
ConnectorType                : Default
DNSRoutingEnabled            : False
DomainSecureEnabled          : False
Enabled                      : True
ErrorPolicies                : Default
ForceHELO                    : False
Fqdn                         : mail.example.com
FrontendProxyEnabled         : False
HomeMTA                      : Microsoft MTA
HomeMtaServerId              : MX
Identity                     : MX to EOP
IgnoreSTARTTLS               : False
IsScopedConnector            : False
IsSmtpConnector              : True
MaxMessageSize               : 35 MB (36,700,160 bytes)
Name                         : MX to EOP
Port                         : 25
ProtocolLoggingLevel         : Verbose
Region                       : NotSpecified
RequireOorg                  : False
RequireTLS                   : True
SmartHostAuthMechanism       : None
SmartHosts                   : {example.mail.protection.outlook.com}
SmartHostsString             : example.mail.protection.outlook.com
SmtpMaxMessagesPerConnection : 20
SourceIPAddress              : 0.0.0.0
SourceRoutingGroup           : Exchange Routing Group (DWBGZMFD01QNBJR)
SourceTransportServers       : {MX}
TlsAuthLevel                 : CertificateValidation
TlsCertificateName           : <I>CN=Go Daddy Secure Certificate Authority - G2,
                               OU=http://certs.godaddy.com/repository/, O="GoDaddy.com, Inc.",
                               L=Scottsdale, S=Arizona, C=US<S>CN=*.example.com
TlsDomain                    :
UseExternalDNSServersEnabled : False`

**Comment by dpaulson45** [comment]
Thanks for this. 

I have talked with our hybrid mail flow person and he agrees that we need to make this change. If `TlsAuthLevel` is not set to `DomainValidation` that we don't need `TlsDomain` set to `'mail.protection.outlook.com'`

I will work on a change for this.
