### ISSUE TITLE
[Issue] - Health Checker not able to execute?

### ISSUE THREAD

**Issue by xe0n11** [microsoft/CSS-Exchange#2004]
**Provide Version Number**
Latest release

**Describe the issue**
The health checker script does not execute. 

Steps:
Downloaded the Health Checker script folder and copying to C:\Scripts\HealthChecker on mailbox server,
Logged on locally to server, launched EMS.
cd C:\Scripts\HealthChecker
.\HealthChecker.ps1 -BuildHtmlServersReport

**Expected behavior**

The script would start running the health checker.

**Script Output**

[PS] C:\Scripts\HealthChecker>.\HealthChecker.ps1 -BuildHtmlServersReport
. : The term 'C:\Scripts\HealthChecker\Analyzer\..\..\..\Shared\VisualCRedistributableVersionFunctions.ps1' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Scripts\HealthChecker\Analyzer\Invoke-AnalyzerEngine.ps1:6 char:3
+ . $PSScriptRoot\..\..\..\Shared\VisualCRedistributableVersionFunction ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Scripts\Heal...onFunctions.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

. : The term 'C:\Scripts\HealthChecker\Analyzer\..\..\..\Shared\ErrorMonitorFunctions.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Scripts\HealthChecker\Analyzer\Invoke-AnalyzerKnownBuildIssues.ps1:5 char:3
+ . $PSScriptRoot\..\..\..\Shared\ErrorMonitorFunctions.ps1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Scripts\Heal...orFunctions.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

And so on... 

**Additional context**
![image](https://github.com/microsoft/CSS-Exchange/assets/53819142/b32e77f4-6333-4ae1-b9f7-b605f3c1e12c)

The Exchange server is effectively a clean build.

Server Core 22\Exchange Server 2019 CU14.

Not sure what the problem is?

**Comment by lusassl-msft** [comment]
@xe0n11 it looks like you've downloaded the HealthChecker project file and not the final build version. Please download the script by using this link: https://github.com/microsoft/CSS-Exchange/releases/latest/download/HealthChecker.ps1

**Comment by xe0n11** [comment]
Ah, mistake! Close the ticket issue plz. I was thinking I'm pretty sure I've ran this before 😂. Cheers mate

**Comment by lusassl-msft** [comment]
No worries and thanks for the confirmation.
