### ISSUE TITLE
.\ExchangeExtendedProtectionManagement.ps1 Error

### ISSUE THREAD

**Issue by gringo-82** [microsoft/CSS-Exchange#2007]
Hello all,

I'm getting again this warning like last year where the script was broken...
Any known bugs?

**Describe the issue**
Script version: 24.02.13.1755
WARNUNG: This script requires to be run inside of Exchange Management Shell. Please run on an Exchange Management
Server or an Exchange Server with Exchange Management Shell.
Server 2016Std German + Exchange 2016 Std CU23 Nov23SU Build Number: 15.01.2507.035

Regards,

gringo

**Comment by lusassl-msft** [comment]
@gringo-82 please check if your Auth Certificate is valid. You can do that by running the following script: https://aka.ms/MonitorExchangeAuthCertificate

**Comment by gringo-82** [comment]
Woah, awesome! Thank you!
The Cert was valid till 2026, and no problems - but your script told "valid for -1 Days".
Renewed, restartet and waited - now it works!

Thanks again!
