### ISSUE TITLE
[Issue] - Health Checker

### ISSUE THREAD

**Issue by Maximss** [microsoft/CSS-Exchange#2016]
**Provide Version Number**
Exchange Health Checker version 24.02.15.1640

**Describe the issue**
Error when run with parameter BuildHtmlServersReport

**Expected behavior**
 Switch to enable the script to build the HTML report for all the servers XML results in the XMLDirectoryPath location

**Script Output**
PS C:\2> .\HealthChecker.ps1 -BuildHtmlServersReport

There appears to have been some errors in the script. To assist with debugging of the script, please send the HealthC
ker-Debug_*.txt, HealthChecker-Errors.json, and .xml file to ExToolsFeedback@microsoft.com.
Failed to export the HealthChecker-Errors.json
Output Debug file written to .\HealthChecker-Debug_20240222111557.txt

**Additional context**
[HealthChecker-HTMLServerReport-20240222111557.txt](https://github.com/microsoft/CSS-Exchange/files/14370942/HealthChecker-HTMLServerReport-20240222111557.txt)
[HealthChecker-Debug_20240222111557.txt](https://github.com/microsoft/CSS-Exchange/files/14370944/HealthChecker-Debug_20240222111557.txt)
[HealthChecker-Errors.json](https://github.com/microsoft/CSS-Exchange/files/14370947/HealthChecker-Errors.json)

**Comment by dpaulson45** [comment]
@Maximss did you run the `.\HealthChecker.ps1` prior to attempting to build the Html Report? As that is required.

**Comment by dpaulson45** [comment]
@Maximss closing this out as no feedback has been provided to confirm cause of problem.
