### ISSUE TITLE
[Issue] - Health Checker -HtmlReportFile does not overwrite

### ISSUE THREAD

**Issue by daepunt** [microsoft/CSS-Exchange#2026]
**Provide Version Number**
Provide the version of the script that has the issue.
v24.02.15.1640

**Describe the issue**
A clear and concise description of the issue.
When running .\HealthChecker.ps1 -BuildHtmlServersReport the default report file ExchangeAllServersReport.html is not overwritten if it already exists. Instead, a unique filename with timestamp is created and there is no mention of this.
Even when I supply the parameter -HtmlReportFile C:\Scripts\ExchangeAllServersReport.html the behaviour stays the same. The command line mentions HTML Report Location: C:\Scripts\ExchangeAllServersReport.html, but the content of the existing file is the same, so nothing changes.

**Expected behavior**
I would expect the script to either overwrite the existing file (espcially with the -HtmlReportFile parameter supplied) or at least to report to the command line that the file already exists and therefore the supplied filename is ignored. if an -Overwrite parameter could be added, I would be happy to use it. I am using the script to gather several reports and compile them into an email. Reusing the same filename makes it easier to gather everything.

**Script Output**
If applicable, add the exception that wasn't handled.

**Additional context**

**Comment by lusassl-msft** [comment]
@daepunt just to double check. If you execute the script like this, the content is not overwritten?

_.\HealthChecker.ps1 -BuildHtmlServersReport -HtmlReportFile “ExchangeAllServersReport.html"_

Note that HealthChecker will consume the latest .xml files, so if you run it twice using this command, it's expected that the content doesn't change because the existing .xml file is used.

**Comment by dpaulson45** [comment]
@daepunt then you aren't running it correctly. It requires there to be .xml files to be generated prior to you running a new report. If the .xml file data doesn't change, neither will your .html data.

**Comment by daepunt** [comment]
Aaagh! There it is. I thought it was possible to run the script and create reports at the same time. I'm running the script first, now,  and then create the report. Thanks for pointing that out!

**Comment by lusassl-msft** [comment]
Question answered.
