### ISSUE TITLE
[Issue] - Health Checker failed on Chinese Traditional OS

### ISSUE THREAD

**Issue by MashiZhou** [microsoft/CSS-Exchange#2027]
**Provide Version Number**
24.02.15.1640

**Describe the issue**
HealthChecker would fail after analyzing data.
But if I use version 23.11.01.2049, it worked properly.

**Comment by MashiZhou** [comment]
I had tried that it works on English version OS, but failed on Chinese version OS.
Is encoding problem?

version Number 
24.03.12.1700

**Comment by dpaulson45** [comment]
@MashiZhou I was able to reproduce this on a Chinese Traditional OS language. I am assuming that is the OS version that you have as well? Chinese Simplified didn't cause the problem from lab testing.

Will start to work on a fix for this.
