### ISSUE TITLE
Exchange 2019 Not detecting New CU - Health Checker

### ISSUE THREAD

**Issue by bbresky1** [microsoft/CSS-Exchange#2045]
**Provide Version Number**
Version: 24.03.12.1700

**Describe the issue**
Have an Exchange Server 2019 that is missing CU14 Build Number 15.02.1544.004
Script shows Exchange Build and Version is at:
Version: Exchange 2019 CU13 Nov23SU
Build Number: 15.02.1258.028 

**Expected behavior**
Script should be able to see new CU update when posted to website.

**Comment by dpaulson45** [comment]
@bbresky1 What is your concern here?

**Comment by bbresky1** [comment]
I have a test Exchange server with a CU that is out of date by three versions, and the script is able to detect that this Server is out of date. However, running on Exchange servers that are only out of date by one CU, the script cannot detect that this is out of date. 
I'm looking to run this script in an environment with multiple exchange servers. When a new CU is released, compare that to the current CU. Create an alert when a CU is out of date. Should the script be able to see new CU's when they are released, or does it take time to see a new CU?

**Comment by dpaulson45** [comment]
CU13 is a supported CU and is not out of date. Just because a new CU is released, don't make all previous versions CUs out of date or support. That is why we still release SUs for all supported CUs. 

If you run the script against CU12, with the version that you are on, it should report it as out of support.

**Comment by bbresky1** [comment]
This makes complete sense: Learn something new every day. I appreciate the information.
