### ISSUE TITLE
[Issue] - HealthChecker documentation issue regarding HTML report

### ISSUE THREAD

**Issue by worldsdream** [microsoft/CSS-Exchange#2053]
**Provide Version Number**
Exchange Health Checker v24.03.12.1700

**Describe the issue**
An error appears when opening the HTML report.

When you go to the page: https://microsoft.github.io/CSS-Exchange/Diagnostics/HealthChecker/, you will see one of the commands:

PS C:\> Get-ExchangeServer | ?{$_.AdminDisplayVersion -Match "^Version 15"} | .\HealthChecker.ps1; .\HealthChecker.ps1 -BuildHtmlServersReport; .\ExchangeAllServersReport.html

The above command always worked. But there has been a change where the report now adds a date behind it. So it's not generic "ExchangeAllServersReport.html".

**Expected behavior**
The HTML report needs to open.

**Script Output**
HTML Report Location: .\ExchangeAllServersReport-20240329084414.html
.\ExchangeAllServersReport.html : The term '.\ExchangeAllServersReport.html' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify
that the path is correct and try again.
At line:1 char:137
+ ... hChecker.ps1 -BuildHtmlServersReport; .\ExchangeAllServersReport.html
+                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\ExchangeAllServersReport.html:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Additional context**
Change the command to a new one, where it will know what name is been given to the report, so it will open the correct report after it finishes.

**Comment by lusassl-msft** [comment]
Hi @worldsdream. You’re correct - the new html report contains a timestamp which is by design as we received multiple requests from customers to make the name unique. If you want to keep the old name, just run the script like this:

`.\HealthChecker.ps1 -BuildHtmlServersReport -HtmlReportFile “ExchangeAllServersReport.html"`

**Comment by worldsdream** [comment]
Hi Lukes,

Thanks for the information you provided.

When you run the command (see screenshot below):

![info](https://github.com/microsoft/CSS-Exchange/assets/12443285/a23dbaf7-3835-444f-97ec-cfa47dc93549)

The error appears:

![info2](https://github.com/microsoft/CSS-Exchange/assets/12443285/6e07fb94-f277-4c86-9d93-ddd5ee39cb2d)

So the command needs to change in that page, right?

**Comment by lusassl-msft** [comment]
@worldsdream yep, you're correct. The documentation is wrong. I will update it to reflect the latest changes in HealthChecker. Thanks for pointing this out!
