### ISSUE TITLE
[Issue]baseline_15.0.1497.7.zip not found... please open issue on https://github.com/microsoft/CSS-Exchange/issues, we will work on it

### ISSUE THREAD

**Issue by Lxfchen** [microsoft/CSS-Exchange#206]
**Describe the issue**
Running the CompareExchangeHashes.ps1 script. Missing baseline file for 15.0.1497.7 at https://github.com/microsoft/CSS-Exchange/releases/tag/v21.03.09.2327

**Expected behavior**
Once the baseline file is uploaded I believe the script will pull it from the repository.

**Script Output**
If applicable, add the exception that you are seeing that wasn't handled.

**Additional context**

**Comment by anshuldube** [comment]
This baseline is added now, Can you please take the latest version of the script from https://github.com/microsoft/CSS-Exchange/releases/latest//download/CompareExchangeHashes.ps1 and try again?

**Comment by Lxfchen** [comment]
> This baseline is added now, Can you please take the latest version of the script from https://github.com/microsoft/CSS-Exchange/releases/latest//download/CompareExchangeHashes.ps1 and try again?

It works now. Thank you for the follow up!
