### ISSUE TITLE
VSSTester [Issue]

### ISSUE THREAD

**Issue by reuvygroovy** [microsoft/CSS-Exchange#2093]
Using the latest version of VSSTester

When running I get the following error

[PS] C:\temp>.\VSSTester111.ps1 -database test -TraceOnly

Do you want to run software from this untrusted publisher?
File C:\temp\VSSTester111.ps1 is published by CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US and is not trusted on your system. Only run scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"): r
Transcript started, output file is C:\temp\240522-143321\vssTranscript.log
05/22/2024 14:33:21 Verifying Exchange version...
  EXCHANGESERVER is an Exchange 2019 server.
05/22/2024 14:33:22 Checking VSS Writer Status: (All Writers must be in a Stable state before running this script)
05/22/2024 14:33:49 Stopping transcript log...
Transcript stopped, output file is C:\temp\240522-143321\vssTranscript.log
Script completed.
Get-VSSWriter : You cannot call a method on a null-valued expression.
At C:\temp\VSSTester111.ps1:885 char:16
+     $writers = Get-VSSWriter
+                ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-VSSWriter], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull,Get-VSSWriter

I was on the phone wiht support and they reproduced this as well on their end. When I used an older version they provided me with this error didn't occur

**Comment by dpaulson45** [comment]
What was the output of `vssadmin list writers` at the time of the issue. Can you provide the logs to `ExToolsFeedback@microsoft.com`?

**Comment by reuvygroovy** [comment]
[PS] C:\temp> vssadmin list writers
vssadmin 1.1 - Volume Shadow Copy Service administrative command-line tool
(C) Copyright 2001-2013 Microsoft Corp.

Waiting for responses.
These may be delayed if a shadow copy is being prepared.

Writer name: 'Task Scheduler Writer'
   Writer Id: {d61d61c8-d73a-4eee-8cdd-f6f9786b7124}
   Writer Instance Id: {1bddd48e-5052-49db-9b07-b96f96727e6b}
   State: [1] Stable
   Last error: No error

Writer name: 'VSS Metadata Store Writer'
   Writer Id: {75dfb225-e2e4-4d39-9ac9-ffaff65ddf06}
   Writer Instance Id: {088e7a7d-09a8-4cc6-a609-ad90e75ddc93}
   State: [1] Stable
   Last error: No error

Writer name: 'Performance Counters Writer'
   Writer Id: {0bada1de-01a9-4625-8278-69e735f39dd2}
   Writer Instance Id: {f0086dda-9efc-47c5-8eb6-a944c3d09381}
   State: [1] Stable
   Last error: No error

Writer name: 'System Writer'
   Writer Id: {e8132975-6f93-4464-a53e-1050253ae220}
   Writer Instance Id: {a29aadde-0639-4400-923a-5fd982e53c7e}
   State: [1] Stable
   Last error: No error

Writer name: 'ASR Writer'
   Writer Id: {be000cbe-11fe-4426-9c58-531aa6355fc4}
   Writer Instance Id: {965ce078-0b03-4eda-bdd0-be675a7de10d}
   State: [1] Stable
   Last error: No error

Writer name: 'Microsoft Exchange Writer'
   Writer Id: {76fe1ac4-15f7-4bcd-987e-8e1acb462fb7}
   Writer Instance Id: {0ae5d2c7-a9fe-43f9-a61f-86563b439453}
   State: [8] Failed
   Last error: Not responding

Writer name: 'Shadow Copy Optimization Writer'
   Writer Id: {4dc3bdd4-ab48-4d07-adb0-3bee2926fd7f}
   Writer Instance Id: {a7a458b4-eaaa-4429-9382-f2d3101ab90b}
   State: [1] Stable
   Last error: No error

Writer name: 'IIS Config Writer'
   Writer Id: {2a40fd15-dfca-4aa8-a654-1f8c654603f6}
   Writer Instance Id: {171318eb-3481-4674-aa1e-c4acab3b34a8}
   State: [1] Stable
   Last error: No error

Writer name: 'Registry Writer'
   Writer Id: {afbab4a2-367d-4d15-a586-71dbb18f8485}
   Writer Instance Id: {cb6339da-6e61-4419-aec0-1768c25fcf5f}
   State: [1] Stable
   Last error: No error

Writer name: 'MSMQ Writer (MSMQ)'
   Writer Id: {7e47b561-971a-46e6-96b9-696eeaa53b2a}
   Writer Instance Id: {3ccabd86-db01-4452-af38-36032fb964f1}
   State: [1] Stable
   Last error: No error

Writer name: 'WMI Writer'
   Writer Id: {a6ad56c2-b509-4e6c-bb19-49d8f43532f0}
   Writer Instance Id: {60bdda81-7474-439f-9cb3-932b4d3e8c32}
   State: [1] Stable
   Last error: No error

Writer name: 'COM+ REGDB Writer'
   Writer Id: {542da469-d3e1-473c-9f4f-7847f01fc64f}
   Writer Instance Id: {dad80ab3-2ebe-46b2-aa8d-0a988c0aad9e}
   State: [1] Stable
   Last error: No error

Writer name: 'IIS Metabase Writer'
   Writer Id: {59b1f0cf-90ef-465f-9609-6ca8b2938366}
   Writer Instance Id: {c0b426cd-5492-4725-b0de-b58c2e1e281b}
   State: [1] Stable
   Last error: No error

Writer name: 'Cluster Shared Volume VSS Writer'
   Writer Id: {1072ae1c-e5a7-4ea1-9e4a-6f7964656570}
   Writer Instance Id: {e9a1c0f9-6b06-4662-abf3-b04f66b848e6}
   State: [1] Stable
   Last error: No error

Writer name: 'BITS Writer'
   Writer Id: {4969d978-be47-48b0-b100-f328f07ac1e0}
   Writer Instance Id: {f6214e79-e7b0-473f-851a-1a4a4d802707}
   State: [1] Stable
   Last error: No error

Writer name: 'CvWriter'
   Writer Id: {248a30d3-9216-4200-8201-29ac21d6c307}
   Writer Instance Id: {854ea213-995c-4ec1-9c29-46bddd910b61}
   State: [1] Stable
   Last error: No error

Writer name: 'Cluster Database'
   Writer Id: {41e12264-35d8-479b-8e5c-9b23d1dad37e}
   Writer Instance Id: {86705e8b-c7cc-4805-bb27-c07a5cd3e44f}
   State: [1] Stable
   Last error: No error

**Comment by dpaulson45** [comment]
It is expected that we do not continue to process if we are in a failed state for our writer. 

```
Writer name: 'Microsoft Exchange Writer'
Writer Id: {76fe1ac4-15f7-4bcd-987e-8e1acb462fb7}
Writer Instance Id: {0ae5d2c7-a9fe-43f9-a61f-86563b439453}
State: [8] Failed
Last error: Not responding
```

**Comment by reuvygroovy** [comment]
Has this changed? Since the older versions continue just fine.

In this status I could never run this command and support is stuck

**Comment by dpaulson45** [comment]
It might be a bug in the older version. Because we shouldn't continue unless we report `Stable`. 

To reset the Writer, it normally takes you to restart the `Microsoft Exchange Replication` Service. If that doesn't set it back to `Stable`, then I would try a reboot. If both of those don't work, then we need to have support to troubleshoot that.

**Comment by reuvygroovy** [comment]
You should tell your support guys this. I got stuck with a case for two months because they kept telling me to re-run this script and they had no idea why this wasn’t working. ☹

Anyways, I restarted the service, and got the following output nonetheless

[PS] C:\temp> vssadmin list writers
vssadmin 1.1 - Volume Shadow Copy Service administrative command-line tool
(C) Copyright 2001-2013 Microsoft Corp.

Waiting for responses.
These may be delayed if a shadow copy is being prepared.

Writer name: 'Task Scheduler Writer'
   Writer Id: {d61d61c8-d73a-4eee-8cdd-f6f9786b7124}
   Writer Instance Id: {1bddd48e-5052-49db-9b07-b96f96727e6b}
   State: [1] Stable
   Last error: No error

Writer name: 'VSS Metadata Store Writer'
   Writer Id: {75dfb225-e2e4-4d39-9ac9-ffaff65ddf06}
   Writer Instance Id: {088e7a7d-09a8-4cc6-a609-ad90e75ddc93}
   State: [1] Stable
   Last error: No error

Writer name: 'Performance Counters Writer'
   Writer Id: {0bada1de-01a9-4625-8278-69e735f39dd2}
   Writer Instance Id: {f0086dda-9efc-47c5-8eb6-a944c3d09381}
   State: [1] Stable
   Last error: No error

Writer name: 'System Writer'
   Writer Id: {e8132975-6f93-4464-a53e-1050253ae220}
   Writer Instance Id: {a29aadde-0639-4400-923a-5fd982e53c7e}
   State: [1] Stable
   Last error: No error

Writer name: 'ASR Writer'
   Writer Id: {be000cbe-11fe-4426-9c58-531aa6355fc4}
   Writer Instance Id: {965ce078-0b03-4eda-bdd0-be675a7de10d}
   State: [1] Stable
   Last error: No error

Writer name: 'Microsoft Exchange Writer'
   Writer Id: {76fe1ac4-15f7-4bcd-987e-8e1acb462fb7}
   Writer Instance Id: {b0e4ad29-66bb-42a8-a15f-8aca67437608}
   State: [1] Stable
   Last error: No error

Writer name: 'Shadow Copy Optimization Writer'
   Writer Id: {4dc3bdd4-ab48-4d07-adb0-3bee2926fd7f}
   Writer Instance Id: {a7a458b4-eaaa-4429-9382-f2d3101ab90b}
   State: [1] Stable
   Last error: No error

Writer name: 'IIS Config Writer'
   Writer Id: {2a40fd15-dfca-4aa8-a654-1f8c654603f6}
   Writer Instance Id: {171318eb-3481-4674-aa1e-c4acab3b34a8}
   State: [1] Stable
   Last error: No error

Writer name: 'WMI Writer'
   Writer Id: {a6ad56c2-b509-4e6c-bb19-49d8f43532f0}
   Writer Instance Id: {60bdda81-7474-439f-9cb3-932b4d3e8c32}
   State: [1] Stable
   Last error: No error

Writer name: 'Registry Writer'
   Writer Id: {afbab4a2-367d-4d15-a586-71dbb18f8485}
   Writer Instance Id: {cb6339da-6e61-4419-aec0-1768c25fcf5f}
   State: [1] Stable
   Last error: No error

Writer name: 'CvWriter'
   Writer Id: {248a30d3-9216-4200-8201-29ac21d6c307}
   Writer Instance Id: {854ea213-995c-4ec1-9c29-46bddd910b61}
   State: [1] Stable
   Last error: No error

Writer name: 'MSMQ Writer (MSMQ)'
   Writer Id: {7e47b561-971a-46e6-96b9-696eeaa53b2a}
   Writer Instance Id: {3ccabd86-db01-4452-af38-36032fb964f1}
   State: [1] Stable
   Last error: No error

Writer name: 'BITS Writer'
   Writer Id: {4969d978-be47-48b0-b100-f328f07ac1e0}
   Writer Instance Id: {f6214e79-e7b0-473f-851a-1a4a4d802707}
   State: [1] Stable
   Last error: No error

Writer name: 'IIS Metabase Writer'
   Writer Id: {59b1f0cf-90ef-465f-9609-6ca8b2938366}
   Writer Instance Id: {c0b426cd-5492-4725-b0de-b58c2e1e281b}
   State: [1] Stable
   Last error: No error

Writer name: 'Cluster Database'
   Writer Id: {41e12264-35d8-479b-8e5c-9b23d1dad37e}
   Writer Instance Id: {86705e8b-c7cc-4805-bb27-c07a5cd3e44f}
   State: [1] Stable
   Last error: No error

Writer name: 'COM+ REGDB Writer'
   Writer Id: {542da469-d3e1-473c-9f4f-7847f01fc64f}
   Writer Instance Id: {dad80ab3-2ebe-46b2-aa8d-0a988c0aad9e}
   State: [1] Stable
   Last error: No error

Writer name: 'Cluster Shared Volume VSS Writer'
   Writer Id: {1072ae1c-e5a7-4ea1-9e4a-6f7964656570}
   Writer Instance Id: {e9a1c0f9-6b06-4662-abf3-b04f66b848e6}
   State: [1] Stable
   Last error: No error

[PS] C:\temp>.\VSSTester111.ps1 -database test -TraceOnly

Do you want to run software from this untrusted publisher?
File C:\temp\VSSTester111.ps1 is published by CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US and is not trusted on your system. Only run scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"): r
Transcript started, output file is C:\temp\240522-172738\vssTranscript.log
05/22/2024 17:27:38 Verifying Exchange version...
  GEXCHANGE01 is an Exchange 2019 server.
05/22/2024 17:27:38 Checking VSS Writer Status: (All Writers must be in a Stable state before running this script)
05/22/2024 17:27:52 Stopping transcript log...
Transcript stopped, output file is C:\temp\240522-172738\vssTranscript.log
Script completed.
Get-VSSWriter : You cannot call a method on a null-valued expression.
At C:\temp\VSSTester111.ps1:885 char:16
+     $writers = Get-VSSWriter
+                ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-VSSWriter], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull,Get-VSSWriter

[PS] C:\temp> vssadmin list writers
vssadmin 1.1 - Volume Shadow Copy Service administrative command-line tool
(C) Copyright 2001-2013 Microsoft Corp.

Waiting for responses.
These may be delayed if a shadow copy is being prepared.

Writer name: 'Task Scheduler Writer'
   Writer Id: {d61d61c8-d73a-4eee-8cdd-f6f9786b7124}
   Writer Instance Id: {1bddd48e-5052-49db-9b07-b96f96727e6b}
   State: [1] Stable
   Last error: No error

Writer name: 'VSS Metadata Store Writer'
   Writer Id: {75dfb225-e2e4-4d39-9ac9-ffaff65ddf06}
   Writer Instance Id: {088e7a7d-09a8-4cc6-a609-ad90e75ddc93}
   State: [1] Stable
   Last error: No error

Writer name: 'Performance Counters Writer'
   Writer Id: {0bada1de-01a9-4625-8278-69e735f39dd2}
   Writer Instance Id: {f0086dda-9efc-47c5-8eb6-a944c3d09381}
   State: [1] Stable
   Last error: No error

Writer name: 'System Writer'
   Writer Id: {e8132975-6f93-4464-a53e-1050253ae220}
   Writer Instance Id: {a29aadde-0639-4400-923a-5fd982e53c7e}
   State: [1] Stable
   Last error: No error

Writer name: 'ASR Writer'
   Writer Id: {be000cbe-11fe-4426-9c58-531aa6355fc4}
   Writer Instance Id: {965ce078-0b03-4eda-bdd0-be675a7de10d}
   State: [1] Stable
   Last error: No error

Writer name: 'Microsoft Exchange Writer'
   Writer Id: {76fe1ac4-15f7-4bcd-987e-8e1acb462fb7}
   Writer Instance Id: {b0e4ad29-66bb-42a8-a15f-8aca67437608}
   State: [1] Stable
   Last error: No error

Writer name: 'Shadow Copy Optimization Writer'
   Writer Id: {4dc3bdd4-ab48-4d07-adb0-3bee2926fd7f}
   Writer Instance Id: {a7a458b4-eaaa-4429-9382-f2d3101ab90b}
   State: [1] Stable
   Last error: No error

Writer name: 'IIS Config Writer'
   Writer Id: {2a40fd15-dfca-4aa8-a654-1f8c654603f6}
   Writer Instance Id: {171318eb-3481-4674-aa1e-c4acab3b34a8}
   State: [1] Stable
   Last error: No error

Writer name: 'Registry Writer'
   Writer Id: {afbab4a2-367d-4d15-a586-71dbb18f8485}
   Writer Instance Id: {cb6339da-6e61-4419-aec0-1768c25fcf5f}
   State: [1] Stable
   Last error: No error

Writer name: 'MSMQ Writer (MSMQ)'
   Writer Id: {7e47b561-971a-46e6-96b9-696eeaa53b2a}
   Writer Instance Id: {3ccabd86-db01-4452-af38-36032fb964f1}
   State: [1] Stable
   Last error: No error

Writer name: 'COM+ REGDB Writer'
   Writer Id: {542da469-d3e1-473c-9f4f-7847f01fc64f}
   Writer Instance Id: {dad80ab3-2ebe-46b2-aa8d-0a988c0aad9e}
   State: [1] Stable
   Last error: No error

Writer name: 'BITS Writer'
   Writer Id: {4969d978-be47-48b0-b100-f328f07ac1e0}
   Writer Instance Id: {f6214e79-e7b0-473f-851a-1a4a4d802707}
   State: [1] Stable
   Last error: No error

Writer name: 'WMI Writer'
   Writer Id: {a6ad56c2-b509-4e6c-bb19-49d8f43532f0}
   Writer Instance Id: {60bdda81-7474-439f-9cb3-932b4d3e8c32}
   State: [1] Stable
   Last error: No error

Writer name: 'IIS Metabase Writer'
   Writer Id: {59b1f0cf-90ef-465f-9609-6ca8b2938366}
   Writer Instance Id: {c0b426cd-5492-4725-b0de-b58c2e1e281b}
   State: [1] Stable
   Last error: No error

Writer name: 'CvWriter'
   Writer Id: {248a30d3-9216-4200-8201-29ac21d6c307}
   Writer Instance Id: {854ea213-995c-4ec1-9c29-46bddd910b61}
   State: [1] Stable
   Last error: No error

Writer name: 'Cluster Shared Volume VSS Writer'
   Writer Id: {1072ae1c-e5a7-4ea1-9e4a-6f7964656570}
   Writer Instance Id: {e9a1c0f9-6b06-4662-abf3-b04f66b848e6}
   State: [1] Stable
   Last error: No error

Writer name: 'Cluster Database'
   Writer Id: {41e12264-35d8-479b-8e5c-9b23d1dad37e}
   Writer Instance Id: {86705e8b-c7cc-4805-bb27-c07a5cd3e44f}
   State: [1] Stable
   Last error: No error

[PS] C:\temp>

**Comment by dpaulson45** [comment]
After this the script should work to test out the VSS Writer to do a backup.

If you email in your case number, we can inform the support engineer and their TA.

**Comment by dpaulson45** [comment]
Okay, I think I see where the problem might be here. I didn't catch that you provided the failure of the script when the writers were in a stable state. 

Please try this version of the script. Hopefully this allows the additional lines noticed in your `vssadmin list writers` output. 

[VSSTester.txt](https://github.com/microsoft/CSS-Exchange/files/15407113/VSSTester.txt)

**Comment by reuvygroovy** [comment]
No go ☹

Transcript started, output file is C:\temp\240522-221017\vssTranscript.log
05/22/2024 22:10:17 Verifying Exchange version...
  EXCHANGE is an Exchange 2019 server.
05/22/2024 22:10:19 Checking VSS Writer Status: (All Writers must be in a Stable state before running this script)
Finding the first writer...
05/22/2024 22:10:32 Stopping transcript log...
Transcript stopped, output file is C:\temp\240522-221017\vssTranscript.log
Script completed.
Get-VSSWriter : You cannot call a method on a null-valued expression.
At C:\temp\VSSTester-new.ps1:897 char:16
+     $writers = Get-VSSWriter
+                ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-VSSWriter], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull,Get-VSSWriter

PS C:\temp>

**Comment by dpaulson45** [comment]
Opps, I see a mistake I made. Please try this one. 

[VSSTester.txt](https://github.com/microsoft/CSS-Exchange/files/15421696/VSSTester.txt)

**Comment by dpaulson45** [comment]
**Issue Update**

`Get-VSSWriter` only accounts for a standard output where the writers start at line 3. However, based off this output, we can see we have additional lines causing the problem.

https://github.com/microsoft/CSS-Exchange/blob/291801ff25bc10c030a2780d5d3af8a0d94df387/Databases/VSSTester/Logging/Get-VSSWriter.ps1#L14

```
[PS] C:\temp> vssadmin list writers
vssadmin 1.1 - Volume Shadow Copy Service administrative command-line tool
(C) Copyright 2001-2013 Microsoft Corp.

Waiting for responses.                                           <----- 
These may be delayed if a shadow copy is being prepared.         <----- 
                                                                 <----- 
Writer name: 'Task Scheduler Writer'
   Writer Id: {d61d61c8-d73a-4eee-8cdd-f6f9786b7124}
   Writer Instance Id: {1bddd48e-5052-49db-9b07-b96f96727e6b}
   State: [1] Stable
   Last error: No error
....
```

While at first the writer was not stable and will result in the script from executing, that wasn't the reason for the script failure the way it was working. Switching this back to an issue and opening a PR on this.

**Comment by reuvygroovy** [comment]
That looks good. Now I can finally run this! Awesome!
