### ISSUE TITLE
[Issue] - Health Checker

### ISSUE THREAD

**Issue by CrackedBatch** [microsoft/CSS-Exchange#2177]
**Provide Version Number**
Exchange Health Checker version 24.08.08.1523

**Describe the issue**
VMWare VM is configured with Dynamic Memory enabled. Health Checker reporting the following:
Dynamic Memory Detected: True 0GB is the allowed dynamic memory of the server. Not supported to have dynamic memory configured.

**Expected behavior**
Dynamic Memory Detected: False

**Script Output**
Processor/Hardware Information
------------------------------
	Type: VMware
	Processor: Intel(R) Xeon(R) Gold 6208U CPU @ 2.90GHz
	Current Total Processor Usage: 8.59
	Number of Processors: 4
	Number of Physical Cores: 16
	Number of Logical Cores: 16
	Hyper-Threading: Disabled
	All Processor Cores Visible: Passed
	Max Processor Speed: 2893
	Physical Memory: 64 GB
	Dynamic Memory Detected: True 0GB is the allowed dynamic memory of the server. Not supported to have dynamic memory configured.

**Comment by Mehdi-po** [comment]
Bonjour 

Il faut passer en statique la mémoire de ta VM

Dynamic memory détectée passera en false dans ce cas là 
Bien cordialement 
Mehdi

**Comment by Mehdi-po** [comment]
Oui par défaut elle est activé et à 0...😉

**Comment by CrackedBatch** [comment]
> @CrackedBatch dynamic memory isn't supported when running Exchange Server (see: https://learn.microsoft.com/en-us/exchange/plan-and-deploy/virtualization?view=exchserver-2019#exchange-memory-requirements-and-recommendations).
> 
> The output which you've shared looks correct to me. If you turn dynamic memory off, the check will return `Dynamic Memory Detected: False`.

The VM has always been configured with Dynamic Memory disabled, so the expected result should be false. Do you have any other suggestions to test this paramater?
![image](https://github.com/user-attachments/assets/c2543806-5e98-40b1-a2f9-318b809fd9c4)

**Comment by dpaulson45** [comment]
@CrackedBatch unless something has changed a `0` value doesn't mean that you disabled Dynamic Memory. It means that you don't have any dedicated memory to the VM guest machine, thus relying on the host to have available free memory for the guest to use when the guest requests it. This is the definition of Dynamic Memory, adding and having memory removed from the guest as the host needs it.

**Comment by CrackedBatch** [comment]
When checking the ESXi console, the following is returned for the Exchange VM:
Command: vim-cmd vmsvc/get.config 20 | grep -i memoryhotadd
Result:  memoryHotAddEnabled = false

**Comment by dpaulson45** [comment]
Dynamic Memory might not be the proper term in VMware, the setting that we are looking for is memory reservation. You should have the guest VM to have the full memory reserved for the guest machine so the guest machine can decide how to utilize its memory.

**Comment by lusassl-msft** [comment]
I think this is the setting that must be configured:
![image](https://github.com/user-attachments/assets/06cb166f-f114-4017-9d3d-b1b18accd0c4)

**Comment by CrackedBatch** [comment]
That is the setting that needed to be enabled. Thanks all for the guidence!
![image](https://github.com/user-attachments/assets/fd2a5260-7c5a-43a4-9a02-747753c81169)

![image](https://github.com/user-attachments/assets/fb16360c-bcff-4cce-a4d6-9839e4375a8d)
