### ISSUE TITLE
[Issue] SourceSideValidations fails to remove invalid permissions

### ISSUE THREAD

**Issue by bill-long** [microsoft/CSS-Exchange#2183]
After SourceSideValidations finds invalid permissions, it can be run with -RemoveInvalidPermisions switch to remove them. However, sometimes this fails with "There is no existing permission found for user." This can occur when the recipient principal is in various invalid states.

The script used to be able to remove these when we were piping the bad permission to Remove-PublicFolderClientPermission. However, that was changed in order to allow the script to work when serialization signing is _not_ working. That change happened here: https://github.com/microsoft/CSS-Exchange/commit/3bb9f7a40c2f99eb8769e6faae9ffeb52809093

The piping approach fails if:

* The script is run from remote powershell.
* The script is run from EMS but the auth certificate is not valid.

So that change made it work in those scenarios, but now it is not able to reliably remove invalid permissions.

I think we should no longer support those scenarios with the -RemoveInvalidPermissions switch. The script _must_ be able to remove invalid permissions. Therefore, we should revert that change. When the script is run with -RemoveInvalidPermissions, it will require EMS with a working auth certificate.

**Comment by dpaulson45** [comment]
With `Confirm-ExchangeShell`, we do properly detect if the pipeline will work. 

```
$shell = Confirm-ExchangeShell

if (-not $shell.EMS -and $RemoveInvalidPermissions) {
      Write-Host "This script requires EMS. If you are using EMS, then you might have an issue with your Auth Certificate preventing the serialization of the Exchange objects to have pipelining work. Because of pipelining will not work, we are unable to execute the script with the switch `-RemoveInvalidPermissions`"
      Write-Host "Please address the issue or do not use the switch `RemoveInvalidPermissions`"
      exit 
}

```
