### ISSUE TITLE
[Work Item] Display Exchange Server edition and trial information

### ISSUE THREAD

**Issue by lusassl-msft** [microsoft/CSS-Exchange#2191]
**Describe the work**

We should display the `Edition` of the Exchange Server. We should also show a warning if Exchange Server is running in trial `IsExchangeTrialEdition`. We should show a red error if `IsExpiredExchangeTrialEdition` is `True` or when `RemainingTrialPeriod` is `<= 7 days`.

Information can be queried by running: `Get-ExchangeServer | fl *trial*,edition`

**Comment by dpaulson45** [comment]
What about lab environments? They don't require Exchange to be licensed.

**Comment by lusassl-msft** [comment]
Indeed, they can ignore this information.
