### ISSUE TITLE
baseline_15.0.516.30.zip not found

### ISSUE THREAD

**Issue by darknite323** [microsoft/CSS-Exchange#222]
As per title.

```
LoadFromGitHub : C:\temp\baseline_15.0.516.30.zip not found... please open issue on
https://github.com/microsoft/CSS-Exchange/issues, we will work on it
At C:\temp\CompareExchangeHashes.ps1:595 char:13
+             LoadFromGitHub -url $zip_file_url -filename $zip_file -installed_ver ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,LoadFromGitHub
```

**Comment by xGDI** [comment]
Same issuer here with Exchange 2013 Build 15.0.1497.2

**Comment by xGDI** [comment]
> > 15.0.1497.2
> 
> 15.0.1497.2 is available on release: https://github.com/microsoft/CSS-Exchange/releases/latest
> Can you please download the corresponding zip file to the same directory as zip file and try again?

I downloaded the file but it is still looking for the newer version, here the error output:

`[03/10/2021 08:26:40] Started...
Found exchange version: 15.0.1497.2
Can't find local baseline for 15.0.516.30
Downloading baseline file from GitHub to C:\Users\Administrator\Desktop\baseline_15.0.516.30.zip


StatusCode        : 200
StatusDescription : OK
Content           : {52, 50, 57, 66...}
RawContent        : HTTP/1.1 200 OK
                    Connection: keep-alive
                    x-amz-id-2: Dm59o9lYVx3X29/w1mo7kzlD6C65TDqLEIE9mM23Vs/dpX3qKuTR+jcxl7CM/Z6PcfcsCWT2Qg8=
                    x-amz-request-id: 294YQYFG42T2MZC3
                    Content-Disposition: attachment; ...
Headers           : {[Connection, keep-alive], [x-amz-id-2,
                    Dm59o9lYVx3X29/w1mo7kzlD6C65TDqLEIE9mM23Vs/dpX3qKuTR+jcxl7CM/Z6PcfcsCWT2Qg8=], [x-amz-request-id,
                    294YQYFG42T2MZC3], [Content-Disposition, attachment;
                    filename=baseline_15.0.1044.25.checksum.txt]...}
RawContentLength  : 66

LoadFromGitHub : C:\Users\Administrator\Desktop\baseline_15.0.516.30.zip not found... please open issue on
https://github.com/microsoft/CSS-Exchange/issues, we will work on it
At C:\Users\Administrator\Desktop\CompareExchangeHashes.ps1:613 char:13
+             LoadFromGitHub -url $zip_file_url -filename $zip_file -installed_ver ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,LoadFromGitHub`

**Comment by githubths** [comment]
Same Same issuer on Exchange 2013, the file (baseline_15.0.516.**30**.zip) are not on the latest Build list. Only the baseline_15.0.516.32.zip are there.

![image](https://user-images.githubusercontent.com/7395784/110621769-e3b26c80-819a-11eb-8d03-6dff6c0dc547.png)

**Comment by scottu-rhc** [comment]
Hi,

We are getting the same error. Strangely have two Exchange 2013 servers on 15.0.1497.2 and the other Exchange Server didn't ask for the baseline_15.0.516.30.zip file

[03/10/2021 15:39:55] Started...
Found exchange version: 15.0.1497.2
Loaded baseline for 15.0.1178.4, hashes number 7452
Loaded baseline for 15.0.1076.9, hashes number 7353
Loaded baseline for 15.0.1497.12, hashes number 7464
Loaded baseline for 15.0.1044.25, hashes number 7353
Loaded baseline for 15.0.1497.0, hashes number 7464
Can't find local baseline for 15.0.516.30
Downloading baseline file from GitHub to C:\temp\baseline_15.0.516.30.zip
LoadFromGitHub : C:\temp\baseline_15.0.516.30.zip not found... please open issue on
https://github.com/microsoft/CSS-Exchange/issues, we will work on it
At C:\TTA\CompareExchangeHashes.ps1:613 char:13
+             LoadFromGitHub -url $zip_file_url -filename $zip_file -installed_ver ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,LoadFromGitHub

**Comment by anshuldube** [comment]
We are working on getting the baseline for 15.0.516.30

**Comment by anshuldube** [comment]
Created a single task for tracking all missing baselines, please follow: https://github.com/microsoft/CSS-Exchange/issues/313
