### ISSUE TITLE
[Issue] Exchange Healthchecker: Exchange Server Membership: Unknown

### ISSUE THREAD

**Issue by wachtell** [microsoft/CSS-Exchange#2221]
**Describe the issue**
I run Exchange Healthchecker every day. However, I get a yellow error regarding Exchange Server membership. The error is not consistent and can be on one or more Exchange Servers.

**Script Output**
Exchange Server Membership: Unknown - Wasn't able to get the Computer Membership information

**Additional context**
Everything works correctly, and the event log has no real errors. Is this important or can I disregard the error?

Thank you in advance
Kris

**Comment by dpaulson45** [comment]
duplicate of #2110

**Comment by dpaulson45** [comment]
Closing, as this issue should be resolved with the PR #2229
