### ISSUE TITLE
[Issue]baseline_15.1.2176.2.zip not found...

### ISSUE THREAD

**Issue by alexanderkhokhlov** [microsoft/CSS-Exchange#224]
**Describe the issue**
A clear and concise description of what the issue is, including what script you are seeing the error in.

**Expected behavior**

**Script Output**
If applicable, add the exception that you are seeing that wasn't handled.

**Additional context**

**Comment by psykokwak4** [comment]
released 16 minutes ago https://github.com/microsoft/CSS-Exchange/releases/download/v21.03.10.0544/baseline_15.1.2176.2.zip

**Comment by bill-long** [comment]
Closing this one, since that zip was released just before this issue was opened. Please let us know if you're still having trouble.
