### ISSUE TITLE
ExchangeMitigations.ps1[Issue]

### ISSUE THREAD

**Issue by thankappas** [microsoft/CSS-Exchange#227]
I tried to execute the script from a Powershell (run as administrator). : 
.\ExchangeMitigations.ps1  -WebSiteNames "Default Web Site" -ApplyAllMitigations -Verbose
I already installed the URL rewrite 2.0 (for IIS 8.5) before running this.

I am receiving  the following error:

Get-InstalledSoftware : Error: Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again. - Line Number: 255
At C:\temp\ExchangeMitigations.ps1:299 char:26
         $RewriteModule = Get-InstalledSoftware | Where-Object { $_.Na ...
                          ~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
     FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-InstalledSoftware

Environment:
 Exchange server 2013 CU13 on Windows 2012R2 (Powershell Version 5.1)

**Comment by mabdo01552** [comment]
I am facing the same issue.

**Comment by mabdo01552** [comment]
can anybody help us resolve this problem?

**Comment by dbacon247** [comment]
Looking into this now

**Comment by dbacon247** [comment]
@mabdo01552  are you also running 
Exchange server 2013 CU13 on Windows 2012R2 (Powershell Version 5.1)

**Comment by dbacon247** [comment]
Found the issue, we tested this script on several older systems even the ones mentioned here on various versions of PowerShell and for some reason on these test machines the function was working fine without passing the -name param.

**Comment by dbacon247** [comment]
@mabdo01552 the fix is going through the build pipeline right now, once it's complete you will be to download the new script like before. 

@bill-long  - any eta on when the the next release will be out?

**Comment by bill-long** [comment]
@mabdo01552 @dbacon247 This released about 25 minutes ago. Can you download the latest release and confirm? Thank you.

**Comment by Dannyvzon** [comment]
Stil the same problem:

![image](https://user-images.githubusercontent.com/59775607/110680228-9ce36780-81d8-11eb-87ca-ebc548846ba2.png)

**Comment by dbacon247** [comment]
@Dannyvzon  are you saying the new version you downloaded does not have this change? 

![image](https://user-images.githubusercontent.com/80121280/110683372-c8426400-8190-11eb-9a38-a9b9691bef9d.png)

**Comment by bill-long** [comment]
I sanity-checked the release file and that change is definitely there, though it's moved down to 335 due to the disclaimer:

![image](https://user-images.githubusercontent.com/4518572/110683721-f3817f00-81a1-11eb-8f93-c87ee10033c6.png)

However, 299, which is 281 in the source, still has the old syntax:

![image](https://user-images.githubusercontent.com/4518572/110683903-2c215880-81a2-11eb-99f4-0acb5c9a2ba4.png)

**Comment by bill-long** [comment]
We're talking about ExchangeMitigations.ps1, right? I didn't look at the old script. But that line 299 does match up with the error from @Dannyvzon 's screenshot.

**Comment by dbacon247** [comment]
@Dannyvzon  Nvm I see I missed one on line 257, just submitted PR with this change

**Comment by Dannyvzon** [comment]
@dbacon247 No problm mate! let me know when i can download again :)

**Comment by Dannyvzon** [comment]
@bill-long @dbacon247 Script is working!

Note: If you use the download link in the discription you still get the old ps1. Downloaded the whole Css-Echange-main zip and now i got the correct one with the changes

Nmap scanning not showing Vulnerabilities anymore

**Comment by dbacon247** [comment]
@Dannyvzon  the link points to the latest release, looks like it was updated 26 minutes ago. I just downloaded the latest version and it has the new changes in it. Should be good to go now.

**Comment by mabdo01552** [comment]
The script is working with me now .

Thanks,

**Comment by dbacon247** [comment]
> The script is working with me now .
> 
> Thanks,

Great!

**Comment by dbacon247** [comment]
@thankappas  - looks like the script is working now for those who were running into this issue, can you confirm?

**Comment by thankappas** [comment]
> @thankappas - looks like the script is working now for those who were running into this issue, can you confirm?

Yes i confirm it works! Thank you
