### ISSUE TITLE
"Get-FileHash" not found...

### ISSUE THREAD

**Issue by DuncanMacLeod-WotU** [microsoft/CSS-Exchange#228]
Processing 3 directories in parallel
Die Benennung "Get-FileHash" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines
ausführbaren Programms erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern
enthalten), und wiederholen Sie den Vorgang.
In C:\Users\Administrator\Downloads\CompareExchangeHashes.ps1:481 Zeichen:13
+             $res = Receive-Job $job.ID
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-FileHash:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
    + PSComputerName        : localhost

**Comment by GitCoastn** [comment]
We had a customer with the same issue, there is a workaround without updating powershell:
Open the script and replace the two occurences of ...

`$hash = $f | Get-FileHash -ErrorAction SilentlyContinue`

... with the following lines ...

```
if (Get-Command "Get-FileHash" -errorAction SilentlyContinue){
    $hash = $f | Get-FileHash -ErrorAction SilentlyContinue
}
else {
    $certutilout = certutil.exe -hashfile $f.FullName SHA256
    if ($certutilout[1] -like "CertUtil:*"){
        $hash = $null
    }
    else{
        $hash = $certutilout[1].ToUpper()
    }
}
```
I'm not used to github, but maybe some officials can implement this snippet. Performance-wise it would be even better to do an initial check for the command and write the result to a boolean, which would then be queried on call.

**Comment by DuncanMacLeod-WotU** [comment]
> We had a customer with the same issue, there is a workaround without updating powershell:
> Open the script and replace the two occurences of ...
> 
> `$hash = $f | Get-FileHash -ErrorAction SilentlyContinue`
> 
> ... with the following lines ...
> 
> ```
> if (Get-Command "Get-FileHash" -errorAction SilentlyContinue){
>     $hash = $f | Get-FileHash -ErrorAction SilentlyContinue
> }
> else {
>     $certutilout = certutil.exe -hashfile "$f.FullName" SHA256
>     if ($certutilout[1] -like "CertUtil:*"){
>         $hash = $null
>     }
>     else{
>         $hash = $certutilout[1].ToUpper()
>     }
> }

Just edited the file, code-signed it with my own certificate ;-) and just started it. Currently running on my Exchange as I am writing these lines. BIG THANK YOU :-) !!

**Comment by anshuldube** [comment]
This is fixed.
