### ISSUE TITLE
[Issue]baseline_15.2.721.13.checksum.txt not found

### ISSUE THREAD

**Issue by DLA2EX** [microsoft/CSS-Exchange#229]
\baseline_15.2.721.13.checksum.txt not found... please open issue on https://github.com/microsoft/CSS-Exchange/issues, we will work on it

baseline_15.2.721.2.checksum.txt not found...
baseline_15.2.595.3.zip not found...
baseline_15.2.397.3.checksum.txt not found...

Thanks for your help.

**Comment by psykokwak4** [comment]
please retry with the latest released scirpt: https://github.com/microsoft/CSS-Exchange/releases/download/v21.03.10.1625/CompareExchangeHashes.ps1

**Comment by anshuldube** [comment]
this baseline is now available, can you please retry?

**Comment by DLA2EX** [comment]
Hello,

All are good now.
Thank you.



Cordialement,
Didier

Stay safe and healthy ! ***@***.***D71716.B644A3B0]

***@***.***D71716.B644A3B0]
6, rue Ménars – 75002 Paris
Direct Line : +33 1 42 99 50 55
