### ISSUE TITLE
[Issue] Zip not found

### ISSUE THREAD

**Issue by JiveLive** [microsoft/CSS-Exchange#230]
**Describe the issue**
Can't find local baseline for ...
Downloading baseline file from GitHub to C:\Users\administrator\baseline_....zip
LoadFromGitHub : C:\Users\administrator\baseline_....zip not found... please open issue on https://github.com/microsoft/CSS-Exchange/issues, we will work on it
At C:\Users\administrator\CompareExchangeHashes(1).ps1:613 char:13
+             LoadFromGitHub -url $zip_file_url -filename $zip_file -in ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,LoadFromGitHub

**Comment by psykokwak4** [comment]
```
Downloading baseline file from GitHub to C:\Users\administrator\baseline_....zip
```
please provide the exact version (not dotdotdot) we need to prepare

**Comment by JiveLive** [comment]
Is there a different way to run it, or a log somewhere I can pull the exact error from?

**Comment by anshuldube** [comment]
You could try:
Start-Transcript 
.\CompareExchangeHashes.ps1
Stop-Transcript

The Start-Transcript will output a file name, you could share the contents of the file.

**Comment by JiveLive** [comment]
Appears to be truncated still.

Loaded baseline for 15.1.2176.2, hashes number 15237
Can't find local baseline for ...
Downloading baseline file from GitHub to C:\Users\administrator.DREES\baseline_....zip
PS C:\Users\administrator.DREES> TerminatingError(Invoke-WebRequest): "Not Found"
>> TerminatingError(LoadFromGitHub): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: C:\Users\administrator.DREES\baseline_....zip not found... please open issue on https://github.com/microsoft/CSS-Exchange/issues, we will work on it"
>> TerminatingError(LoadFromGitHub): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: C:\Users\administrator.DREES\baseline_....zip not found... please open issue on https://github.com/microsoft/CSS-Exchange/issues, we will work on it"
>> TerminatingError(LoadFromGitHub): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: C:\Users\administrator.DREES\baseline_....zip not found... please open issue on https://github.com/microsoft/CSS-Exchange/issues, we will work on it"
>> TerminatingError(LoadFromGitHub): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: C:\Users\administrator.DREES\baseline_....zip not found... please open issue on https://github.com/microsoft/CSS-Exchange/issues, we will work on it"
>> TerminatingError(LoadFromGitHub): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: C:\Users\administrator.DREES\baseline_....zip not found... please open issue on https://github.com/microsoft/CSS-Exchange/issues, we will work on it"
>> TerminatingError(LoadFromGitHub): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: C:\Users\administrator.DREES\baseline_....zip not found... please open issue on https://github.com/microsoft/CSS-Exchange/issues, we will work on it"
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: C:\Users\administrator.DREES\baseline_....zip not found... please open issue on https://github.com/microsoft/CSS-Exchange/issues, we will work on it
LoadFromGitHub : C:\Users\administrator.DREES\baseline_....zip not found... please open issue on https://github.com/microsoft/CSS-Exchange/issues, we will work on it
At C:\Users\administrator.DREES\CompareExchangeHashes.ps1:613 char:13
+             LoadFromGitHub -url $zip_file_url -filename $zip_file -in ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,LoadFromGitHub

PS C:\Users\administrator.DREES> Stop-Transcript
**********************
Windows PowerShell transcript end
End time: 20210310115636
**********************

**Comment by psykokwak4** [comment]
could you also copy the below 2 blocks in powershell, and give us result for `FindInstalledVersions`?

https://github.com/microsoft/CSS-Exchange/blob/d95e5e70a17a8baaa3661c507a32418f044091d5/Security/CompareExchangeHashes.ps1#L119-L271
https://github.com/microsoft/CSS-Exchange/blob/d95e5e70a17a8baaa3661c507a32418f044091d5/Security/CompareExchangeHashes.ps1#L536-L568

**Comment by JiveLive** [comment]
I'm sorry, I'm not sure what you are asking me to do.  I'm on Version 15.1 ‎(Build 2176.2)‎ Hybrid Deployment

**Comment by anshuldube** [comment]
Do you have internet connectivity on this server?

**Comment by JiveLive** [comment]
I do, yes.

**Comment by anshuldube** [comment]
Can you open the script and share the version, it would look something like:
# Version 21.03.10.0536
We suspect that we are missing baselines for one of the versions you have on the machine, so if you could copy the below (what my colleague also shared above) into powershell and let us know the output we will know a bit more:

`$VALID_VERSIONS = @{ ` 
         # E19 
         '15.2.858.5'   = $true; ` 
         '15.2.792.5'   = $true; ` 
         '15.2.792.3'   = $true; ` 
         '15.2.721.13'  = $true; ` 
         '15.2.792.10'  = $true; ` 
         '15.2.721.8'   = $true; ` 
         '15.2.721.6'   = $true; ` 
         '15.2.721.4'   = $true; ` 
         '15.2.721.3'   = $true; ` 
         '15.2.721.2'   = $true; ` 
         '15.2.659.11'  = $true; ` 
         '15.2.659.8'   = $true; ` 
         '15.2.659.7'   = $true; ` 
         '15.2.659.6'   = $true; ` 
         '15.2.659.4'   = $true; ` 
         '15.2.595.6'   = $true; ` 
         '15.2.595.3'   = $true; ` 
         '15.2.529.11'  = $true; ` 
         '15.2.529.5'   = $true; ` 
         '15.2.464.5'   = $true; ` 
         '15.2.397.3'   = $true; ` 
         '15.2.330.5'   = $true; ` 
         '15.2.221.12'  = $true; ` 
         '15.2.196.0'   = $true; ` 
  
     #E16 
     '15.1.2242.4'      = $true; ` 
         '15.1.2176.9'  = $true; ` 
         '15.1.2176.4'  = $true; ` 
         '15.1.2176.2'  = $true; ` 
         '15.1.2106.13' = $true; ` 
         '15.1.2106.8'  = $true; ` 
         '15.1.2106.6'  = $true; ` 
         '15.1.2106.4'  = $true; ` 
         '15.1.2106.3'  = $true; ` 
         '15.1.2106.2'  = $true; ` 
         '15.1.2044.12' = $true; ` 
         '15.1.2044.8'  = $true; ` 
         '15.1.2044.7'  = $true; ` 
         '15.1.2044.6'  = $true; ` 
         '15.1.2044.4'  = $true; ` 
         '15.1.1979.6'  = $true; ` 
         '15.1.1979.3'  = $true; ` 
         '15.1.1913.10' = $true; ` 
         '15.1.1913.7'  = $true; ` 
         '15.1.1913.5'  = $true; ` 
         '15.1.1847.10' = $true; ` 
         '15.1.1847.7'  = $true; ` 
         '15.1.1847.5'  = $true; ` 
         '15.1.1847.3'  = $true; ` 
         '15.1.1779.2'  = $true; ` 
         '15.1.1713.5'  = $true; ` 
         '15.1.1591.10' = $true; ` 
         '15.1.1531.3'  = $true; ` 
         '15.1.1466.3'  = $true; ` 
         '15.1.1415.2'  = $true; ` 
         '15.1.1261.35' = $true; ` 
         '15.1.1034.33' = $true; ` 
         '15.1.1034.26' = $true; ` 
         '15.1.845.34'  = $true; ` 
         '15.1.669.32'  = $true; ` 
         '15.1.544.27'  = $true; ` 
         '15.1.466.34'  = $true; ` 
         '15.1.396.30'  = $true; ` 
         '15.1.225.42'  = $true; ` 
         '15.1.225.16'  = $true; ` 
  
     #E13 
     '15.0.1497.12'     = $true; ` 
         '15.0.1497.10' = $true; ` 
         '15.0.1497.8'  = $true; ` 
         '15.0.1497.7'  = $true; ` 
         '15.0.1497.6'  = $true; ` 
         '15.0.1497.4'  = $true; ` 
         '15.0.1497.3'  = $true; ` 
         '15.0.1497.2'  = $true; ` 
         '15.0.1497.0'  = $true; ` 
         '15.0.1473.5'  = $true; ` 
         '15.0.1473.4'  = $true; ` 
         '15.0.1473.3'  = $true; ` 
         '15.0.1395.10' = $true; ` 
         '15.0.1395.8'  = $true; ` 
         '15.0.1395.7'  = $true; ` 
         '15.0.1395.6'  = $true; ` 
         '15.0.1395.4'  = $true; ` 
         '15.0.1367.9'  = $true; ` 
         '15.0.1367.6'  = $true; ` 
         '15.0.1367.3'  = $true; ` 
         '15.0.1365.7'  = $true; ` 
         '15.0.1365.1'  = $true; ` 
         '15.0.1347.5'  = $true; ` 
         '15.0.1347.3'  = $true; ` 
         '15.0.1347.2'  = $true; ` 
         '15.0.1320.4'  = $true; ` 
         '15.0.1293.2'  = $true; ` 
         '15.0.1263.5'  = $true; ` 
         '15.0.1236.3'  = $true; ` 
         '15.0.1210.3'  = $true; ` 
         '15.0.1178.4'  = $true; ` 
         '15.0.1156.6'  = $true; ` 
         '15.0.1130.10' = $true; ` 
         '15.0.1130.7'  = $true; ` 
         '15.0.1104.5'  = $true; ` 
         '15.0.1076.9'  = $true; ` 
         '15.0.1044.25' = $true; ` 
         '15.0.995.29'  = $true; ` 
         '15.0.913.22'  = $true; ` 
         '15.0.847.32'  = $true; ` 
         '15.0.775.38'  = $true; ` 
         '15.0.712.24'  = $true; ` 
         '15.0.620.29'  = $true; ` 
         '15.0.516.32'  = $true; ` 
         '15.0.516.30'  = $true; ` 
  
     #E10 
     '14.3.513.0'       = $true; ` 
         '14.3.509.0'   = $true; ` 
         '14.3.496.0'   = $true; ` 
         '14.3.468.0'   = $true; ` 
         '14.3.461.1'   = $true; ` 
         '14.3.452.0'   = $true; ` 
         '14.3.442.0'   = $true; ` 
         '14.3.435.0'   = $true; ` 
         '14.3.419.0'   = $true; ` 
         '14.3.417.1'   = $true; ` 
         '14.3.411.0'   = $true; ` 
         '14.3.399.2'   = $true; ` 
         '14.3.389.1'   = $true; ` 
         '14.3.382.0'   = $true; ` 
         '14.3.361.1'   = $true; ` 
         '14.3.352.0'   = $true; ` 
         '14.3.336.0'   = $true; ` 
         '14.3.319.2'   = $true; ` 
         '14.3.301.0'   = $true; ` 
         '14.3.294.0'   = $true; ` 
         '14.3.279.2'   = $true; ` 
         '14.3.266.2'   = $true; ` 
         '14.3.248.2'   = $true; ` 
         '14.3.235.1'   = $true; ` 
         '14.3.224.2'   = $true; ` 
         '14.3.224.1'   = $true; ` 
         '14.3.210.2'   = $true; ` 
         '14.3.195.1'   = $true; ` 
         '14.3.181.6'   = $true; ` 
         '14.3.174.1'   = $true; ` 
         '14.3.169.1'   = $true; ` 
         '14.3.158.1'   = $true; ` 
         '14.3.146.0'   = $true; ` 
         '14.3.123.4'   = $true; ` 
  
 } 
 
 function FindInstalledVersions() { 
     $VDIR_PATTERN = New-Object System.Text.RegularExpressions.Regex -ArgumentList  '(.+)\s+\"(.+)\"\s+\(physicalPath:(.+)\)' 
  
     $versions = @{} 
  
     Add-PSSnapin -Name "Microsoft.Exchange.Management.PowerShell.E2010" -ErrorAction SilentlyContinue 
     $server = (Get-ExchangeServer) | Where-Object { $_.Identity.Name -eq (hostname) } 
     if ($server.AdminDisplayVersion.Major -eq 14) { 
         $exchange_version = (Get-Command ExSetup | ForEach-Object { $_.FileVersionInfo }).ProductVersion 
     } else { 
         $exchange_version = "$($server.AdminDisplayVersion.Major).$($server.AdminDisplayVersion.Minor).$($server.AdminDisplayVersion.Build).$($server.AdminDisplayVersion.Revision)" 
     } 
  
     Remove-PSSnapin -Name "Microsoft.Exchange.Management.PowerShell.E2010" -ErrorAction SilentlyContinue 
  
     $versions[$exchange_version] = $true 
     $vdir_paths = @() 
     $logs = & (Join-Path $env:Windir "system32\inetsrv\appcmd.exe") LIST VDIRS | Sort-Object 
  
     foreach ($log in $logs) { 
         $log -match $VDIR_PATTERN | Out-Null; 
         $vdir_physical_path = $Matches[3] 
         $vdir_physical_path = $vdir_physical_path -replace "%SystemDrive%", $env:SystemDrive 
         $vdir_physical_path = $vdir_physical_path -replace "%windir%", $env:windir 
  
         # note: some vdirs share same physical paths 
         $vdir_paths += $vdir_physical_path 
     } 
  
     $vdir_paths | Where-Object { Test-Path $_ } | ForEach-Object { Get-ChildItem -Directory -Path $_ } | Where-Object { $VALID_VERSIONS[$_.Name] -eq $true } | ForEach-Object { $versions[$_.Name] = $true } 
  
     return $exchange_version, $versions.Keys 
 } 
 
 FindInstalledVersions
 
 
 
 `

**Comment by JiveLive** [comment]
# Version 21.03.10.0536

**Comment by JiveLive** [comment]
Is there somewhere I can manually download the baselines?  I had this error when I tried to run it yesterday, however it seemed to move past the error.

**Comment by anshuldube** [comment]
We have all the baselines available for download here: https://github.com/microsoft/CSS-Exchange/releases/latest
However, with the truncated output we are not able to tell which versions you could download. 
If you run the part of the script to find installed versions, we would be able to tell, let us know if you are still having trouble trying to run it?

**Comment by JiveLive** [comment]
How do I do that?  I tried to copy it and run it but it just displays the code and goes back to a prompt.  When I tried to do the logging everything still shows as "..." the version, and the baseline file show that.

**Comment by JiveLive** [comment]
I tried running it directly in the Exchange management shell, and it moved passed the error, shows exchange version 15.1.2176.2 and loaded three baselines 15.1.  1779.2, 2176.9, & 2176.2

**Comment by JiveLive** [comment]
Thanks for all the help yesterday!    Any update on the 1779.2 baselines being loaded?

**Comment by anshuldube** [comment]
Created a single task for tracking all missing baselines, please follow: https://github.com/microsoft/CSS-Exchange/issues/313
