### ISSUE TITLE
[Issue] "Done. One or more potentially malicious files found, please inspect the result file" - FALSE NEGATIVE?

### ISSUE THREAD

**Issue by Sektorsync** [microsoft/CSS-Exchange#232]
Hello Exchange Team!

We ran the script "CompareExchangeHashes.ps1" as described below

As our Exchange Servers may not conenct to "https://github.com/" due to firewall restrictions, I downloaded all baseline files before.

===============================================
\CompareExchangeHashes.ps1
[03/10/2021 12:47:16] Started...
Found exchange version: 15.2.721.2
Loaded baseline for 15.2.659.6, hashes number 15196
Loaded baseline for 15.2.721.13, hashes number 15196
Loaded baseline for 15.2.721.2, hashes number 15138
Loaded baseline for 15.2.659.4, hashes number 15138
BaselineData - 15.2.659.6 15.2.721.13 15.2.721.2 15.2.659.4 15.2.721.2
Processing 3 directories in parallel
Processing 3 directories in parallel
Processing 3 directories in parallel
Processing 3 directories in parallel
Processing 3 directories in parallel
Processing 3 directories in parallel
Processing 4 directories in parallel
Processing 4 directories in parallel
Processing 4 directories in parallel
Processing 4 directories in parallel
Comparison complete. Writing results.
Exporting  objects to results
        Submitting files for analysis:
        Please submit the output file for analysis in the malware analysis portal
        in the link below. Please add the text 'ExchangeMarchCVE' in
        'Additional Information' field on the portal submission form.
        https://www.microsoft.com/en-us/wdsi/filesubmission
        Instructions on how to use the portal can be found here:
        https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/submission-guide
Exported results to .\15.2.721.2_result.csv
[03/10/2021 13:00:05] Done. One or more potentially malicious files found, please inspect the result file. ExchangeVersion: 15.2.721.2 OSVersion: 10.0.17763.0 ScriptVersion: 21.03.10.0536
===============================================

The files reported as potentially malicious  are

LastAccessTimeUtc,"PDir","FileName","LastWriteTimeUtc","Error","FileHash","FilePath","CreationTimeUtc","VDir"
18.06.2020 07:01:47,"C:\inetpub\wwwroot","iisstart.png","18.06.2020 07:01:47","Suspicious","","C:\inetpub\wwwroot\iisstart.png","18.06.2020 07:01:48","Default Web Site/"
11.10.2020 08:14:12,"C:\inetpub\wwwroot","web.config","11.10.2020 08:14:12","Suspicious","","C:\inetpub\wwwroot\web.config","11.10.2020 08:14:12","Default Web Site/"
11.10.2020 08:14:12,"C:\inetpub\wwwroot","web.config.bak","03.09.2020 08:45:43","Suspicious","","C:\inetpub\wwwroot\web.config.bak","10.07.2020 16:39:27","Default Web Site/"
18.06.2020 07:01:47,"C:\inetpub\wwwroot","iisstart.htm","18.06.2020 07:01:47","Suspicious","","C:\inetpub\wwwroot\iisstart.htm","18.06.2020 07:01:48","Default Web Site/"

I uploaded the file ".\15.2.721.2_result.csv" to "https://www.microsoft.com/en-us/wdsi/filesubmission", but there have no vulnerabilities been found in the four files listed in this csv.

The mentioned files are just .config, .htm and .png files.

Maybe this is a FALSE POSITIVE?

**Comment by psykokwak4** [comment]
script marks any file created after Dec 01 2020 under `$env:SystemDrive\inetpub\wwwroot` as suspicious https://github.com/microsoft/CSS-Exchange/blob/d95e5e70a17a8baaa3661c507a32418f044091d5/Security/CompareExchangeHashes.ps1#L335,
https://github.com/microsoft/CSS-Exchange/blob/d95e5e70a17a8baaa3661c507a32418f044091d5/Security/CompareExchangeHashes.ps1#L377

probably because your system's default date time format is not MM/dd/yyyy which is the format script assumes 

we will have it addressed, meanwhile, please change https://github.com/microsoft/CSS-Exchange/blob/d95e5e70a17a8baaa3661c507a32418f044091d5/Security/CompareExchangeHashes.ps1#L273 as something like below:
```ps
$MARK_AS_SUSPICIOUS_FROM = (Get-Date -Date "12/01/2020" -Format "MM/dd/yyyy")
```

**Comment by psykokwak4** [comment]
also, currently the script blindly marks files recently changed under `$env:SystemDrive\inetpub\wwwroot` as suspicious, it only has capability to compare local file hashes against known good file hashes published in github

**Comment by psykokwak4** [comment]
closing it since this script is deprecated
