### ISSUE TITLE
[Issue] Can't find local baseline for 15.0.516.30

### ISSUE THREAD

**Issue by Dannyvzon** [microsoft/CSS-Exchange#247]
[03/10/2021 20:11:54] Started...
Found exchange version: 15.0.1263.5
Loaded baseline for 15.0.847.32, hashes number 6825
Can't find local baseline for 15.0.516.30
Downloading baseline file from GitHub to C:\tmp\baseline_15.0.516.30.zip
LoadFromGitHub : C:\tmp\baseline_15.0.516.30.zip not found... please open issue on https://github.com/microsoft/CSS-Exc
hange/issues, we will work on it
At C:\tmp\CompareExchangeHashes.ps1:613 char:13
+             LoadFromGitHub -url $zip_file_url -filename $zip_file -in ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,LoadFromGitHub

**Comment by anshuldube** [comment]
Tracked by: https://github.com/microsoft/CSS-Exchange/issues/222
