### ISSUE TITLE
No  baseline_15.0.516.30.zip found [Issue]

### ISSUE THREAD

**Issue by ProfBeefer** [microsoft/CSS-Exchange#254]
no zip for this baseline number which results in the following error: 

LoadFromGitHub : C:\users\nsoadmin\desktop\Hashes\baseline_15.0.516.30.zip not found... please open issue on
https://github.com/microsoft/CSS-Exchange/issues, we will work on it
At C:\users\nsoadmin\desktop\Hashes\CompareExchangeHashes.ps1:613 char:13
+             LoadFromGitHub -url $zip_file_url -filename $zip_file -installed_ver ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,LoadFromGitHub

**Comment by anshuldube** [comment]
Tracked by: https://github.com/microsoft/CSS-Exchange/issues/222
