### ISSUE TITLE
baseline_15.0.516.30.zip not found

### ISSUE THREAD

**Issue by fadyibra** [microsoft/CSS-Exchange#259]
LoadFromGitHub : C:\Engineer\CompareExchangeHashes\baseline_15.0.516.30.zip not found... please open issue on
https://github.com/microsoft/CSS-Exchange/issues, we will work on it
At C:\Engineer\CompareExchangeHashes\CompareExchangeHashes.ps1:636 char:13
+             LoadFromGitHub -url $zip_file_url -filename $zip_file -installed_ver ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,LoadFromGitHub

**Comment by anshuldube** [comment]
Tracked with this: https://github.com/microsoft/CSS-Exchange/issues/222
