### ISSUE TITLE
Environmental Variable compared to SharedWebConfig

### ISSUE THREAD

**Issue by johage** [microsoft/CSS-Exchange#261]
Compare the System Variable configuration for the %ExchangeInstallPath% where we'd normally see:
  C:\Program Files\Microsoft\Exchange Server\V15\
And then compare this against the SharedWebConfig files that can be found in these directories:
  FE - "C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\SharedWebConfig.config"
  BE - "C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\SharedWebConfig.config"

Where we would see these types of entries that can become corrupted during a bad install attempt:
```
  // Good
    <codeBase version="15.0.0.0" href="file:///C:\Program Files\Microsoft\Exchange Server\V15\bin\BigFunnel.BondTypes.dll" />

  /// Bad
    <codeBase version="15.0.0.0" href="file:///%ExchangeInstallDir%\BigFunnel.BondTypes.dll" />
OR
    <codeBase version="15.0.0.0" href="file:///C:\\Program Files\Microsoft\Exchange Server\V15\bin\BigFunnel.BondTypes.dll" />
```

**Comment by bill-long** [comment]
This looks like a feature request for SetupAssist?

**Comment by dpaulson45** [comment]
Going to be creating a post install script 

- Checks for this
- Missing DLLS
- Copy over the DLLs from ISO if missing

**Comment by dpaulson45** [comment]
I am thinking we should just add this particular check into the Health Checker. Search for all config files under `V15\FrontEnd\` and `V15\ClientAccess\` and check to see if they have a string of `%ExchangeInstallDir%`.

@bill-long @johage thoughts?

**Comment by johage** [comment]
Depends upon if you're going to make it public to the user running it or not. If we're missing DLLs but nothing is "broken" are we going to immediately recommend they use the CopyMissingDLL script?

I like the idea of getting out ahead of things but just want to be sure we know how we're going to handle it.

Thanks,

Josh Hagen
Exchange Technical Advisor
Tier 3 Business hours: 8:00AM-8:00PM Central
Microsoft Exchange On-Premise
701.492.6842
Working hours: Monday-Friday 7:00-4:00PM Central

I am committed to providing excellent service and I value your feedback. I welcome comments about what I did right, as well as suggestions for how I can continue to improve my service in the future. Microsoft is committed to providing world-class service, so your input regarding the entire support process is highly valued. Please send your comments to me or my manager Heidi Triplett at ***@***.******@***.***>

Exchange 2010 has hit End of Life as of October 13, 2020 please review this link if you have questions about this - https://docs.microsoft.com/en-us/microsoft-365/enterprise/exchange-2010-end-of-support?view=o365-worldwide

**Comment by dpaulson45** [comment]
No, not going to check for missing DLLs as that would be a large mess to include in the Health Checker. The original task/ask of just checking for the environment variable. 

the other things I was thinking of isn't going to occur at this point in time.

**Comment by johage** [comment]
Then I say go for it so we know if things are missing even if it's not causing any issues.

Thanks,

Josh Hagen
Exchange Technical Advisor
Tier 3 Business hours: 8:00AM-8:00PM Central
Microsoft Exchange On-Premise
701.492.6842
Working hours: Monday-Friday 7:00-4:00PM Central

I am committed to providing excellent service and I value your feedback. I welcome comments about what I did right, as well as suggestions for how I can continue to improve my service in the future. Microsoft is committed to providing world-class service, so your input regarding the entire support process is highly valued. Please send your comments to me or my manager Heidi Triplett at ***@***.******@***.***>

Exchange 2010 has hit End of Life as of October 13, 2020 please review this link if you have questions about this - https://docs.microsoft.com/en-us/microsoft-365/enterprise/exchange-2010-end-of-support?view=o365-worldwide
