### ISSUE TITLE
[Work Item] Detect Extra files in CompareExchangeHashes.ps1

### ISSUE THREAD

**Issue by vboyev-MSFT** [microsoft/CSS-Exchange#263]
**Describe the work**
Presently - the script validates default files in Exchange VDIRS.  However - if I were to create a net new file - like "webshell.aspx " and place it in the vdir path - it is not surfaced as an extra file and suspicious/extraneous 

**Additional Context**
 
What it did not pick up was the extra file a manually placed in the VDIR: 
 
![image](https://user-images.githubusercontent.com/28322607/110719510-97831e80-81d2-11eb-8ea1-7eca78685bba.png)

**Comment by psykokwak4** [comment]
should be fixed in the next release (curr v21.03.10.2314)

**Comment by psykokwak4** [comment]
actually, what's your script version and the absolute path of chinachopper.aspx?
also it would be great if you can share vdir paths (`$logs=c:\windows\system32\inetsrv\appcmd.exe LIST VDIRS | clip`)
can't reproduce using current release (`v21.03.10.2314`)

**Comment by vboyev-MSFT** [comment]
absolute path for the chinachopper.aspx was default c:\program files\microsoft\exchange\v15\frontend\httpproxy\owa\chinachopper.aspx  
Vanilla Ex2016 installation all defaults on Server 2012R2

I will try latest and see if repro....not sure which version the script was...

**Comment by psykokwak4** [comment]
![image](https://user-images.githubusercontent.com/6261280/110857482-c3071700-826d-11eb-9899-ca809fadcc98.png)
what's the version embedded in your script?

**Comment by psykokwak4** [comment]
let me know if you want to setup as session or something since you're from MSFT

**Comment by psykokwak4** [comment]
(after sync) I think it is expected, so your issue is:

1. you have created multiple empty files on your lab. chinachopper.aspx is just one of them
2. we have empty files in baseline
3. all empty files have the same hash (`E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855`)

--> nothing got reported

let us know if that's not the case
