### ISSUE TITLE
[Issue] Is ExchangeMitigations.ps1 implemented for Exchange 2010? 

### ISSUE THREAD

**Issue by k-watanabetaf** [microsoft/CSS-Exchange#267]
I executed ExchangeMitigations.ps1 on Exchange Server 2010 and I have error message.
I read this guide on https://github.com/microsoft/CSS-Exchange/tree/main/Security
This script provides a mechanism for malicious file detection on Exchange servers running E13, E16 or E19 versions.

Do I need to run this command in Exchange 2010? Or should I ignore it? 

Get-Service : Cannot find any service with service name 'MSExchangeHM'.
At C:\temp\0311Script\ExchangeMitigations.ps1:575 char:21
+     $MSExchangeHM = Get-Service MSExchangeHM
+                     ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (MSExchangeHM:String) [Get-Service], ServiceCommandException
    + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.GetServiceCommand

**Comment by dbacon247** [comment]
Hey @k-watanabetaf the only mitigation that applies to Exchange 2010 is the Unified Messaging mitigation which simply turns off Unified messaging on your Exchange servers.

For more information on the vulnerabilities and mitigation's please visit https://aka.ms/exchangevulns

**Comment by k-watanabetaf** [comment]
Thank you, I got it
