### ISSUE TITLE
No baseline_15.1.1591.8.zip in repository

### ISSUE THREAD

**Issue by nelsonfnunes** [microsoft/CSS-Exchange#270]
Hello,

I'm trying to run the CompareExchangeHashes.ps1 on my exchange server but I am getting the below error.

Found exchange version: 15.1.2176.2
Can't find local baseline for 15.1.1591.8
Downloading baseline file from GitHub to C:\temp\HAFNIUM\baseline_15.1.1591.8.zip
LoadFromGitHub : C:\temp\HAFNIUM\baseline_15.1.1591.8.zip not found... please open issue on
https://github.com/microsoft/CSS-Exchange/issues, we will work on it

I manually checked the assets in https://github.com/microsoft/CSS-Exchange/releases/tag/v15.1.1591.8 but there is no baseline_15.1.1591.8.zip only baseline_15.1.1591.10.zip. Can you please look at adding this baseline?

Best regards
Nelson

**Comment by anshuldube** [comment]
The baseline is now available, can you re-try?

**Comment by nelsonfnunes** [comment]
tanks you
