### ISSUE TITLE
Problem with URL Rewrite

### ISSUE THREAD

**Issue by cyrakuse** [microsoft/CSS-Exchange#278]
When i execute ExchangeMitiggations.ps1 i have an error :
![image](https://user-images.githubusercontent.com/3593751/110769828-e7a4c400-8258-11eb-9987-4f5c67101d05.png)

The log file doesn't contain error. It say "configuration done"

**Comment by ghislaingaillot** [comment]
Same here, it seems to be related to the plugin language (FR).

**Comment by dbacon247** [comment]
Can you guys send me the specs of you the server that's hitting this problem? 
From systeminfo
OS Name:
OS Version:
System Type:

From $PSVersionTable
PSVersion:

From Exchange Management Shell (Get-ExchangeServer | fl *admin*)
Exchange Version:

The name of the url rewrite module your using

Thanks!

**Comment by dbacon247** [comment]
Found the issue easy fix just need to change the -Name param  to *IIS* and it should find it. 

![image](https://user-images.githubusercontent.com/80121280/110821724-347e9f80-8245-11eb-94ae-2ef01227809f.png)

**Comment by dbacon247** [comment]
@cyrakuse and @ghislaingaillot  can you download the latest version of the script and confirm if it's working? Thanks!

**Comment by cyrakuse** [comment]
The script has been executed correctly but after ECP isn't accessible. We obtain error 503 with the URL : https://localhost/ecp/?ExchClientVer=15

**Comment by ghislaingaillot** [comment]
I tried to run the new version but it thrown an error:
`[PS] C:\Users\ADMINACCOUNT\Downloads>.\ExchangeMitigations.ps1 -FullPathToMSI "C:\Users\ADMINACCOUNT\Downloads\rewrite_2.0_rtw_x64.msi" -WebSiteNames "Default Web Site" -ApplyA
llMitigations

Voulez-vous exécuter le logiciel de cet éditeur non approuvé ?
Le fichier C:\Users\ADMINACCOUNT\Downloads\ExchangeMitigations.ps1 est publié par CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US et n'est pas approuvé
sur votre système. N'exécutez que des scripts provenant d'éditeurs approuvés.
[M] Ne jamais exécuter  [N] Ne pas exécuter  [O] Exécuter une fois  [T] Toujours exécuter  [?] Aide (la valeur par défaut est « N ») : O
COMMENTAIRES : [INFO] Installing IIS URL Rewrite Module 2


name                  : X-AnonResource-Backend Abort - inbound
enabled               : True
patternSyntax         : ECMAScript
stopProcessing        : False
match                 : Microsoft.IIs.PowerShell.Framework.ConfigurationElement
conditions            : Microsoft.IIs.PowerShell.Framework.ConfigurationElement
serverVariables       : Microsoft.IIs.PowerShell.Framework.ConfigurationElement
action                : Microsoft.IIs.PowerShell.Framework.ConfigurationElement
PSPath                : MACHINE/WEBROOT/APPHOST/Default Web Site
Location              :
ConfigurationPathType : Location
ItemXPath             : /system.webServer/rewrite/rules/rule[@name='X-AnonResource-Backend Abort - inbound']
Attributes            : {name, enabled, patternSyntax, stopProcessing}
ChildElements         : {match, conditions, serverVariables, action}
ElementTagName        : rule
Methods               :
Schema                : Microsoft.IIs.PowerShell.Framework.ConfigurationElementSchema

name                  : X-BEResource Abort - inbound
enabled               : True
patternSyntax         : ECMAScript
stopProcessing        : True
match                 : Microsoft.IIs.PowerShell.Framework.ConfigurationElement
conditions            : Microsoft.IIs.PowerShell.Framework.ConfigurationElement
serverVariables       : Microsoft.IIs.PowerShell.Framework.ConfigurationElement
action                : Microsoft.IIs.PowerShell.Framework.ConfigurationElement
PSPath                : MACHINE/WEBROOT/APPHOST/Default Web Site
Location              :
ConfigurationPathType : Location
ItemXPath             : /system.webServer/rewrite/rules/rule[@name='X-BEResource Abort - inbound']
Attributes            : {name, enabled, patternSyntax, stopProcessing}
ChildElements         : {match, conditions, serverVariables, action}
ElementTagName        : rule
Methods               :
Schema                : Microsoft.IIs.PowerShell.Framework.ConfigurationElementSchema

Le démarrage d'une commande sur le serveur distant a échoué avec le message d'erreur suivant:
[ClientAccessServer=exchangeServerName,BackEndServer=exchangeServerName.domain.tld,RequestId=a60dcde1-6998-4824-9fa8-2573326a7ffb,TimeStamp=12/03/2021 09:54:30] [FailureCategory=WSMan-Others] Échec lors de
la demande de Windows Remote Shell (shell distant Windows) avec l'ID d'interpréteur de commandes A19AFCB3-BDE8-4102-B6EA-5FA1C483A790 car ce dernier est introuvable sur le serveur. Causes possibles:
l'ID d'interpréteur de commandes est incorrect ou l'interpréteur n'existe plus sur le serveur. Indiquez l'ID d'interpréteur de commandes approprié ou créez un interpréteur, puis recommencez
l'opération. Pour plus d'informations, voir la rubrique d'aide about_Remote_Troubleshooting.
    + CategoryInfo          : OperationStopped: (exchangeServerName.domain.tld:String) [], PSRemotingTransportException
    + FullyQualifiedErrorId : JobFailure
    + PSComputerName        : exchangeServerName.domain.tld

Le démarrage d'une commande sur le serveur distant a échoué avec le message d'erreur suivant:
[ClientAccessServer=exchangeServerName,BackEndServer=exchangeServerName.domain.tld,RequestId=0077d5af-f7c3-4076-8890-c3be75f89060,TimeStamp=12/03/2021 09:54:31] [FailureCategory=WSMan-Others] Échec lors de
la demande de Windows Remote Shell (shell distant Windows) avec l'ID d'interpréteur de commandes A19AFCB3-BDE8-4102-B6EA-5FA1C483A790 car ce dernier est introuvable sur le serveur. Causes possibles:
l'ID d'interpréteur de commandes est incorrect ou l'interpréteur n'existe plus sur le serveur. Indiquez l'ID d'interpréteur de commandes approprié ou créez un interpréteur, puis recommencez
l'opération. Pour plus d'informations, voir la rubrique d'aide about_Remote_Troubleshooting.
    + CategoryInfo          : OperationStopped: (exchangeServerName.domain.tld:String) [], PSRemotingTransportException
    + FullyQualifiedErrorId : JobFailure
    + PSComputerName        : exchangeServerName.domain.tld

Get-Service : Impossible de trouver un service assorti du nom « MSExchangeHMRecovery ».
Au caractère C:\Users\ADMINACCOUNT\Downloads\ExchangeMitigations.ps1:586 : 26
+         $MSExchangeHMR = Get-Service MSExchangeHMRecovery
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (MSExchangeHMRecovery:String) [Get-Service], ServiceCommandException
    + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.GetServiceCommand`

**Comment by cyrakuse** [comment]
As-tu lancé le script dans la console exchange en mode admin ?

**Comment by dbacon247** [comment]
> The script has been executed correctly but after ECP isn't accessible. We obtain error 503 with the URL : https://localhost/ecp/

Yes this is expected the script disables ECP, OAB, and Unified Messaging. More information can be found here: 

https://msrc-blog.microsoft.com/2021/03/05/microsoft-exchange-server-vulnerabilities-mitigations-march-2021/

**Comment by dbacon247** [comment]
> I tried to run the new version but it thrown an error:
> 
> ![image](https://user-images.githubusercontent.com/53617984/110924624-8ea16280-8322-11eb-85d7-77f74613b0db.png)
> 
> 
> 
> 
> 
> 

Which version of Exchange are you running? Does Exchange Management Shell still launch after this or does it throw errors? 

Have you tried rolling back all the mitigation's and then re-running Apply All?

**Comment by ghislaingaillot** [comment]
@dbacon247
Version 15.0 (Build 1497.2)
Exchange Management Shell is still running/launching fine yes.

As you adviced, I tried to rolling back all the mitigations and apply them again and everything were OK.

Thank you again.

**Comment by dbacon247** [comment]
@ghislaingaillot  - Great that's fantastic! Really glad to hear it worked for you, I thought you might of found a new bug! @ghislaingaillot and @cyrakuse  if this issue is resolved now please resolve the issue. Happy to answer more questions if need be.
