### ISSUE TITLE
LoadFromGitHub : C:\baseline_15.0.516.30.zip not found...

### ISSUE THREAD

**Issue by josephlevit** [microsoft/CSS-Exchange#279]
**Describe the issue**
CompareExchangeHashes.ps1 fails when trying to download baseline_15.0.516.30.zip

**Script Output**
PS C:\> .\CompareExchangeHashes.ps1
[03/11/2021 11:56:36] Started...
Found exchange version: 15.0.1497.2
Loaded baseline for 15.0.1104.5, hashes number 7353
Loaded baseline for 15.0.1497.2, hashes number 7395
Loaded baseline for 15.0.1497.12, hashes number 7464
Can't find local baseline for 15.0.516.30
Downloading baseline file from GitHub to C:\baseline_15.0.516.30.zip
LoadFromGitHub : C:\baseline_15.0.516.30.zip not found... please open issue on
https://github.com/microsoft/CSS-Exchange/issues, we will work on it
At C:\CompareExchangeHashes.ps1:647 char:13
+             LoadFromGitHub -url $zip_file_url -filename $zip_file -installed_ver ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,LoadFromGitHub

**Comment by VWMike** [comment]
I am still experiencing this issue:

[PS] C:\utilbats\haf>.\CompareExchangeHashes.ps1

Do you want to run software from this untrusted publisher?
File C:\utilbats\haf\CompareExchangeHashes.ps1 is published by CN=Microsoft Corporation, O=Microsoft Corporation,
L=Redmond, S=Washington, C=US and is not trusted on your system. Only run scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"): r
[03/11/2021 23:09:56] Started...
Creating a new session for implicit remoting of "Get-ExchangeServer" command...
Found exchange version: 15.0.1497.2
Can't find local baseline for 15.0.1395.4
Downloading baseline file from GitHub to C:\utilbats\haf\baseline_15.0.1395.4.zip
Loaded baseline for 15.0.1395.4, hashes number 7395
Can't find local baseline for 15.0.516.30
Downloading baseline file from GitHub to C:\utilbats\haf\baseline_15.0.516.30.zip
LoadFromGitHub : C:\utilbats\haf\baseline_15.0.516.30.zip not found... please open issue on
https://github.com/microsoft/CSS-Exchange/issues, we will work on it
At C:\utilbats\haf\CompareExchangeHashes.ps1:647 char:13
+             LoadFromGitHub -url $zip_file_url -filename $zip_file -installed_ver ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,LoadFromGitHub

[PS] C:\utilbats\haf>

**Comment by anshuldube** [comment]
Created a single task for tracking all missing baselines, please follow: https://github.com/microsoft/CSS-Exchange/issues/313
