### ISSUE TITLE
LoadFromGitHub : C:\tmp\baseline_15.0.712.23.zip not found...

### ISSUE THREAD

**Issue by Masterkey1979** [microsoft/CSS-Exchange#281]
[PS] C:\tmp>.\CompareExchangeHashes.ps1
[03/11/2021 11:00:38] Started...
Found exchange version: 15.0.1497.2
Can't find local baseline for 15.0.712.23
Downloading baseline file from GitHub to C:\tmp\baseline_15.0.712.23.zip
LoadFromGitHub : C:\tmp\baseline_15.0.712.23.zip not found... please open issue on
https://github.com/microsoft/CSS-Exchange/issues, we will work on it
In C:\tmp\CompareExchangeHashes.ps1:647 Zeichen:13
+             LoadFromGitHub -url $zip_file_url -filename $zip_file -installed_ver ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,LoadFromGitHub

**Comment by anshuldube** [comment]
Created a single task for tracking all missing baselines, please follow: https://github.com/microsoft/CSS-Exchange/issues/313
