### ISSUE TITLE
CompareExchangeHashes not working on Server Core [Issue]

### ISSUE THREAD

**Issue by JamesRoodCIT** [microsoft/CSS-Exchange#284]
**Describe the issue**
The script errors with unable to download from GitHub

**Expected behavior**
The script should successfully connect to GitHub

**Script Output**
Can't find local baseline for 15.2.464.5
Downloading baseline file from GitHub to C:\Windows\system32\baseline_15.2.464.5
.zip
LoadFromGitHub : Cannot reach out to
https://github.com/microsoft/CSS-Exchange/releases/latest, please download
baseline files for 15.2.464.5 15.2.792.10 15.2.792.3 from
https://github.com/microsoft/CSS-Exchange/releases/latest manually to
C:\Windows\system32, then rerun this script from C:\Windows\system32.
At line:647 char:13
+             LoadFromGitHub -url $zip_file_url -filename $zip_file -in ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
   n,LoadFromGitHub

**Additional context**
Editing Line 555 to add the parameter -UseBasicParsing resolves the issue

**Comment by psykokwak4** [comment]
thanks! added
