### ISSUE TITLE
[Issue] No baseline 15.0.1104.8 in repository

### ISSUE THREAD

**Issue by N1c093** [microsoft/CSS-Exchange#285]
**Describe the issue**
Sadly baseline 15.0.1104.8 seems to be missing in the repository

**Expected behavior**
Baseline 15.0.1104.8 is present in repository

**Script Output**
CSV report output: `"01/14/2016 18:16:55","xxx\V15\ClientAccess","microsoft.owa.attachments.collabattachmentpreview.js","08/27/2015 17:29:54","NoHashMatch","C81206FCF0C5BDA707A985DC39EA061B619620D5EFDA81A3E3BCDDD19768E31D","xxx\V15\ClientAccess\Owa\prem\15.0.1104.8\scripts\microsoft.owa.attachments.collabattachmentpreview.js","01/14/2016 18:16:55","Exchange Back End/`

**Comment by anshuldube** [comment]
Created a single task for tracking all missing baselines, please follow: https://github.com/microsoft/CSS-Exchange/issues/313
