### ISSUE TITLE
CompareExchangeHashes false positive(?) after RewriteRules added to web.config

### ISSUE THREAD

**Issue by ex9r** [microsoft/CSS-Exchange#287]
After applying the BackendCookieMitigation.ps1 , the web.config gets changed (added rewrite rules) and is flagged as suspicious. 
Am i missing something or is this a false positive? 

"LastAccessTimeUtc","PDir","FileName","LastWriteTimeUtc","Error","FileHash","FilePath","CreationTimeUtc","VDir"
"04/04/2020 22:50:07","C:\inetpub\wwwroot","web.config","03/08/2021 15:30:02","Suspicious","EA09B9DE0C02B15FECBBB399024D7DBA44B6EE1D88C67F425D0E730AA8F7C832","C:\inetpub\wwwroot\web.config","04/04/2020 22:50:07","Default Web Site/"

Only thing changed in that file are rewrite rules, i compared it to a file from an old backup. 

Thanks and BR
Darius

**Comment by psykokwak4** [comment]
it is expected, the script blindly marks any file under `"$env:SystemDrive\inetpub\wwwroot"` changed after

https://github.com/microsoft/CSS-Exchange/blob/e6d04b8402c3e15bb4bb942ffc8b32a77f2085f5/Security/src/CompareExchangeHashes.ps1#L299

as suspicious, the current version only compares local file hash with known good hashes, and it does not have capability to exam file content

related snippet:


https://github.com/microsoft/CSS-Exchange/blob/e6d04b8402c3e15bb4bb942ffc8b32a77f2085f5/Security/src/CompareExchangeHashes.ps1#L376-L387


https://github.com/microsoft/CSS-Exchange/blob/e6d04b8402c3e15bb4bb942ffc8b32a77f2085f5/Security/src/CompareExchangeHashes.ps1#L414-L425
