### ISSUE TITLE
"Parameter Cannot be found... 'DestinationPath'" CompareExchangeHashes.ps1  

### ISSUE THREAD

**Issue by MushyPeaFritter** [microsoft/CSS-Exchange#314]
Receiving the following error when running CompareExchangeHashes.ps1 on Some (not all) Exchange servers.

[03/12/2021 01:30:55] Started...
Found exchange version: 15.0.1497.2
Main : A parameter cannot be found that matches parameter name 'DestinationPath'.
At C:\Users\user\Desktop\Hashes\CompareExchangeHashes.ps1:766 char:1
+ Main $CompressSuspiciousAndMissingFilesToCSV
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Main], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Main_**

The PS1 script has run successfully on other machines

I have attempted to download the files directly to see if it is a problem connecting to the site but the error persists. 

Any ideas?

Thanks in advance :)

**Comment by psykokwak4** [comment]
what's your powershell version? and if your system allows to run unsigned script, will it help if you change the last line of the script to something like below?

```ps
Main -CompressSuspiciousAndMissingFilesToCSV $CompressSuspiciousAndMissingFilesToCSV
```

**Comment by psykokwak4** [comment]
closing it since this script is deprecated
