### ISSUE TITLE
Can't find local baseline for 15.0.712.23

### ISSUE THREAD

**Issue by AndreasBlank** [microsoft/CSS-Exchange#319]
Hello 
running the powershell script CompareExchangeHashes.ps1 I get following error:

Downloading baseline file from GitHub to C:\temp\baseline_15.0.712.23.zip
LoadFromGitHub : C:\temp\baseline_15.0.712.23.zip not found... please open issue on
https://github.com/microsoft/CSS-Exchange/issues, we will work on it
In C:\temp\CompareExchangeHashes.ps1:654 Zeichen:13
+             LoadFromGitHub -url $zip_file_url -filename $zip_file -installed_ver ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,LoadFromGitHub
![error](https://user-images.githubusercontent.com/55684976/110906921-f6e54980-830c-11eb-8a0a-cc0206964c1e.PNG)

**Comment by Masterkey1979** [comment]
Same here with 2 Servers

**Comment by psykokwak4** [comment]
tracked from #313
