### ISSUE TITLE
[Question] CompareExchangeHashes OAB temp-file

### ISSUE THREAD

**Issue by N1c093** [microsoft/CSS-Exchange#320]
Hello,

I hope it's okay to ask a question here. I just run the `CompareExchangeHashes.ps1` against my Exchange Server. It just found a hash mismatch in one temp OAB-File. 

Should I be worried about it?

These lines where present in the result CSV:

```
"04/27/2020 20:58:01","xxx\V15\ClientAccess","LZXhzdmgalp.djs","04/27/2020 22:06:11","NoHashMatch","E9BEAC5CBF3E4141A8B907CAB7D8A6379974427653D3F2B89ACB34A4E06B2665","xxx\V15\ClientAccess\OAB\Temp\LZXhzdmgalp.djs","04/27/2020 20:58:01","Exchange Back End/"


"04/27/2020 20:58:01","xxx\V15\ClientAccess\OAB","LZXhzdmgalp.djs","04/27/2020 22:06:11","NoHashMatch","E9BEAC5CBF3E4141A8B907CAB7D8A6379974427653D3F2B89ACB34A4E06B2665","xxx\V15\ClientAccess\OAB\Temp\LZXhzdmgalp.djs","04/27/2020 20:58:01","Exchange Back End/OAB/"

```

Thank you in advance!

**Comment by psykokwak4** [comment]
closing it since this script is deprecated

**Comment by MScialfa** [comment]
Hi N1c093, can you explain me why and when Exchange create this strange files in C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\OAB\Temp?
What are this files?
Thanks in advance

**Comment by N1c093** [comment]
Hi @MScialfa 
actually I don't know, what these files are and where they come from. I think these are temp files from the offline address book, which wasn't cleaned up. I only see these files on one of four nodes. These files were create in April and August 2020.
