### ISSUE TITLE
CompareExchangeHashes.ps1 baseline_15.0.995.28.zip not found

### ISSUE THREAD

**Issue by mbu36** [microsoft/CSS-Exchange#322]
Loaded baseline for 15.0.1473.3, hashes number 7394
Loaded baseline for 15.0.995.29, hashes number 11830
Can't find local baseline for 15.0.995.28
Downloading baseline file from GitHub to C:\tmp\mbu\HN_Check\baseline_15.0.995.28.zip
LoadFromGitHub : C:\tmp\mbu\HN_Check\baseline_15.0.995.28.zip not found... please open issue on https://github.com/microsoft/CSS-Exchange/issues, we will work on it
In C:\tmp\mbu\HN_Check\CompareExchangeHashes_1.ps1:654 Zeichen:13
+             LoadFromGitHub -url $zip_file_url -filename $zip_file -in ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,LoadFromGitHub

**Comment by psykokwak4** [comment]
please check `#313` for baseline updates
