### ISSUE TITLE
[Issue] Baseline for 15.1.1913.12 missing

### ISSUE THREAD

**Issue by jellyneck84** [microsoft/CSS-Exchange#324]
**Describe the issue**
the compare hash scripts reports me many .js files in directory ClientAccess\Owa\prem\15.1.1913.12\scripts. I can not see a basefile for this version in the repository. The version is Exchange 2016 CU16 with the security fix, now we updated to CU19 with the fix and run the check. Seems for me to be a false positive. Creation Date of the files is the time and date when we installed the security fix for cu16.

Can you confirm this?

**Comment by psykokwak4** [comment]
yes! please check `#313` for baseline updates
