### ISSUE TITLE
[Issue] baseline for 15.0.1044.29 missing

### ISSUE THREAD

**Issue by t3easy** [microsoft/CSS-Exchange#325]
**Describe the issue**
baseline for 15.0.1044.29 missing

**Expected behavior**
baseline for 15.0.1044.29 exists

**Script Output**
(Hopefully) False positive alert

**Additional context**
CompareExchangeHashes.ps1

**Comment by jellyneck84** [comment]
Which files were marked as hash missing? had a similiar issue with a different version.

**Comment by t3easy** [comment]
@jellyneck84 the hole baseline is missing not just some files so every file in the 15.0.1044.29 folder is marked as "potentially malicious files"

**Comment by t3easy** [comment]
As the files didn't changed since 2015, and there is no zip for 15.0.1044.29 https://github.com/microsoft/CSS-Exchange/releases/tag/v21.03.12.0547...

**Comment by psykokwak4** [comment]
thanks! please check `#313` for baseline updates
