### ISSUE TITLE
[Issue] Incomplete Output?

### ISSUE THREAD

**Issue by Kvoo** [microsoft/CSS-Exchange#328]
**Describe the issue**

Running the script locally on the exchange server, it does not show if our server has been hit or not. A friend of mine ran it a few days ago, and it correctly showed green / red messages stating if the server is affected.

**Expected behavior**

The script clearly states if the server was hit or not

**Script Output**

PS C:\temp> .\Test-ProxyLogon.ps1 -DisplayOnly
ProxyLogon Status: Exchange Server SVEX03
  Log age days: Oabgen  Ecp 29.5 Autod 30.0 Eas 30.0 EcpProxy 30.0 Ews 30.0 Mapi 30.0 Oab 30.0 Owa 30.0 OwaCal 30.0 Powershell 30.0 RpcHttp 30.0
  Other suspicious files found: 1
   SuspiciousArchive : C:\ProgramData\AppRecovery\InstallerCache\Agent\configuration.zip

**Comment by bill-long** [comment]
We don't put "Other suspicious files" in red because they are only suspicious - they are not a confirmed hit. But we also don't show the green message when we find suspicious files because we did find something that should be reviewed by an admin.

**Comment by Kvoo** [comment]
I see, that makes sense! Consider this solved.
