### ISSUE TITLE
After apply ExchangeMitigations.ps1 ECP access is lost

### ISSUE THREAD

**Issue by eduzav** [microsoft/CSS-Exchange#338]
In Exchange Server 2016 CU11 and after applying the script ExchangeMitigations.ps1 ECP access is lost, can it be?

If I try to access the administration console from the local server -> "https: //localhost/ecp" I have an error "HTTP error 503 - The service is unavailable"

If I rollback the script I have the management available again.
I'm something wrong??

**Comment by eduzav** [comment]
![nmap scan - after script](https://user-images.githubusercontent.com/16383631/111016733-4455cb00-838e-11eb-842a-1595ec97d0b5.PNG)
![nmap scan - before script](https://user-images.githubusercontent.com/16383631/111016738-4586f800-838e-11eb-9c12-e202668a1114.PNG)
![output powershell script](https://user-images.githubusercontent.com/16383631/111016739-461f8e80-838e-11eb-9157-861fe41c948d.PNG)

**Comment by eduzav** [comment]
I attached the output of powershell script and the nmap scan before /after installed-

**Comment by eduzav** [comment]
![error](https://user-images.githubusercontent.com/16383631/111016869-01e0be00-838f-11eb-99ba-5af7c0ccda87.PNG)

**Comment by dbacon247** [comment]
@eduzav this is by design and part of the mitigation. There is a switch for each piece. 

ApplyAll, Apply OAB, Apply ECP, Apply UM. 
Rollback all, rollback OAB, rollback, rollback ecp, rollback UM. 

For more information visit: https://msrc-blog.microsoft.com/2021/03/05/microsoft-exchange-server-vulnerabilities-mitigations-march-2021/

**Comment by eduzav** [comment]
Perfect!!!, other question, do you know if having the ecp disabled also serves as mitigation?
Ej -> Set-EcpVirtualDirectory -Identity "ecp (Default Web Site)" -AdminEnabled $false
