### ISSUE TITLE
[Issue] Potential false positives in temp folder

### ISSUE THREAD

**Issue by ericwbentley** [microsoft/CSS-Exchange#345]
**Describe the issue**
After running CompareExchangeHashes.ps1, in the results a file in a temp folder is returned as NoHashMatch

The filename is LZXc2f3lst0.1js and it is located in C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\OAB\Temp

I believe it is being compared because it matches the pattern *js even though it is not a JS file

`foreach ($f in (Get-ChildItem -Recurse -Path $pdir -File -Include *aspx, *asmx, *asax, *js, *css, *htm, *html)) {`

**Expected behavior**
Files in temp locations should not be compared against baselines since they are uniquely generated. But they may still be scanned for known bad hashes.

**Script Output**
"05/22/2020 23:01:23","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\OAB","LZXc2f3lst0.1js","05/22/2020 23:02:27","NoHashMatch","0FB0953831C314195A9761723CFB5D2CB2D18B006A310E16C225B9108161275F","C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\OAB\Temp\LZXc2f3lst0.1js","05/22/2020 23:01:23","Exchange Back End/OAB/"

**Additional context**
The file has been submitted to Microsoft for analysis through https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by ericwbentley** [comment]
Dupe of #320 , my mistake

**Comment by MScialfa** [comment]
Hi ericwbentley, can you explain me why and when Exchange create this strange files in C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\OAB\Temp?
What are this files?
Thanks in advance
