### ISSUE TITLE
[Issue]Can't find local baseline for 14.02.0390.003

### ISSUE THREAD

**Issue by darrenmolloy** [microsoft/CSS-Exchange#349]
Get-Service : Cannot find any service with service name 'MSExchangeHM'.
At C:\ExchangeMitigations.ps1:575 char:21
+     $MSExchangeHM = Get-Service MSExchangeHM
+                     ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (MSExchangeHM:String) [Get-Service], ServiceCommandException
    + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.GetServiceCommand

PS C:\> .\CompareExchangeHashes.ps1
[03/15/2021 12:08:03] Started...
Found exchange version: 14.02.0390.003
Can't find local baseline for 14.02.0390.003
Downloading baseline file from GitHub to C:\baseline_14.02.0390.003.zip
LoadFromGitHub : C:\baseline_14.02.0390.003.zip not found... please open issue on
https://github.com/microsoft/CSS-Exchange/issues, we will work on it
At C:\CompareExchangeHashes.ps1:660 char:13
+             LoadFromGitHub -url $zip_file_url -filename $zip_file -in ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,LoadFromGitHub

**Comment by psykokwak4** [comment]
tracked at #313
