### ISSUE TITLE
Cannot find path "(vdir's)" because it does not exist. At D:\tmp\CompareExchangeHashes.ps1:533 char:13

### ISSUE THREAD

**Issue by dimbra2021** [microsoft/CSS-Exchange#352]
Receiving the following error on 1 of our Exchange servers;

`Processing 3 directories in parallel. Batch 1 of 10 batches.
Cannot find path 'D:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\owa' because it does not exist.
At D:\tmp\CompareExchangeHashes (3).ps1:533 char:13
$res = Receive-Job $job.ID
CategoryInfo          : ObjectNotFound: (D:\Program File...d\HttpProxy\owa:String) [Get-ChildItem], ItemNotFound
Exception
FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
PSComputerName        : localhost`

Tried adjusting the path manually in the code, but can't exactly pinpoint where this is going wrong.
When we pull the Get-OWAvirtualDirectory for example, we see the virtual directory pointing to c:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\owa so the error is perfectly understandable.

But we can't find the part to adjust..

**Comment by psykokwak4** [comment]
could you share your output for the below cmdlet?

```ps
$logs = & (Join-Path $env:Windir "system32\inetsrv\appcmd.exe") LIST VDIRS
```

seems like the above cmdlet is returning you D drive but your actual owa vdir path is in C drive (as returned by Get-OWAVirtualDirectory)

**Comment by psykokwak4** [comment]
https://github.com/microsoft/CSS-Exchange/blob/1c9607dfc7ab84b253efe0e4fcd7116cc09c1147/Security/src/CompareExchangeHashes.ps1#L599

https://github.com/microsoft/CSS-Exchange/blob/1c9607dfc7ab84b253efe0e4fcd7116cc09c1147/Security/src/CompareExchangeHashes.ps1#L620

line 620 and 599 from commit 1c9607dfc7ab84b253efe0e4fcd7116cc09c1147 are what you'd like to change, probably replacing the parsed value with C drive path will help

**Comment by dimbra2021** [comment]
Below the output from the given command. Strange thing is, the virtual directories are on the C drive, but the script is returning the D drive. Below the c drive is returned except the last 2 ines, but the directories on the D drive doesn't exist...

`VDIR "Default Web Site/" (physicalPath:%SystemDrive%\inetpub\wwwroot)
VDIR "Default Web Site/Rpc/" (physicalPath:C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\rpc)
VDIR "Default Web Site/owa/" (physicalPath:C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\owa)
VDIR "Default Web Site/owa/Calendar/" (physicalPath:C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\o
wa)
VDIR "Default Web Site/owa/Integrated/" (physicalPath:C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy
\owa)
VDIR "Default Web Site/owa/oma/" (physicalPath:C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\owa)
VDIR "Default Web Site/ecp/" (physicalPath:C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\ecp)
VDIR "Default Web Site/EWS/" (physicalPath:C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\EWS)
VDIR "Default Web Site/Autodiscover/" (physicalPath:C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\A
utodiscover)
VDIR "Default Web Site/Microsoft-Server-ActiveSync/" (physicalPath:C:\Program Files\Microsoft\Exchange Server\V15\Front
End\HttpProxy\sync)
VDIR "Default Web Site/OAB/" (physicalPath:C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\OAB)
VDIR "Default Web Site/mapi/" (physicalPath:C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\mapi)
VDIR "Default Web Site/PowerShell/" (physicalPath:C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\Pow
erShell)
VDIR "Exchange Back End/" (physicalPath:C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess)
VDIR "Exchange Back End/PowerShell/" (physicalPath:C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\PowerShe
ll-Proxy)
VDIR "Exchange Form Based/" (physicalPath:C:\inetpub\exchange_fb)
VDIR "Exchange Form Based/ecp/" (physicalPath:C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\ecp_fb)
VDIR "Exchange Form Based/owa/" (physicalPath:C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\owa_fb)
VDIR "Exchange Form Based/owa/Calendar/" (physicalPath:D:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProx
y\owa)
VDIR "Exchange Form Based/owa/Integrated/" (physicalPath:D:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpPr
oxy\owa)
VDIR "Exchange Form Based/owa/oma/" (physicalPath:D:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\owa
)`

**Comment by psykokwak4** [comment]
not sure why are you having extra spaces for the below vdir physical paths.. (column 120 if line is long enough)
but yeah, this script iterate through paths returned from `& (Join-Path $env:Windir "system32\inetsrv\appcmd.exe") LIST VDIRS`
not sure why physical paths returned from appcmd.exe are not trustworthy

![image](https://user-images.githubusercontent.com/6261280/111205152-26ea5200-8584-11eb-873c-ac18e93c4828.png)

```
VDIR "Default Web Site/" (physicalPath:%SystemDrive%\inetpub\wwwroot) 
VDIR "Default Web Site/Autodiscover/" (physicalPath:C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\A utodiscover) 
VDIR "Default Web Site/ecp/" (physicalPath:C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\ecp) 
VDIR "Default Web Site/EWS/" (physicalPath:C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\EWS) 
VDIR "Default Web Site/mapi/" (physicalPath:C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\mapi) 
VDIR "Default Web Site/Microsoft-Server-ActiveSync/" (physicalPath:C:\Program Files\Microsoft\Exchange Server\V15\Front End\HttpProxy\sync) 
VDIR "Default Web Site/OAB/" (physicalPath:C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\OAB) 
VDIR "Default Web Site/owa/" (physicalPath:C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\owa) 
VDIR "Default Web Site/owa/Calendar/" (physicalPath:C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\o wa) 
VDIR "Default Web Site/owa/Integrated/" (physicalPath:C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy \owa) 
VDIR "Default Web Site/owa/oma/" (physicalPath:C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\owa) 
VDIR "Default Web Site/PowerShell/" (physicalPath:C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\Pow erShell) 
VDIR "Default Web Site/Rpc/" (physicalPath:C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\rpc) 
VDIR "Exchange Back End/" (physicalPath:C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess) 
VDIR "Exchange Back End/PowerShell/" (physicalPath:C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\PowerShe ll-Proxy) 
VDIR "Exchange Form Based/" (physicalPath:C:\inetpub\exchange_fb) 
VDIR "Exchange Form Based/ecp/" (physicalPath:C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\ecp_fb) 
VDIR "Exchange Form Based/owa/" (physicalPath:C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\owa_fb) 
VDIR "Exchange Form Based/owa/Calendar/" (physicalPath:D:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProx y\owa) 
VDIR "Exchange Form Based/owa/Integrated/" (physicalPath:D:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpPr oxy\owa) 
VDIR "Exchange Form Based/owa/oma/" (physicalPath:D:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\owa )
```

**Comment by psykokwak4** [comment]
gocha you (or malicious actors) must have changed vdir's manually
i guess you could probably contact appcmd.exe support to check whether there's a way to restore them to their original values?
or open PR to fix the script to retrieve vidr paths from cmdlets such as  `Get-OWAvirtualDirectory`?

**Comment by psykokwak4** [comment]
closing it since this script is deprecated
