### ISSUE TITLE
[Issue] Shows server as vulnerable if run on a non-exchange server

### ISSUE THREAD

**Issue by singlethreaded** [microsoft/CSS-Exchange#374]
**Describe the issue**
This script reports the server as vulnerable if Exchange is not installed.
MSPs and IR firms often can't guarantee the server they run this on is running exchange due to lack of consistency or naming conventions between customers.

**Expected behavior**
Should report that exchange is not installed.

**Script Output**
If applicable, add the exception that you are seeing that wasn't handled.

**Additional context**
The offending code is in: Get-ServerVulnStatus. It checks for a key and if it doesn't find an exchange version it just uses an else statement to assume a version.
```
{
    param(
        $Version = (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\ExchangeServer\v15\Setup\')
    )

    $Version = $Version.OwaVersion
    $FutureCUs = @{
        E19CU9  = "15.2.858.5"
        E16CU20 = "15.1.2242.4"
    }

    if ($version -like "15.2.*") {
        $LatestCU = $FutureCUs.E19CU9
    } elseif ($version -like "15.1.*") {
        $LatestCU = $FutureCUs.E16CU20
    } else {
        $LatestCU = "15.2.000.0000" #version higher than 15.0 to trigger SecurityHotfix check for E15
    }
```

**Comment by singlethreaded** [comment]
For reference, this is what i added to make it stop:
```
$exchangePath = (Get-ItemProperty -Path Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ExchangeServer\v15\Setup -ea 0).MsiInstallPath
if ($null -eq $exchangePath) {
    $exchangePath = (Get-ItemProperty -Path Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ExchangeServer\v14\Setup -ea 0).MsiInstallPath
}
if ($null -eq $exchangePath) {
   Write-Error "Exchange not found"
   return $false
}
```

**Comment by dbacon247** [comment]
@singlethreaded  thanks for the feedback! This will be addressed in the next Pull Request.
