### ISSUE TITLE
[Issue] get-culture language

### ISSUE THREAD

**Issue by michalnh** [microsoft/CSS-Exchange#377]
**Describe the issue**
Patched Exchange Server 2010, SP3 RU32 de-DE
Windows Server 2008R2
Investigate for any adversary activity, indicators of compromise, etc….
get-culture language error running the script.

**Expected behavior**
Run EOMT.PS1
Errormessage...

**Script Output**
...right site Operators "-" Value expression
EOMT.ps1:245 :33
      if ((Get-Culture).Name - <<<< in @("de-DE", "en-US", "es-ES", "fr-FR", "it-IT", "ja-JP", "ko-KR", "ru-RU", "zn-CN", "zn-TW")) 
{
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ExpectedValueExpression 

**Additional context**

**Comment by bill-long** [comment]
Looks like `-in` is not recognized, which means the PowerShell version is too low. The script requires at least version 3. Further, the script does not support Exchange 2010. Please refer to the System Requirements in the [readme](https://github.com/microsoft/CSS-Exchange/tree/main/Security#exchange-on-premises-mitigation-tool-eomt).

**Comment by michalnh** [comment]
@bill-long 
Thanks for the quick feedback.

**Comment by dbacon247** [comment]
@bill-long Thanks!
