### ISSUE TITLE
EOMT v21.03.17.2012 problem with Exchange 2016 CU20

### ISSUE THREAD

**Issue by RedPeace** [microsoft/CSS-Exchange#384]
Hi,

EOMT v21.03.17.2012 does not recognize CU20 für Exchange 2016 and is applying the mitigations!

What to do now? Reinstall CU20?

Greetings
Gero

**Comment by dbacon247** [comment]
Hi @RedPeace 

You can just run .\EOMT.ps1 -Rollbackmitigation￼

No need to redeploy E16CU20, small bug in the script that was missed and addressed just now in.

https://github.com/microsoft/CSS-Exchange/commit/bac721a38e239967dc9d7eabb2f714d6c0ee878c

**Comment by RedPeace** [comment]
Hi,

perfect.

Thank you! :)
