### ISSUE TITLE
EOMT 21.03.18.2345 Get-ServerVulnStatus detects Ex2019 CU9 as vulnerable

### ISSUE THREAD

**Issue by jaspain** [microsoft/CSS-Exchange#396]
We patched our Ex2019 CU8 server with KB5000871 and subsequently installed CU9. `$Version = (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\ExchangeServer\v15\Setup\').OwaVersion` returns `15.2.858.2`, which is less than `$FutureCUs.E19CU9`. Therefore the function searches for the security hotfix KB5000871, but doesn't find it. Although this hotfix was definitely installed prior to the installation of CU9, it appears that the CU9 installation removed it. Therefore the server is falsely determined to be vulnerable. Should `$FutureCUs.E19CU9` be set to `15.2.858.2` instead of `15.2.858.5`?

**Comment by paddybuss** [comment]
They will have a look on it and will change the way how the script detect the installed build version.

https://github.com/microsoft/CSS-Exchange/pull/406

Ive changed the owa version for myself and now all works fine.

**Comment by bill-long** [comment]
Closing this as the fix is released.
