### ISSUE TITLE
EOMT.ps1 keeps reporting server is vulnerable

### ISSUE THREAD

**Issue by alvesman** [microsoft/CSS-Exchange#424]
**Describe the issue**
EOMT.ps1 keeps reporting server is vulnerable after applying mitigation. URL Rewrite configuration is already updated.
Exchange 2016 with cumulative update 20 and no pending windows updates

**Expected behavior**
Do not report server is vulnerable....

**Comment by dbacon247** [comment]
Confirmed this is fixed in the latest version of EOMT. Please download the latest version.
