### ISSUE TITLE
Setup -- Display FSMO , Site of Exchange server

### ISSUE THREAD

**Issue by Sureshbd** [microsoft/CSS-Exchange#428]
**Is your request related to a problem? Please describe.**
New request

**Describe The Request**
Display FSMO information and alert if the Exchange box is of different site
Netdom Query FSMO 
Nltest /dsgetsite for site information or Get-Exchangeserver |ft name,site or Check DynamicSiteName from registry
HKLM\System\CurrentControlSet\Services\Netlogon\Parameters
If the site is hardcoded for any reason then SiteName key

**Additional context**

**Comment by dpaulson45** [comment]
Right now the way this works, we will display this information if we aren't on the latest build of Exchange.

Change: 056b92a0ff4116699fd74e14bda72a99fdaabc8d


Output Example:

![image](https://user-images.githubusercontent.com/22776718/113321164-f0793a80-92d8-11eb-8ec5-9f6082828829.png)

**Comment by dpaulson45** [comment]
Being that this is already checked in and this information is only required useful when we need to do ` /prepareAD `, this issue can be closed.
