### ISSUE TITLE
EOMT.ps1 Version 21.03.18.2345, Script Fails if "Windows Management Instrumentation" is not running!

### ISSUE THREAD

**Issue by drejabi** [microsoft/CSS-Exchange#435]
On row 474: 
if ((Get-Item $env:TEMP).PSDrive.Free -ge 314572800) {
--> Will return none/null.  and Scripts then fails do to low disk space...
Get-Psdrive requires WMI to be running, took me some "digging" before i figured that out,

Maybe a status check of the Windows "Winmgmt" Service...

Thx
Rikard

**Comment by bill-long** [comment]
Since this has been open for 5 months, I'm going to close it. Looks like this isn't going to be addressed.

Hopefully, anyone that runs into this problem will find this issue. Thanks for reporting it.
