### ISSUE TITLE
Using Get-WinEvent with Hashtable instead of Get-Eventlog increases performance

### ISSUE THREAD

**Issue by Marc4056** [microsoft/CSS-Exchange#47]
https://github.com/microsoft/CSS-Exchange/blob/2fce81069fc0686a00eb5fa6accb280ccce2ebe7/Security/Test-Hafnium.ps1#L45

I replaced line 45 where the eventlog is searched using CMDlet "Get-Eventlog" with CMDlet "Get-WinEvent" using FilterableHashtable as follows:

$eventLogs = Get-WinEvent -FilterHashtable @{LogName='Application'; ProviderName='MSExchange Unified Messaging'; Level='2'} | Where-Object { $_.Message -like "`*`System.InvalidCastException`*`"}

This speeds up the query approx by  factor 10 on my systems. Eventlog search now only takes about 3 minutes per system instead of 30 minutes

**Comment by bill-long** [comment]
Looks like it throws an error when the event log is clean, so we will need to handle that gracefully.

```
PS C:\>  Get-WinEvent -FilterHashtable @{LogName='Application'; ProviderName='MSExchange Unified Messaging'; Level='2'} | Where-Object { $_.Message -like "*System.InvalidCastException*"}
Get-WinEvent : No events were found that match the specified selection criteria.
At line:1 char:2
+  Get-WinEvent -FilterHashtable @{LogName='Application'; ProviderName= ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-WinEvent], Exception
    + FullyQualifiedErrorId : NoMatchingEventsFound,Microsoft.PowerShell.Commands.GetWinEventCommand
```

**Comment by Marc4056** [comment]
That is true, but I experience the same when the eventlog is clean using the Get-Eventlog CMDlet

**Comment by bill-long** [comment]
Ah you're right, we just need to tack on the SilentlyContinue like the other command had.

**Comment by bill-long** [comment]
Thank you!

**Comment by Marc4056** [comment]
Right, forgot to take parameter "-ErrorAction SilentlyContinue" into my command
