### ISSUE TITLE
[Issue] format issue in Get-MRMDetails.ps1

### ISSUE THREAD

**Issue by DennyMei** [microsoft/CSS-Exchange#528]
**Describe the issue**
Get-MRMDetails.ps1 failed to run, error shows single quote mark issue in line 51.
![image](https://user-images.githubusercontent.com/1555117/116025616-852a4a80-a683-11eb-8f12-2dbba1832cc5.png)

**Script Output**
![image](https://user-images.githubusercontent.com/1555117/116025481-2c5ab200-a683-11eb-9be5-6e634c74f783.png)

**Comment by bill-long** [comment]
Confirmed fixed by releasing with the proper encoding:

![image](https://user-images.githubusercontent.com/4518572/116130223-97f74c00-a690-11eb-82f6-309075e4d6ac.png)

Curly quotes are still there but it's fine now.

**Comment by DennyMei** [comment]
It works now, thanks.
