### ISSUE TITLE
SetupAssist should fix tombstoned well known groups

### ISSUE THREAD

**Issue by bill-long** [microsoft/CSS-Exchange#53]
SetupAssist.ps1 should detect when otherWellKnownGroups contains DEL objects and should generate an ldifde import file so the user can easily clean them up if desired.

**Comment by Julien-nl** [comment]
the scan has detected this.
```
WARNING:
Zipped files found in C:\ProgramData, please verify these are expected:
C:\ProgramData\VMware\VMware Tools\vss_manifests.zip
```
I have scanned the file, I don't know if I have to worry about this.

**Comment by bill-long** [comment]
Sorry, we cannot help with the results of Test-Hafnium in the issues of this repo, except insofar as bugs or enhancements to the script. The script will flag any zip files in ProgramData so you can verify they are valid and expected based on the software installed.
