### ISSUE TITLE
HealthChecker - [New Check] Check installed UCMA version

### ISSUE THREAD

**Issue by dpaulson45** [microsoft/CSS-Exchange#535]
Creating an issue to track this pending investigating of UCMA version. 

Original Request: 

**Describe the issue**
Currently Microsoft offers UCMA 4.0 as required for a 2013/2016/2019 Exchange installation.
UCMA 4.0 is outdated and not supported anymore on Server 2016 and 2019.
UCMA 6.0 is the latest supported version (which currently has some issues which Microsoft does not seem to have fixed)

**Additional context**
Source: https://docs.microsoft.com/en-us/answers/questions/167684/exchange-2016-exchange-2019-wrong-recommendations.html

Migrated From: https://github.com/dpaulson45/HealthChecker/issues/538

**Comment by JustinHoeky** [comment]
Hi @lusassl-msft ,
Any news on this topic?
We talked about this one in March https://github.com/dpaulson45/HealthChecker/issues/538

**Comment by Karl-WE** [comment]
@JustinHoeky unfortunately haven't received any feedback from the Exchange Team yet on the Microsoft Q&A or Microsoft Techcommunity forums. Also Exch Docs.microsoft.com are not connected publicly to github so one could create an issue or PR for updating the documentation. 
My main concern is still the wrong hardcoded C++ Redist on UCMA 6.0 setup. I have few hope that someone could change it from = to >= in the MSI. It would be easy though not sure who can be asked / is responsible. 

Also unclear what is the need for the UCMA anyway as Skype for Business is dead. I am not sure if Teams in a Exchange Hybrid would still need it.

**Comment by lusassl-msft** [comment]
@JustinHoeky it's still under investigation. Until it is clarified you should use UCMA 4.0 (as stated in the prerequisites: https://docs.microsoft.com/en-us/exchange/plan-and-deploy/prerequisites?view=exchserver-2019#exchange-2019-mailbox-servers-on-windows-server-2019). 
We ship this version with the Exchange bits (version which can be used on Server 2019 Core) and use it to run unit tests in development etc. . Keep you posted when I have more recent information on this topic.

**Comment by Karl-WE** [comment]
Hi @lusassl-msft any news from the Exchange Team on this?

**Comment by Karl-WE** [comment]
Hi @lusassl-msft good news. UCMA 4.0 is not the correct version for Exchange Server 2016 and 2019. My doubts seem to be about right. 
Exchange Team signed off my PR on docs.
https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/2771#event-5280924630

**Comment by tiburd** [comment]
@Karl-WE - The Exchange team noticed your change and asked me to revert it:

> AFAIK the 6.0 version was not yet tested with Exchange so I'd strongly recommend reverting the change.
> We still ship UCMA 4.0 by default with Exchange 2019 and our testing is done by using UCMA 4.0. 

It was reverted in [this PR](https://github.com/MicrosoftDocs/OfficeDocs-Exchange-pr/pull/2070), and a note has been added that states UCMA 4.0 must be used even if the documentation for UCMA 4.0 stated that it's not supported with Windows server 2016/2019.

**Comment by Karl-WE** [comment]
I am fine to close this PR @dpaulson45

**Comment by dpaulson45** [comment]
If this changes, we will make sure we update the script to handle it.
