### ISSUE TITLE
[Issue] - Health Checker - Load Balancing Report doesn't work on Non-US systems

### ISSUE THREAD

**Issue by lusassl-msft** [microsoft/CSS-Exchange#581]
Health Checker Load Balancing doesn't work on Non-US systems. We use a static approach (counter name in English language) to query the required counters. Need to investigate if there is another way to query the required counters without relying on the name (like: https://powershellmagazine.com/2013/07/19/querying-performance-counters-from-powershell/).

**Comment by dpaulson45** [comment]
Unable to use the code in the above article for non-Windows default counters. 

```
Function Get-PerformanceCounterLocalName
{
  param
  (
    [UInt32]
    $ID,
	$ComputerName = $env:COMPUTERNAME
  )

  $code = '[DllImport("pdh.dll", SetLastError=true, CharSet=CharSet.Unicode)] public static extern UInt32 PdhLookupPerfNameByIndex(string szMachineName, uint dwNameIndex, System.Text.StringBuilder szNameBuffer, ref uint pcchNameBufferSize);'

  $Buffer = New-Object System.Text.StringBuilder(1024)
  [UInt32]$BufferSize = $Buffer.Capacity

  $t = Add-Type -MemberDefinition $code -PassThru -Name PerfCounter -Namespace Utility
  $rv = $t::PdhLookupPerfNameByIndex($ComputerName, $id, $Buffer, [Ref]$BufferSize)

  if ($rv -eq 0)
  {
    $Buffer.ToString().Substring(0, $BufferSize-1)
  }
  else
  {
    Throw 'Get-PerformanceCounterLocalName : Unable to retrieve localized name. Check computer name and performance counter ID.'
  }
}
```

This doesn't have the same index for different machines. Need to crawl the server for the registry and get the index that way. 

Hopefully most computers do have the `009` (English) that we can base this information off of.

**Comment by lusassl-msft** [comment]
The `009` should be exist. It’s the default on each computer independent from OS language
