### ISSUE TITLE
[Issue] - Health Checker html report not showing correct info regarding vulnerabilities.

### ISSUE THREAD

**Issue by emptystreets130** [microsoft/CSS-Exchange#586]
**Provide Version Number**
21.05.11.1059

**Describe the issue**
I ran the latest Healthchecker script, 21.05.11.1059, on both of my exchange servers and notice something odd. I ran the script on the 1st exchange server. Fully patched. The HTML report didn't report any vulnerabilities. 

Ran the script on the 2nd exchange server. Fully patched. It reported all the vulnerabilities from the Hafnium attack.

I also had the script output the txt and xml file. Open the file up and it doesn't show any vulnerabilities in either servers. So I ran other tools from Microsoft. Their tools shows that none of my servers needs an remediations.

Is there a HTML coding error in the Healthchecker script?

**Expected behavior**
Should a fully patch server shows the Hafnium vulnerabilities in the output?

**Additional context**

**Comment by dpaulson45** [comment]
@emptystreets130 can you email the files (HTML and XMLs) and show what you are talking about to ExToolsFeedback@microsoft.com

**Comment by emptystreets130** [comment]
Hmm. Odd. I ran the report again on both servers just now. No Hafnium vulnerabilities are listed on the server in question.

The previous report I had was right after I installed the May patch. I guess I had to recreated the xml file???

**Comment by dpaulson45** [comment]
@emptystreets130 correct the HTML report is based off the XML files in the current location. If you only ran the Health Checker against 1 server after installing the security path, then ran the HTML report while having other XML files in the director for other servers, it will report it based off what is in that XML file for those other servers.
