### ISSUE TITLE
Health Checker - Check certificate Secure Hash Algorithm (SHA) and show a warning for SHA-1

### ISSUE THREAD

**Issue by lusassl-msft** [microsoft/CSS-Exchange#589]
We should check the certificate Secure Hash Algorithm (SHA) in the certificate check and highlight if SHA-1 was used (it's considered weak).

**Comment by hmstorecenter-com** [comment]
@hmsc @hmstorecenter

**Comment by lusassl-msft** [comment]
Implemented with `v21.05.27.0855`

**Comment by hmstorecenter-com** [comment]
Whos is msft
