### ISSUE TITLE
Health Checker - Display the Exsetup.exe ProductVersion build number by default

### ISSUE THREAD

**Issue by lusassl-msft** [microsoft/CSS-Exchange#603]
PG decided to publish the build numbers for each Security Update (SU) starting with the March 2021 SU (see: https://docs.microsoft.com/en-us/Exchange/new-features/build-numbers-and-release-dates?view=exchserver-2019#exchange-server-2019). 
We display the build number (`AdminDisplayVersion`) returned by the `Get-ExchangeServer` cmdlet. However, the build number doesn't show the latest state in case a SU was installed. We should change our logic here and show the build number returned by `Get-Command Exsetup.exe | ForEach {$_.FileVersionInfo}` (we already have this information available).

**Comment by lusassl-msft** [comment]
@dpaulson45 Any thoughts or concerns?

**Comment by dpaulson45** [comment]
Give me a little bit to think about this. I think it might end up being a good idea if admins are confused about the build number vs the SU build.

**Comment by michelderooij** [comment]
Sorry to mingle. AdminDisplayVersion usually doesn't provide admins enough information, or hints at trailing. It's for this reason I have been keeping track of a ([builds](https://eightwone.com/references/versions-builds-dates/)) page for years.
