### ISSUE TITLE
[Issue] - Health Checker - Page File Size  and Sleepy Nic reports wrong result

### ISSUE THREAD

**Issue by megosugit** [microsoft/CSS-Exchange#608]
**Provide Version Number**
These issues have been present for a while, I have checked again today with 21.06.01.0625 and it is still the case.

**Describe the issue**
The script reports "Page File Size: Error: System is set to automatically manage the pagefile size.", however page file size is manually set as follow:
Automatically manage paging file size for all drives: unchecked
C: 3967-3967 (initial size - maximum size)
D: 32768-32768
E: None
F: None
G: None
H: None

The script reports "Sleepy NIC Disabled: False --- Warning: It's recommended to disable NIC power saving options" however the option "Allow the computer to turn off this device to save power" is disabled on the only NIC (vmxnet3 Ethernet Adapter).

**Expected behavior**
As the page file size is set manually, this error shouldn't appear while running the HealthChecker script.

Sleepy NIC shouldn't be reported as the option "Allow the computer to turn off this device to save power" is unchecked.

**Script Output**
Exchange Information
--------------------
        Name: *****
        Version: Exchange 2016 CU19
        Build Number: 15.1.2176.2
        Exchange IU or Security Hotfix Detected.
                Security Update for Exchange Server 2016 Cumulative Update 19 (KB5000871)
                Security Update for Exchange Server 2016 Cumulative Update 19 (KB5001779)
        Server Role: Mailbox
        DAG Name: Standalone Server
        AD Site: Default-First-Site-Name
        MAPI/HTTP Enabled: True
        Exchange Server Maintenance: Server is not in Maintenance Mode

Operating System Information
----------------------------
        Version: Microsoft Windows Server 2016 Standard
        System Up Time: 3 day(s) 17 hour(s) 46 minute(s) 2 second(s)
        Time Zone: Romance Standard Time
        Dynamic Daylight Time Enabled: True
        .NET Framework: 4.8
        **Page File Size: Error: System is set to automatically manage the pagefile size.**
        Power Plan: High performance
        Http Proxy Setting: <None>

NIC Settings Per Active Adapter
-------------------------------
        Interface Description: vmxnet3 Ethernet Adapter [LAN]
                Driver Date: 2019-07-11
                Driver Version: 1.8.16.0
                MTU Size: 1500
                Max Processors: 6
                Max Processor Number: 5
                Number of Receive Queues: 4
                RSS Enabled: True
                Link Speed: 10000 Mbps --- This may not be accurate due to virtualized hardware
                IPv6 Enabled: True
                IPv4 Address:
                        Address: 192.168.*.*\24 Gateway: 192.168.*.*
                IPv6 Address:
                DNS Server: 192.168.*.* 192.168.*.*
                Registered In DNS: True
                Sleepy NIC Disabled: False --- Warning: It's recommended to disable NIC power saving options
                        More Information: http://support.microsoft.com/kb/2740020

**Additional context**

**Comment by lusassl-msft** [comment]
@megosugit could you please run the script with the `-SaveDebugLog` switch and send us the output to `extoolsfeedback [AT] Microsoft [DOT] com?`

**Comment by megosugit** [comment]
I have sent the requested logs. Good luck :)

**Comment by megosugit** [comment]
Hello,

did you receive the logs properly ? Did you find any clue in the logs ?

**Comment by lusassl-msft** [comment]
@megosugit yep, I've received the logs but had not time yet to check them. It's scheduled for next week. I'll keep you posted (via mail).

**Comment by megosugit** [comment]
ok great, thank you

**Comment by dpaulson45** [comment]
The issue with the page file here is the fact that we have two page files. Current bug in code is here: 

```
Function Get-PageFileInformation {

    Write-Verbose "Calling: $($MyInvocation.MyCommand)"
    [HealthChecker.PageFileInformation]$page_obj = New-Object HealthChecker.PageFileInformation
    $pageFile = Get-WmiObjectHandler -ComputerName $Script:Server -Class "Win32_PageFileSetting" -CatchActionFunction ${Function:Invoke-CatchActions}

    if ($null -ne $pageFile) {
        if ($pageFile.GetType().Name -eq "ManagementObject") {
            $page_obj.MaxPageSize = $pageFile.MaximumSize              <---- only setting the value if we have a non array returned. 
        }
        $page_obj.PageFile = $pageFile
    } else {
        Write-Verbose "Return Null value"
    }

    Write-Verbose "Exiting: $($MyInvocation.MyCommand)"
    return $page_obj
}

```

Need to handle multi page files better.

**Comment by dpaulson45** [comment]
link #717

**Comment by dpaulson45** [comment]
From the debug log, we appear to not find any values in the registry for 001-003 which causes this to stop processing and failing to possibly find the correct values here.

I wonder if there is a similar way to do a `Get-ChildItem` against this location in the registry with opening of the registry. If there isn't, we could create a script block that will use `Get-ChildItem` within an `Invoke-Command` to allow the action to be taken remotely as well. This way we can query all the items and not have an arbitrary retry counter when there are more items to be testing against.
