### ISSUE TITLE
[Issue] Zip file check fails on Windows 2019

### ISSUE THREAD

**Issue by bill-long** [microsoft/CSS-Exchange#62]
Test-Hafnium is showing an error on Windows 2019. I can reproduce this on Exchange 2019 in my lab:

```
Get-ChildItem : Access is denied
At C:\Users\Administrator\Desktop\Test-Hafnium.ps1:95 char:17
+ ... $zipFiles = Get-ChildItem -Recurse -Path "$env:ProgramData" -Include  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ChildItem], UnauthorizedAccessException
    + FullyQualifiedErrorId : System.UnauthorizedAccessException,Microsoft.PowerShell.Commands.GetChildItemCommand
```

**Comment by bill-long** [comment]
The only way I can get this working is filtering after the Get-ChildItem...

![image](https://user-images.githubusercontent.com/4518572/110065795-a0d53c80-7d35-11eb-8f9d-f95aea0b55fb.png)

Is that our only option?

**Comment by bill-long** [comment]
So basically, -ErrorAction SilentlyContinue does not work when you have the -Include parameter in there.

**Comment by dpaulson45** [comment]
Doesn't work for me at all finding the file

**Comment by bill-long** [comment]
Yeah the -or is not working. It only finds the first extension listed in that where clause.

**Comment by dpaulson45** [comment]
![image](https://user-images.githubusercontent.com/22776718/110066709-b481a280-7d37-11eb-87d5-59ac9407b3a9.png)

only other option would be to use `-Filter ` which wouldn't be as nice either but an option.

**Comment by bill-long** [comment]
This seems to work:

![image](https://user-images.githubusercontent.com/4518572/110066859-0cb8a480-7d38-11eb-9363-9dce5dc76cb9.png)
