### ISSUE TITLE
SetupAssist and HealthChecker look for different VC++ 2013 versions

### ISSUE THREAD

**Issue by bill-long** [microsoft/CSS-Exchange#629]
SetupAssist:

![image](https://user-images.githubusercontent.com/4518572/126393931-2107328f-34ee-4446-acac-095cb24f1fa9.png)

HealthChecker:

![image](https://user-images.githubusercontent.com/4518572/126393986-d8eed6e4-a062-4c4b-8315-9d8e397dcb9e.png)

Whatever we do here, we might want to change this check into a shared function so the code stays in sync between the two scripts.

**Comment by dpaulson45** [comment]
What i am thinking currently is the following. 

- Create 3 different functions. 
  -  Get-VisualCRedistributableVersion  -- likely from https://github.com/microsoft/CSS-Exchange/blob/main/Shared/Get-VisualCRedistributableVersion.ps1
  -  Test-VcRedistributableVersion2012 
  -  Test-VcRedistributableVersion2013 

The Test functions knows the object structure that is returned from `Get-VisualCRedistributableVersion` and they contain the correct version that we want to be testing against and how and just returns a boolean. 

Do the same type of function logic that we have here. 

https://github.com/microsoft/CSS-Exchange/blob/main/Search/Troubleshoot-ModernSearch/StoreQuery/StoreQueryFunctions.ps1

Sample Code: 
```
$visualCRedistributableVersion = Get-VisualCRedistributableVersion  -ComputerName E19A
...
$vc2012 = $visualCRedistributableVersion | Test-VcRedistributableVersion2012
$vc2013 = $visualCRedistributableVersion | Test-VcRedistributableVersion2013
if ($vc2012) {
   Write-Host "Current 2012"
} else { Write-Host "not current 2012" }

if ($vc2013) {
   Write-Host "Current 2013"
} else { Write-Host "not current 2013" }

```

@bill-long what are your thoughts?

**Comment by bill-long** [comment]
That sounds fine to me. That allows us to cut out most of the code from Test-PrerequisiteInstalled and just do:

```
if (-not Test-VcRedistributableVersion2012) {
    "Download Visual C++ 2012 blahblah..."
}
```

**Comment by dpaulson45** [comment]
Cool, so should we collapse all the functions here into a single file in Share? Keep them under Get-VisualCRedistributableVersion.ps1 or do VisualCRedistributableVersionFunctions.ps1?
