### ISSUE TITLE
[Work Item] add web.config check

### ISSUE THREAD

**Issue by tweekerz** [microsoft/CSS-Exchange#651]
Need to add a check to validate all the web.config files have the HttpRequestFilteringModule in them

**Comment by dpaulson45** [comment]
@tweekerz  we have some code already out there in Health Checker that does find the Web.config file for the app pools. We can create a Shared function that we can use in both Health Checker and Test-AMSI. Let me know what you all need.

**Comment by tweekerz** [comment]
@dpaulson45 are you parsing the web.configs for what's within them? I am basically working with GCI and select-string for the module Like this:

Get-ChildItem -Recurse -Path '$installpath' -Filter web.config | Select-String HttpRequestFilteringModule | Select-Object -ExpandProperty Path 

Then I would need to sort and compare and notify on the web.configs that are missing HttpRequestFilteringModule

**Comment by dpaulson45** [comment]
@tweekerz I am not currently parsing them. I collect them or I also do this with gathering the Web App information. 

https://github.com/microsoft/CSS-Exchange/blob/main/Diagnostics/HealthChecker/DataCollection/ExchangeInformation/Get-ExchangeAppPoolsInformation.ps1

Is Test-AMSI able to be run remotely? If it is, this might be something that we should tackle and place in Shared. Something that at least collects the config file location/content to be able to parse out the information.

**Comment by dpaulson45** [comment]
@tweekerz recently created this logic, wouldn't be hard to include what you are looking for was well.

https://github.com/microsoft/CSS-Exchange/blob/main/Diagnostics/HealthChecker/DataCollection/ExchangeInformation/Get-ExchangeIISConfigSettings.ps1
