### ISSUE TITLE
[Issue] add German localization for IIS HTTP 400 Error

### ISSUE THREAD

**Issue by tweekerz** [microsoft/CSS-Exchange#652]
**Describe the issue**
Running the Test-AMSI script on an Exchange server that has a different OS language than English (German in my case) will lead to the warning message that AMSI may be disabled, as the script checks for the English error message of the code 400 / Bad Request that is returned. The test is working fine despite of this, code 400 is returned, and the detection is logged. And a Microsoft 365 Defender alert was triggered, as we've onboarded the Exchange servers to Defender for Endpoint. Of course, you can change the script and add the error message in the OS language if you want it to display the correct result.

**Expected behavior**
A correct localized message

**Comment by Pamor-vlz** [comment]
German HTTP 400 error message is:
Der Remoteserver hat einen Fehler zurückgegeben: (400) Ungültige Anforderung

So line 47
If ($_.Exception.Message -notlike "*The remote server returned an error: (400) Bad Request*") {

could be changed to
If ($_.Exception.Message -notlike "*The remote server returned an error: (400) Bad Request*" -and $_.Exception.Message -notlike "*Der Remoteserver hat einen Fehler zurückgegeben: (400) Ungültige Anforderung*") {

This will of course become unwieldy if you add localization for more languages this way.

**Comment by tweekerz** [comment]
@Pamor-vlz I need to see if there is a way to pull localized errors, because I agree this would get out of hand quickly. Not crazy about this idea but I think this may work short term. Can you change your line 47 to the below and test?

If ($_.Exception.Message -notlike "*: (400)*") {

**Comment by Pamor-vlz** [comment]
@tweekerz Test was successful, that line does work:

`If ($_.Exception.Message -notlike "*: (400)*") {`
