### ISSUE TITLE
[Issue] Invoke-ScriptAnalyzer isn't catching all the rules like it use to

### ISSUE THREAD

**Issue by dpaulson45** [microsoft/CSS-Exchange#682]
**Describe the issue**
Recently found that an alias was able to get by the build process. After looking into it, we found that it wasn't catching a few of the rules. 

**Expected behavior**
We should be using all the default rules by default, then excluding the rules that we want. 

**Additional context**

Removing this section of the `PSScriptAnalyzerSettings.psd1` allows all the rules to take effect.
```
    IncludeRules        = @(
        'PSPlaceOpenBrace',
        'PSPlaceCloseBrace',
        'PSUseConsistentWhitespace',
        'PSUseConsistentIndentation',
        'PSAlignAssignmentStatement',
        'PSUseCorrectCasing'
    )
```
Not fully sure why this was this way to begin with, as it was working initially. A possibility is that something was changed when merging HealthChecker or ExchangeLogCollector if they had these settings. Either way, need to revert this change and which requires going through all the error the script is now producing.

**Comment by bill-long** [comment]
PSReviewUnusedParameter is generating a ton of false positives. I think we should just exclude it. There has been an issue open for a year at PowerShell/ScriptAnalyzer#1472 with no fix in sight.
