### ISSUE TITLE
Health Checker should check Recycling settings

### ISSUE THREAD

**Issue by bill-long** [microsoft/CSS-Exchange#692]
Setting Recycling Settings on an IIS vdir will cause the app pool to recycle periodically, resulting in a short outage.

Health Checker should validate these settings to make sure we are not configured for self-inflicted outages.

**Comment by dpaulson45** [comment]
Related to #537

**Comment by michelderooij** [comment]
Disagree - setting AutoD recycling to recycle every hour or so is good practice in hybrid deployments to provide clients with accurate information after on- or offboarding.

**Comment by bill-long** [comment]
@michelderooij We've had a series of support cases from customers getting 503's from Autodiscover - in the latest case case, every 30 minutes - due to recycling. Even if recycling is useful when moving mailboxes between on-prem and cloud, the setting needs to be called out to stop people from opening support cases on hourly (or half-hourly) 503's.

Do you have any more information on what Autodiscover caches _for more than an hour_ that makes recycling useful? Is this in an EHLO blog post or a best practices document somewhere? That's a very long cache lifetime, rivalling the good old 2-hour MBI cache.

**Comment by dpaulson45** [comment]
@bill-long the latest case was actually regarding EAS, they just so happened to also set the AutoD app pool as well to recycle. 

@michelderooij Unless customer are moving mailbox without the wait for complete option, meaning they have to manually cut over the mailboxes or wait for a particular time, there should be no reason to automatically restart AutoD App Pool during the migration process. You should only need to do it 1 time after AD has been properly updated.

Even with that being said, AutoD is the only app pool that you can argue for the automatic restarts. Even though it shouldn't be done in my opinion. The other app pools where we have seen actual cases on, like `MSExchangeSyncAppPool` and `MSExchangeMapiMailboxAppPool` this should **never** be set for this feature.

**Comment by bill-long** [comment]
Ah, thanks. Got my app pools confused.

**Comment by michelderooij** [comment]
We seldomly onboard customers in batches using the CompleteAfter, given the additional work/fixing that usually also needs to take place. Real-life on/offboarding is a process, involving additional tasks which need to take place pre and post. We never seen customers reporting 503's. We usually configure an interval to to accommodate emergency on/offboarding (eg mailboxes missed or ones that shouldn't have been processed) when we can't remotely trigger a recycle over all Exchange boxes, and when waiting for the (next) scheduled post-migration recycle isn't an option. But since this isn't about the migration, you could check DNS and only report configured recycle settings if the AutoD DNS record points to the outlook-s redirector.

**Comment by dpaulson45** [comment]
@michelderooij What is the reason to recycle the app pool every hour? This should have been fixed within Exchange 2013 CU13 when we switched the cache to be recycled every hour. You are virtually doing the same thing, except with the code fix it still allows clients to get processed. 

https://support.microsoft.com/en-us/topic/outlook-client-remains-disconnected-after-the-mailbox-is-migrated-to-exchange-server-2013-3bdf4bf9-c524-bd69-b7a3-5e58768173ec

the only benefit you have is to recycle right after the cut over. Which you would need to do manually. 

You can also remotely recycle all the Exchange Servers AutoD app pools. 

Sample:

```
Invoke-Command -ComputerName "ListOfExchangeServers" -ScriptBlock { & "$env:windir\system32\inetsrv\appcmd.exe" recycle apppool MSExchangeAutodiscoverAppPool } 
```

**Comment by michelderooij** [comment]
Thanks, David. I'm aware of the process and procedures.
