### ISSUE TITLE
[Issue] - Health Checker

### ISSUE THREAD

**Issue by tortoise62** [microsoft/CSS-Exchange#712]
Exchange Health Checker version 21.08.18.1724

**Describe the issue**
Under Server Details, the "MAPI Front End App Pool GC Mode" isn't reflecting the value contained in "C:\Program Files\Microsoft\Exchange Server\V15\Bin\MSExchangeMapiFrontEndAppPool_CLRConfig.config".  
File contents:
![2021-08-23 01_34_52-_LAS-LAW - TeamViewer](https://user-images.githubusercontent.com/89381939/130416748-92e36a31-9743-4605-845d-5f32ff163b06.png)

**Expected behavior**
No error should have been flagged as value of GCserver is "true" already.   Exchange Health Checker v21.07.13.1221 did not report this as an error.

**Script Output**
LINE 23 of the Exchange Health Checker version 21.08.18.1724
MAPI Front End App Pool GC Mode: Workstation --- Error
To Fix this issue go into the file MSExchangeMapiFrontEndAppPool_CLRConfig.config in the Exchange Bin directory and change the GCServer to true and recycle the MAPI Front End App Pool
![2021-08-23 01_16_28-2021 08 22-LPS-Exch2013-Report html and 12 more pages - Personal - Microsoft​ Ed](https://user-images.githubusercontent.com/89381939/130415995-3486808c-4197-46d7-befd-ec341510838f.png)
![2021-08-23 01_27_47-_LAS-LAW - TeamViewer](https://user-images.githubusercontent.com/89381939/130416003-a477e95d-0b17-49de-9cf2-c8b4dc72d7db.png)
![2021-08-23 01_05_10-Computed Diff - Diff Checker and 19 more pages - Personal - Microsoft​ Edge](https://user-images.githubusercontent.com/89381939/130416048-dcbc88fd-502a-40eb-b073-195e0a0e5784.png)
![2021-08-23 01_04_53-Computed Diff - Diff Checker and 19 more pages - Personal - Microsoft​ Edge](https://user-images.githubusercontent.com/89381939/130416053-92762567-e6d9-4dfc-86d0-54a96a6895bf.png)

**Additional context**
Line 23 of the Exchange Health Checker version 21.07.13.1221
MAPI Front End App Pool GC Mode: Server

**Comment by dpaulson45** [comment]
@tortoise62 thanks for the heads up. This is now fixed in the latest release of the Health Checker.
