### ISSUE TITLE
[Work Item] Improve PageFile object logic

### ISSUE THREAD

**Issue by dpaulson45** [microsoft/CSS-Exchange#717]
**Describe the work**
Currently only provide if auto page is set or not. Currently not doing that even correctly when multiple page files are detected. 

Look at creating a new view for this:

```
Page File:

          Location              Size
          ----------             -----
          c:\pagefile.sys      32778
```

This will be a list for each of the page files, providing a new `Out-Columns` view. Where `Size` is `0` automatic system manage is set and is incorrect and additional wording is provided. Same goes if multiple page files are detected.

**Comment by ildjarnisdead** [comment]
This seems to fix at least the error that no page file was detected when there are multiple files:

`
Function Get-PageFileInformation {

    Write-Verbose "Calling: $($MyInvocation.MyCommand)"
    [HealthChecker.PageFileInformation]$page_obj = New-Object HealthChecker.PageFileInformation
    $pageFile = Get-WmiObjectHandler -ComputerName $Script:Server -Class "Win32_PageFileSetting" -CatchActionFunction ${Function:Invoke-CatchActions}

    if ($null -ne $pageFile) {
        foreach ($pfile in $pageFile) {
            if ($pfile.GetType().Name -eq "ManagementObject") {
                $page_obj.MaxPageSize += $pfile.MaximumSize
            }
        }
        $page_obj.PageFile = $pageFile
    } else {
        Write-Verbose "Return Null value"
    }

    Write-Verbose "Exiting: $($MyInvocation.MyCommand)"
    return $page_obj
}
`

**Comment by dpaulson45** [comment]
Can't have MaxPageSize added up between all the page files. That isn't the intent.
