### ISSUE TITLE
[Issue] Write-Host function doesn't work properly when used in PS ISE

### ISSUE THREAD

**Issue by lusassl-msft** [microsoft/CSS-Exchange#718]
**Describe the issue**
The newly introduced shared `Write-Host` function doesn't work in PowerShell ISE. 
ISE makes use of the `Windows Presentation Foundation (WPF)` (https://docs.microsoft.com/en-us/dotnet/api/system.windows.media?view=net-5.0) and so, calls like `$host.PrivateData.WarningForegroundColor` return color settings in `System.Windows.Media.Color` which cannot be converted to type `System.ConsoleColor` which is expected when calling `Microsoft.PowerShell.Utility\Write-Host @params`.

Issue reported by a customer.

**Script Output**
```
Write-Host : Cannot bind parameter 'ForegroundColor'. Cannot convert the "#FFFF8C00" value of type "System.Windows.Media.Color" to type "System.ConsoleColor".
At C:\Users\Administrator\Desktop\hcold\HealthChecker.ps1:6069 char:5
+     Write-Host $message -ForegroundColor Yellow
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Write-Host], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Write-Host
```

**Additional context**
Possible solution could be to introduce another helper function which checks if the script is executed in PowerShell ISE `$host.Name -eq "Windows PowerShell ISE Host"` and if so, add the following assembly: `Add-Type -AssemblyName PresentationCore` (should be loaded by default when using ISE), ~~load the ColorConverter class `$colorConverter = New-Object System.Windows.Media.ColorConverter`, convert the `System.Windows.Media.Color` to string via `$color = ($colorConverter).ConvertToString($ForegroundColor)`~~., create a hashtable and map the ARGB value to the color property.
```
if ($null -eq $Script:colorCustomObject) {
    $Script:colorHashTable=@{}
    [Windows.Media.Colors] | Get-Member -Static -Type Property | Select-Object -Expand Name | ForEach-Object {
        $Script:colorHashTable.Add($_, "$([Windows.Media.Colors]::$_)")
    }
}
```
However, it's complex and I'm not sure if it's worth it.

**Comment by lusassl-msft** [comment]
Assigned to @bill-long as owner of this shared function.

**Comment by dpaulson45** [comment]
I actually wrote that function. 

The first question is should we support ISE?

**Comment by lusassl-msft** [comment]
Oops. I think it's not required for running the scripts but might be useful for debugging purpose.

**Comment by bill-long** [comment]
It looks like a string works in both scenarios. Can we store and pass a string instead of an object? In other words, `Write-Host Hi ForegroundColor "Red"` works just as well in ISE as it does in the normal powershell console.

**Comment by dpaulson45** [comment]
@bill-long  the issue isn't with the object vs the string type, it is how the color is stored in ISE. 

```
 $host.UI.RawUI.ForegroundColor
-1

$host.PrivateData


Window                                    : Microsoft.Windows.PowerShell.Gui.Internal.MainWindow
SelectedScriptPaneState                   : Top
ShowDefaultSnippets                       : True
ShowToolBar                               : True
ShowOutlining                             : True
ShowLineNumbers                           : True
TokenColors                               : {[Attribute, #FF00BFFF], [Command, #FF0000FF], [CommandArgument, #FF8A2BE2], [CommandParameter, #FF000080]...}
ConsoleTokenColors                        : {[Attribute, #FFB0C4DE], [Command, #FFE0FFFF], [CommandArgument, #FFEE82EE], [CommandParameter, #FFFFE4B5]...}
XmlTokenColors                            : {[Comment, #FF006400], [CommentDelimiter, #FF008000], [ElementName, #FF8B0000], [MarkupExtension, #FFFF8C00]...}
DefaultOptions                            : Microsoft.PowerShell.Host.ISE.ISEOptions
FontSize                                  : 9
Zoom                                      : 100
FontName                                  : Lucida Console
ErrorForegroundColor                      : #FFFF9494
ErrorBackgroundColor                      : #00FFFFFF
WarningForegroundColor                    : #FFFF8C00
WarningBackgroundColor                    : #00FFFFFF
VerboseForegroundColor                    : #FF00FFFF
VerboseBackgroundColor                    : #00FFFFFF
DebugForegroundColor                      : #FF00FFFF
DebugBackgroundColor                      : #00FFFFFF
ConsolePaneBackgroundColor                : #FF012456
ConsolePaneTextBackgroundColor            : #FF012456
ConsolePaneForegroundColor                : #FFF5F5F5
ScriptPaneBackgroundColor                 : #FFFFFFFF
ScriptPaneForegroundColor                 : #FF000000
ShowWarningForDuplicateFiles              : True
ShowWarningBeforeSavingOnRun              : True
UseLocalHelp                              : True
AutoSaveMinuteInterval                    : 2
MruCount                                  : 10
ShowIntellisenseInConsolePane             : True
ShowIntellisenseInScriptPane              : True
UseEnterToSelectInConsolePaneIntellisense : True
UseEnterToSelectInScriptPaneIntellisense  : True
IntellisenseTimeoutInSeconds              : 3
```

The entire reason to create this function was to have "Yellow" text show up as the same as custom Warning settings in the PowerShell setting. Some goes for "Red" as Error and if the custom setting has the same color as one of these to, change it to Grey by default.

**Comment by bill-long** [comment]
I thought surely there is a way to convert them, but there isn't. Write-Host requires a System.ConsoleColor, and the default colors in ISE won't convert. Example:

```
> [Enum]::GetNames([System.ConsoleColor]) | % { [PSCustomObject]@{Name = $_; Number = [System.Drawing.Color]::FromName($_).ToArgb().ToString("X")} }

Name        Number  
----        ------  
Black       FF000000
DarkBlue    FF00008B
DarkGreen   FF006400
DarkCyan    FF008B8B
DarkRed     FF8B0000
DarkMagenta FF8B008B
DarkYellow  0       
Gray        FF808080
DarkGray    FFA9A9A9
Blue        FF0000FF
Green       FF008000
Cyan        FF00FFFF
Red         FFFF0000
Magenta     FFFF00FF
Yellow      FFFFFF00
White       FFFFFFFF
```

```
> $host.PrivateData.ErrorForegroundColor.ToString()
#FFFF9494
```

The default ISE error color is basically pink, not red. There is no equivalent in System.ConsoleColor, so it's impossible to Write-Host with a -ForegroundColor value that matches the configured color in ISE.

Ugh.

In this scenario I suggest we just have a reasonable default. If the user wants their color choices respected, they need to use something other than ISE. Even VSCode is fine.

**Comment by dpaulson45** [comment]
Which brings up do we want to support ISE for the scripts. 

If we do, there is a way to do this, just gets to be a little complicated is all.

**Comment by bill-long** [comment]
I think *basic* ISE support (using a default color and ignoring user preferences) is good enough. I don't think we should add a bunch of complicated code for this scenario.
