### ISSUE TITLE
Feature Request HC: Check for HealtMailbox status

### ISSUE THREAD

**Issue by grimson73** [microsoft/CSS-Exchange#766]
**Is your request related to a problem? Please describe.**
Get-Mailbox -Monitoring can be used to verify the state of the HealthMailboxes. Only (to my knowledge) then you can obtain the health of these mailboxes to your surprise.

**Describe The Request**
Sometimes the following output can be expected:
WARNING: The object customer.local/Microsoft Exchange System Objects/Monitoring Mailboxes/HealthMailbox42c7f554cbd5455c999493c924323d33 has been corrupted or isn't compatible with Microsoft support requirements, and it's in an inconsistent state. The following validation errors happened:
WARNING: Database is mandatory on UserMailbox.
WARNING: Database is mandatory on UserMailbox.

You do have then to correct this, but my guess this will be overseen sometimes these errors because of (at least for me) I am not looking (just now I will) actively in those Healthmailboxes.

Therefore a request to add the HealthMailbox state to the HealthChecker script. Just to hint the Admin who executes the HC script to examine these mailboxes.
Thanks! :)

**Comment by dpaulson45** [comment]
Closing out. Hard to do for Monitoring mailboxes, goes beyond scope of the Health Checker, and if anything would be another script with little value add at this time.
