### ISSUE TITLE
[Issue] SourceSideValidations - Example for disabling mail-enabled system public folder wrong

### ISSUE THREAD

**Issue by Apoc70** [microsoft/CSS-Exchange#772]
**Describe the issue**
The PowerShell output for disabling a mail-enabled system folder does not work.
In that particular case, even an adjusted Disable-MailPublicFolder did not work. There was no corresponding MESO for this folder (EFORMS REGISTRY), but the public folder object parameter MailEnabled was $true.
A Set-PublicFolder [PFID] -MailEnabled:$false solved the issue.

The hashtable provided by SSV results in an error message.

**Expected behavior**
The output example should provide code for disabling the mail-enabled folder.

**Script Output**
```powershell
# Original output
Import-Csv .\ValidationResults.csv |
 ? ResultType -eq MailEnabledSystemFolder |
% { Disable-MailPublicFolder @{TestName=Permission;
ResultType=Duration; Severity=Information; FolderIdentity=;
FolderEntryId=; ResultData=01:00:41.1242214}.FolderIdentity }
```
 
```powershell
# Updated output 
Import-Csv .\ValidationResults.csv |
 ? ResultType -eq MailEnabledSystemFolder |
% { Disable-MailPublicFolder $_.FolderEntryId -Confirm:$false}
```

**Comment by bill-long** [comment]
Closing pending further information.
