### ISSUE TITLE
[Issue] SourceSideValidations - Script failes to remove public client permission - ADCDisabledMail

### ISSUE THREAD

**Issue by Apoc70** [microsoft/CSS-Exchange#773]
**Describe the issue**
The script fails to remove public folder client permissions for security groups that are already mail-disabled with the error 'Multiple objects with legacy DN ADCDisabledMail were found.'

**Expected behavior**
The script should try removing the permission in a try/catch block, providing additional guidance on how to clean up "unremovable" client permission. 

**Script Output**
```powershell

.\SourceSideValidations.ps1 -RemoveInvalidPermissions

Removing disabled_SomeSecurityGroup from folder \PFFolderA\PFFolderAB\SomeFolder/Title
Multiple objects with legacy DN ADCDisabledMail were found.
    + CategoryInfo          : NotSpecified: (:) [Remove-PublicFolderClientPermission], 
NonUniqueLegacyExchangeDNException
    + FullyQualifiedErrorId : [Server=MX1911,RequestId=07df1adf-1a8e-4b1a-8f76-25fe0322d9b7,TimeStamp=10/13/2021 
12:53:57 PM] [FailureCategory=Cmdlet-NonUniqueLegacyExchangeDNException] 
E6AC41,Microsoft.Exchange.Management.StoreTasks.RemovePublicFolderClientPermission
    + PSComputerName        : mx1911.varunagroup.de
Multiple objects with legacy DN ADCDisabledMail were found.
    + CategoryInfo          : NotSpecified: (:) [Remove-PublicFolderClientPermission], NonUniqueLegacyExchangeDNExcept
   ion
    + FullyQualifiedErrorId : [Server=MX1911,RequestId=07df1adf-1a8e-4b1a-8f76-25fe0322d9b7,TimeStamp=10/13/2021 12:
   53:57 PM] [FailureCategory=Cmdlet-NonUniqueLegacyExchangeDNException] E6AC41,Microsoft.Exchange.Management.StoreTasks.RemovePublicFolderClientPermission
    + PSComputerName        : mx1911.varunagroup.de

# providing just one example of multiple errors of that kind
```

**Comment by bill-long** [comment]
Hi @Apoc70, the problem isn't that the group is mail-disabled. Rather, the problem is that it has a non-unique legacyExchangeDN of "ADCDisabledMail". This must be a _very_ old group, as this would have been stamped by the Active Directory Connector back in the Exchange 2000/2003 timeframe.

To fix this, you'll need to clear the legacyExchangeDN value from the Active Directory objects. To identify all such objects, run the following command:

`ldifde -t 3268 -r "(legacyExchangeDN=ADCDisabledMail)" -l distinguishedName -f ObjectsWithADCDisabledMail.txt`

**Comment by bill-long** [comment]
I'm trying to figure out if there's any scenario where we would _not_ want the script to automatically clear the legacyExchangeDN when it is set to this value.

**Comment by Apoc70** [comment]
Hi @bill-long,
That's what struggling with me. The Exchange org is quite old but runs Exchange 2016 and Exchange 2019 only. Public folder mailbox moves from 2016 to 2019 fail due to public folder ACL issues. The SSC script identified the issues quire easily. 
There was no ACL-related issue when moving PF mailboxes from 2013 to 2016. 
We've already identified the objects, some were created in legacy Exchange, ~50% were created in a modern Exchange version. That's why I wonder that the ADCDisabledMail is stamped on those objects. The group mentioned in the example got disabled while in an Exchange 2016 only environment.

**Comment by bill-long** [comment]
@Apoc70 I just searched the Exchange 2013 and 2016 code, and I can't find anything that sets ADCDisabledMail. The most recent code I can find that even looks for this value is Exchange 2010. I'm completely baffled as to how this could get set in Exchange 2016.

I think what we'll do is test for this situation when we run the invalid permissions test, and we'll produce a different result type, like InvalidPermissionWithAmbiguousLegacyDN. Then, when fixing the permissions. we'll use this result type to indicate that we need to clear the legacyExchangeDN, pause a few seconds to allow replication, and then proceed with removal.

**Comment by bill-long** [comment]
Closing for now as I'm not sure what to do here. Hopefully this is a rare case.
