### ISSUE TITLE
[Issue] - Health Checker shows unhandled error after successful run

### ISSUE THREAD

**Issue by lusassl-msft** [microsoft/CSS-Exchange#777]
**Provide Version Number**
21.10.12.1555

**Describe the issue**
Multiple customers reporting an issue with the latest script version. The script runs properly but shows the issue warning (_There appears to have been some errors in the script. To assist with debugging of the script, please send the HealthChecker-Debug*.txt, HealthChecker-Errors.json, and .xml file to [redacted]._) at the end of the run. 

**Script Output**
In all cases, the following unhandled error is listed at the end of the display output:
```
Errors that occurred that wasn't handled
Error Index: 1
You cannot call a method on a null-valued expression.
at <ScriptBlock>, <No file>: line 2
at <ScriptBlock>, <No file>: line 465
at <ScriptBlock>, <No file>: line 462
at Write-Errors, D:\Exchange Update\HealthChecker.ps1: line 5662
at Get-ErrorsThatOccurred, D:\Exchange Update\HealthChecker.ps1: line 5704
at <ScriptBlock>, D:\Exchange Update\HealthChecker.ps1: line 7615
at <ScriptBlock>, <No file>: line 1
-----------------------------------
```

**Comment by lusassl-msft** [comment]
Had a debug session with an affected customer. It looks like we run into the following problem that causes the behavior reported by multiple customers:

```
An error occurred while enumerating through a collection: Collection was modified; enumeration operation may not execute..
In C:\install\HealthChecker.ps1:5676 Zeichen:13
+             $Error | ForEach-Object {
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Collecti...numeratorSimple:ArrayListEnumeratorSimple) [], Runt
   imeException
    + FullyQualifiedErrorId : BadEnumeration

Die Sammlung wurde geändert. Der Enumerationsvorgang kann möglicherweise nicht ausgeführt werden.
```

A similar issue was fixed within PS7: https://github.com/PowerShell/PowerShell/issues/11459

**Comment by lusassl-msft** [comment]
Worked together with a customer who ran into the same issue but only on Server 2012 R2. I noticed that a call like this failed and caused an unexpected failure:

`$local:AmsiInitFailed = [Ref].Assembly.GetType(\u0027System.Management.Automation.AmsiUtils\u0027).GetField(\u0027amsiInitFailed\u0027,\u0027NonPublic,Static\u0027).GetValue($null)\r\n"`

This call queries the status of the AMSI which is not available on Server 2012 R2. It was caused by SentinelOne EDR solution. If EDR is disabled on Server 2012 R2, the script runs fine. If it's enabled, the script reports an unhandled error.

**Comment by lusassl-msft** [comment]
Confirmed with another customer. After SentinelOne EDR was temporarily disabled, the script runs without any issue.

**Comment by lusassl-msft** [comment]
Customer has an open support case with SentinelOne to clarify if the behavior (calling the AMSI Interface settings) is expected on Server 2012 R2 (no AMSI available) or not. If it's expected, we then must think about our error handling to catch these unexpected errors.

**Comment by dpaulson45** [comment]
@lusassl-msft any updates on this?

**Comment by lusassl-msft** [comment]
@dpaulson45 Customer is still in contact with SentinelOne. Current workaround to mitigate this on Server 2012 (R2) is to disable the EDR PowerShell script engine.

**Comment by lusassl-msft** [comment]
![image](https://user-images.githubusercontent.com/40993616/149508727-6023d081-11f5-4514-a116-05b2300ab36f.png)

**Comment by grimson73** [comment]
![image](https://user-images.githubusercontent.com/45716059/152164729-425e4213-c98a-414c-b256-905dac1a44d4.png)

FWIW:
Windows Server 2012 R2 - Exchange 2013 - Sentinel One -> OK
SentinelInstaller-x64_windows_64bit_v21_7_4_1043.exe -> v21.7 SP1

**Comment by lusassl-msft** [comment]
Thanks @grimson73. So, it works for you with version `21.7.4.1043` and EDR PowerShell script engine turned on?

**Comment by grimson73** [comment]
![image](https://user-images.githubusercontent.com/45716059/152369268-ebab4c07-bd78-473b-871c-e06171122887.png)
![image](https://user-images.githubusercontent.com/45716059/152369382-b3f9fa0b-d323-4710-b241-8ca17ad2042d.png)
My MSP collogues who are in control of S1 told me that the Script Engine was enabled indeed. So based on this it should align with the S1 promise that SP1 would fix this. Curiously as I am, I try to find another S1 / Exchange Server and test if they let me :) will eventually post the results if possible. thank you!

**Comment by grimson73** [comment]
Found another Windows Server 2012 R2 with Exchange Server 2013 CU23
- Ran the Exchange Health Checker version 22.02.01.1135 -> no script errors
- Sentinelone client v27.7.4.1043 (assuming the same settings -> script scan on)

**Comment by lusassl-msft** [comment]
Great news! Thanks for letting me know @grimson73. Will confirm with other customers who reported this issue before closing the work item.

**Comment by lusassl-msft** [comment]
Going to close this issue now. Talked to multiple customers and they all confirmed that it was fixed by the latest SentinelOne EDR version.
