### ISSUE TITLE
[Work Item] - HealthChecker - Verify SharedWebConfig.Config exist in the Client Access and HTTPProxy folder

### ISSUE THREAD

**Issue by Logonzal** [microsoft/CSS-Exchange#809]
$MsiInstallPath = (Get-ItemProperty HKLM:\SOFTWARE\Microsoft\ExchangeServer\v15\Setup).MsiInstallPath
$SharedWebConfigHttpProxyFile = $MsiInstallPath + "FrontEnd\HttpProxy\SharedWebConfig.config"
$SharedWebConfigClientAccessFile = $MsiInstallPath + "ClientAccess\SharedWebConfig.config"
$TestPathSharedWebConfigHttpProxyFile = Test-Path -path $SharedWebConfigHttpProxyFile
$TestPathSharedWebConfigClientAccessFile = Test-Path -path $SharedWebConfigClientAccessFile

If ($TestPathSharedWebConfigHttpProxyFile -eq $false) {
Write-Host -ForegroundColor Red "Cannot find path $SharedWebConfigHttpProxyFile because it does not exist. Follow the resolution steps in the article to restore. https://aka.ms/recreate-sharedwebconfig `n"
}

If ($TestPathSharedWebConfigClientAccessFile -eq $false) {
Write-Host -ForegroundColor Red "Cannot find path $SharedWebConfigClientAccessFile because it does not exist. Follow the resolution steps in the article to restore. https://aka.ms/recreate-sharedwebconfig"
}

**Comment by dpaulson45** [comment]
@Logonzal are you wanting to add this?
