### ISSUE TITLE
[Issue] nmap script scan problem with https://github.com/microsoft/CSS-Exchange/blob/main/Security/http-vuln-cve2021-26855.nse

### ISSUE THREAD

**Issue by 2d4d** [microsoft/CSS-Exchange#81]
**Describe the issue**
nmap scripting is not reliable in scanning HTTPS, see these issues:
https://github.com/GossiTheDog/scanning/issues/2
https://github.com/nmap/nmap/issues/2094

**Comment by GossiTheDog** [comment]
If it helps https://github.com/GossiTheDog/scanning/issues/3

**Comment by GossiTheDog** [comment]
This is the way I worked around on my own script: add --min-rtt-timeout 3 to nmap options.
