### ISSUE TITLE
[Work Item] - HealthChecker - Verify if the Exchange Back End ECP virtual directory BinSearchFolders value is misconfigured

### ISSUE THREAD

**Issue by Logonzal** [microsoft/CSS-Exchange#810]
$MsiInstallPath = (Get-ItemProperty HKLM:\SOFTWARE\Microsoft\ExchangeServer\v15\Setup).MsiInstallPath
$BinSearchFolders = Get-Item -Path "C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\ecp\web.config" |
Select-String -Pattern "BinSearchFolders" | select-object -ExpandProperty Line

$BinSearchFolders = $BinSearchFolders.ToString()
$BinSearchFolders = $BinSearchFolders.Substring(39)
$BinSearchFolders = $BinSearchFolders.Split(";""/"">")
$BinSearchFolders = $BinSearchFolders.Trim() -ne ""

if ($BinSearchFolders[0] -notlike "$MsiInstallPath"+"bin" -or $BinSearchFolders[1] -notlike "$MsiInstallPath"+"bin\CmdletExtensionAgents" -or 
    $BinSearchFolders[2] -notlike "$MsiInstallPath"+"ClientAccess\Owa\bin") {
    write-host -ForegroundColor Red "The BinSearchFolders value on the Exchange Back End ECP virtual directory is misconfigured. Follow the resolution steps in the article 
    to restore. https://aka.ms/BinSearchFoldersPath"
}

**Comment by dpaulson45** [comment]
#980 Resolved this.
