### ISSUE TITLE
[Issue] - Health Checker - WARNING: There was an error trying to add custom classes to the current PowerShell session

### ISSUE THREAD

**Issue by hapklaar** [microsoft/CSS-Exchange#814]
**Provide Version Number**
Any

**Describe the issue**
I run a scheduled task with a simple wrapper script to periodically run healthchecker.ps1 against all our Exchange servers. 
1. It first tries to update the script with the scriptupdateonly switch.
2. Then it enumerates all exchange nodes and uses healthchecker.ps1 to loop through them to generate XML's for them using the Outputfilepath. 
3. Finally it builds an html report with switch BuildserversReport and then sends that report with send-mailmessage.

This works fine, except when there was an update available. When the tool was updated I get the following custom error:

`WARNING: There was an error trying to add custom classes to the current PowerShell session. You need to close this session and open a new one to have the script properly work.`

I'm not sure how to work around this. I could separate the update part from the actual scanning of the servers by creating a separate scheduled task, but I feel there must be a smarter way to do this.

**Expected behavior**
Update then run the healthchecker without errors.

**Script Output**
`WARNING: There was an error trying to add custom classes to the current PowerShell session. You need to close this session and open a new one to have the script properly work.`

**Comment by lusassl-msft** [comment]
You'll see this warning if the new (updated) version contains changes within the class section of the script. There was an update of the class with the latest Health Checker version:

`public object WildCardAcceptedDomain; // for issues with * accepted domain.`

I don't think there is a way to unload the class except to start a new session. You could handle this in your wrapper by comparing the file hash pre/post running the ScriptUpdateOnly switch. If it differs post ScriptUpdateOnly it means the script has been updated and should be run within a new session (for example when the scheduled task is executed again or so).

**Comment by dpaulson45** [comment]
One way around this is to call the code that does the `ScriptUpdateOnly` prior to loading in the class information that is used for the script.

**Comment by lusassl-msft** [comment]
Exactly, let's add it to the backlog. I'll take care of this ask.
