### ISSUE TITLE
Add status check for dependent services in HealthChecker

### ISSUE THREAD

**Issue by fluggelgleckheimlen** [microsoft/CSS-Exchange#826]
**Describe The Request**
It would be great if you add status checks for dependent services that are not touched during CUs or SUs installation.

These services are listed as common in $env:exchangeinstallpathbin\ServiceControl.ps1 and not included in the critical list below:
`$script:servicesToControl['Common'] = @( 'WinMgmt', 'RemoteRegistry', 'HealthService', 'OnePoint', 'MOM', 'OMCFG', 'pla' )`
`$script:servicesToControl['Critical'] = @( 'WinMgmt', 'RemoteRegistry', 'W3Svc', 'IISAdmin' )`

**Additional context**
For example: the PLA service may be disabled during failed upgrade and will cause a memory leak in MSExchangeDiagnostics. Subsequent CU installations will not change the state of the service, but a new check in HealthChecker may tell the administrator that something is wrong.

**Comment by dpaulson45** [comment]
@lusassl-msft I got some code written for this. However, debating on where to place the code. Should it be under Exchange or Server Information? Need to also decide on which section to display the results under. Let me know what you think.
