### ISSUE TITLE
[Issue] - Health Checker

### ISSUE THREAD

**Issue by omer-py** [microsoft/CSS-Exchange#830]
**Provide Version Number**
ms exchange 2016 cu22 running on windows 2016 datacenter edition

**Describe the issue**
net tcp sharing service getting disabled and ms services stopped intervally almost 12 to 14 hours

**Expected behavior**

**Script Output**
If applicable, add the exception that wasn't handled.

**Additional context**

**Comment by lusassl-msft** [comment]
Hi @omer-py ,
can you add a little more context here? Do you want us to add a check to the HealthChecker for the scenario described here?

**Comment by lusassl-msft** [comment]
Closing this issue. Please open a new one if required.
