### ISSUE TITLE
Reset-ScanEngineVersion does not support running remotely

### ISSUE THREAD

**Issue by bill-long** [microsoft/CSS-Exchange#833]
It would be nice if we could run the script in one place and pass it all the server names. The script was originally written to work that way, but there's a problem.

You can observe the problem if you copy the $scriptBlock variable from the script and paste it right into PowerShell:

![image](https://user-images.githubusercontent.com/4518572/147877550-8cd98474-8cff-4b03-908b-fff20ab537ce.png)

Then, attempt to invoke the script block against a remote server:

![image](https://user-images.githubusercontent.com/4518572/147877561-dfab4bbd-cf6e-4ff4-a783-1b01834d4d8f.png)

It works until it calls the Update-MalwareFilteringServer script:

![image](https://user-images.githubusercontent.com/4518572/147877631-961a37fc-a052-4095-9050-ea68cb8ebb80.png)

![image](https://user-images.githubusercontent.com/4518572/147877653-f18dab58-2c40-41fa-b9b6-e0551ec4deaa.png)

This refers to an area of Update-MalwareFilteringServer where it also invokes a script block. So I guess you can't have a script block that was invoked from a remote machine call a script that then invokes another script block? If we can figure out how to make this work, then the script can work remotely.

**Comment by bill-long** [comment]
This seems to be the second hop problem described here: https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ps-remoting-second-hop

I tried CredSSP, but it is not enabled by default in my labs, which means it may not be enabled in many production environments.

**Comment by bill-long** [comment]
Update-MalwareFilteringServer.ps1 is a fairly simple script. Instead of calling it, perhaps we could copy the relevant commands into Reset-ScanEngineVersion?

**Comment by bill-long** [comment]
Still doesn't work. Even if we call Start-EngineUpdate directly in the Reset- script, it still fails on the creds.

**Comment by dpaulson45** [comment]
Script might not need to have this issue fixed, should we close it out?

**Comment by bill-long** [comment]
Yeah, this is a won't fix. Haven't seen any asks for it (does anyone still use this script) and also have no ideas how to fix it.
