### ISSUE TITLE
HealthChecker reports TLS 1.2 and other are disabled

### ISSUE THREAD

**Issue by alexhass** [microsoft/CSS-Exchange#852]
Health checker incorectly reports that TLS 1.2/1.1/1.0 is disabled.

It is not correct that the value need to be 1 or 0. It can also be 0xffffffff (4294967295).

See https://www.hass.de/content/setup-microsoft-windows-or-iis-ssl-perfect-forward-secrecy-and-tls-12.

**Comment by dpaulson45** [comment]
@alexhass no, it can't be 0xffffffff, it is required to be 1 or 0 as per our documentation. 

See this issue for more information: https://github.com/dpaulson45/HealthChecker/issues/220

**Comment by dpaulson45** [comment]
Also, 0xffffffff = -1 which most people believe that this means don't enable or always going to be false, which isn't true. Based off the article you provided, all it is doing is enabling it, which again some people believe it does the opposite. While it does work, it is the incorrect way of doing it and the Health Checker is only going to follow the correct way of doing it. 

![image](https://user-images.githubusercontent.com/22776718/148794875-ca54d355-b0aa-41a3-953b-d8fc232f6d1d.png)

**Comment by alexhass** [comment]
Have you reviewed MS SSL code why it works? Maybe there is just a lack of documentation?

**Comment by dpaulson45** [comment]
It isn't lack of documentation it is how code works. 

![image](https://user-images.githubusercontent.com/22776718/148799517-ddda4159-c057-4fd6-ba60-b113caba34dd.png)
