### ISSUE TITLE
[Issue] - Health Checker detect FIP-FS error on Exchange 2013 CAS role server

### ISSUE THREAD

**Issue by WarmColor** [microsoft/CSS-Exchange#859]
**Provide Version Number**
Server version: Exchange 2013 CU 23
Health Checker version: 22.01.11.2114

**Describe the issue**
script show error with a  Exchange 2013 CAS role server without mailbox role, but 2013 shouldn't be affected.
![image](https://user-images.githubusercontent.com/13973339/149055866-70db11de-04ce-40ea-9c0e-42dea0790049.png)

**Expected behavior**
with no error

**Script Output**
![image](https://user-images.githubusercontent.com/13973339/149054471-e34e46c9-84df-48d8-9f02-e7bc4ce68c0d.png)

**Comment by dpaulson45** [comment]
Need to bypass this check in the CAS only role on 2013.
