### ISSUE TITLE
Optimize certificate reporting in Health Checker

### ISSUE THREAD

**Issue by jalrok** [microsoft/CSS-Exchange#872]
Azure joined servers generate a lot of unnecessary errors as all the "MS-Organization-P2P-Access" are listed as invalid. I'd like to be able to exclude these, or only report on certificates that are assigned to Exchange roles.

These certificates cause a similar issue in the Exchange GIU as all the Azure certs are constantly expiring and triggering unnecessary warnings.

**Comment by lusassl-msft** [comment]
Will check if we can exclude these certificate from the check.

Just for the records:


_What are the MS-Organization-P2P-Access certificates present on our Windows 10/11 devices?

The MS-Organization-P2P-Access certificates are issued by Azure AD to both, Azure AD joined and hybrid Azure AD joined devices. These certificates are used to enable trust between devices in the same tenant for remote desktop scenarios. One certificate is issued to the device and another is issued to the user. The device certificate is present in Local Computer\Personal\Certificates and is valid for one day. This certificate is renewed (by issuing a new certificate) if the device is still active in Azure AD. The user certificate is not persistent and is valid for one hour, but it is issued on-demand when a user attempts a remote desktop session to another Azure AD joined device. It is not renewed on expiry. Both these certificates are issued using the MS-Organization-P2P-Access certificate present in the Local Computer\AAD Token Issuer\Certificates. This certificate is issued by Azure AD during device registration._

https://docs.microsoft.com/en-us/azure/active-directory/devices/faq#what-are-the-ms-organization-p2p-access-certificates-present-on-our-windows-10-11-devices
