### ISSUE TITLE
[Wrong Version Reported] - Health Checker

### ISSUE THREAD

**Issue by CAFMATS** [microsoft/CSS-Exchange#878]
**Provide Version Number**
22.01.31.1746

**Describe the issue**
Health Checker is reporting the wrong Exchange version number. I am on Exchange 2019 CU10, it is reporting Exchange 2019 CU11.

**Expected behavior**
It should report the correct Exchange version and CU #.

Sample Output:

Name: EXCH_2019_SERVER
        Generation Time: 01/31/2022 20:52:36
        Version: Exchange 2019 CU11
        Build Number: 15.02.0922.020

![Health_Check_Wrong_Ver](https://user-images.githubusercontent.com/98793968/151911843-67835831-c983-45c3-93a1-f2e0d978a392.jpg)

**Comment by lusassl-msft** [comment]
@CAFMATS could you please run the script with the `-SaveDebugLog` switch and share the log via `ExToolsFeedback[at]microsoft[dot]com` ?
