### ISSUE TITLE
Health Checker v2 - Visual C++ Redistributable Version Check - 2013 reported as outdated with 2012 current one

### ISSUE THREAD

**Issue by benoithamet** [microsoft/CSS-Exchange#886]
After running the Health Checker v2 script, got the below report for VC++ redistributable which does not make sense - how 2013 could be outdated compared to 2012 being the current one
Visual C++ Redistributable Version Check:
	Visual C++ 2013 Redistributable is outdated
	Visual C++ 2012 Redistributable Version 11.0.61030 is current

The script has been ran directly from the Exchange 2019 server (up to date) running on Windows 2019 Server (up to date)

**Comment by dpaulson45** [comment]
Health Checker v2 script is no longer supported. Make sure you are using the most recent version from here: http://aka.ms/ExchangeHealthChecker

The Visual C++ Redistributable needs to be updated manually vs from Windows Update and isn't part of Exchange update process.

**Comment by benoithamet** [comment]
Thanks
I understand this is a manual process
What I'm saying how it could report the 2013 is outdated and says the 2012 version is current one
Also the version used is the latest one available from the link you provided

**Comment by dpaulson45** [comment]
You stated that you are running v2, which is a year or two old version. Secondly the script no longer displays the Visual C++ Redistributable that way. You are not running the most current script, run the latest version from the link provided above.

**Comment by dpaulson45** [comment]
If you run the latest version of the script, it will provide the correct link to our page which will then redirect you to the page that contains the latest version of C++ for 2013.

**Comment by benoithamet** [comment]
Thanks David
Sorry apparently indeed I ended to use the old version
All good
