### ISSUE TITLE
[Issue] SetupAssist Failed to properly run Test-ExchangeADSetupLevel

### ISSUE THREAD

**Issue by worldsdream** [microsoft/CSS-Exchange#895]
Running the script in Exchange Management Shell on the Exchange Server shows the error:

[02/15/2022 12:18:37] : Working on test Test-ExchangeADSetupLevel
[02/15/2022 12:18:39] : Failed to properly run Test-ExchangeADSetupLevel
[02/15/2022 12:18:39] : System.Management.Automation.RuntimeException: Не удается индексировать в массив NULL.
в System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
в System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
в System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
в System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
[02/15/2022 12:18:39] : в TestPrepareAD, C:\scripts\SetupAssist.ps1: строка 237
в TestReadyLevel, C:\scripts\SetupAssist.ps1: строка 311
в Test-ExchangeADSetupLevel, C:\scripts\SetupAssist.ps1: строка 412
в RunAllTests, C:\scripts\SetupAssist.ps1: строка 3598
в Main, C:\scripts\SetupAssist.ps1: строка 3608
в , C:\scripts\SetupAssist.ps1: строка 3686

**Comment by dpaulson45** [comment]
#896 should have addressed this issue.

**Comment by dpaulson45** [comment]
Confirmed this worked for the customer.

**Comment by worldsdream** [comment]
Thanks
