### ISSUE TITLE
[Feature Request] Warning check if MRS Proxy is enabled -> disable according to best practices

### ISSUE THREAD

**Issue by grimson73** [microsoft/CSS-Exchange#898]
Hello,

When running the HCW wizard to connect the on-premises Exchange Server to EOL you 'have to' enable the MRS Proxy on the Internet facing Exchange Server.

https://docs.microsoft.com/en-us/exchange/architecture/mailbox-servers/mrs-proxy-endpoint?view=exchserver-2019

'What do you need to know before you begin?' describes the following:
- If you don't perform cross-forest moves or remote move migrations, keep MRS Proxy endpoints disabled on Mailbox servers to reduce the attack surface of your organization.

So 'best practices' is to keep this MRS Proxy disabled when not in use. Therefore I was thinking if this would be somehow worthy for the HealthCheck script.
To check if the MRS Proxy is enabled and if so offer the scriptrunner the best practice advice accordingly.

Again, please keep this as a suggestion, if not applicable please close :) thanks!!

**Comment by dpaulson45** [comment]
Could probably add this and just display it as a warning if it is enabled.
