### ISSUE TITLE
HealthChecker should count AD sites and warn regarding high CPU

### ISSUE THREAD

**Issue by bill-long** [microsoft/CSS-Exchange#909]
**Is your request related to a problem? Please describe.**

Autodiscover app pool will peg the CPU at 4-hour intervals when there are many AD sites. In a recent case, there were over 800 sites, but it could be observed with fewer. Not sure what the exact threshold should be here.

**Describe The Request**

If AD site count is greater than *n*, say something about the possibility of high CPU at 4-hour intervals from Autodiscover app pool. Note the workaround of changing this value:

![image](https://user-images.githubusercontent.com/4518572/155385609-d2c54a02-6720-42f2-b8ad-3c272c7bca32.png)

The first value (04:00:00) is the refresh interval for the Complete discovery scope. This is the scope Autodiscover uses. When Topology sends a new Complete topology over to Autodiscover every 4 hours, Autodiscover has to recalculate all the site costs.

As a workaround, the interval can be reduced in this config file. On the recent case we reduced it to 24 hours with no apparent ill effects.

**Comment by dpaulson45** [comment]
For this we decided to display a value if we have over 500 sites. Then a warning once at 750, then an error message at 1000 sites. All of them linking back to a page in the docs about the issue.
