### ISSUE TITLE
[Issue] ExchangeMitigations.ps1 breaks Exchange 2013 CU23

### ISSUE THREAD

**Issue by viniciusferrao** [microsoft/CSS-Exchange#920]
**Describe the issue**
After running `ExchangeMitigations.ps1` on an Exchange Server 2013 CU23 running on Windows Server 2012 (non-R2) the server is unusable.

There's some warning that IIS Rewrite Module 2.1 will break on IIS8 but 2.0 is no longer available, I'm not sure if this is related or not.

Server was unable to even run `Get-HealthReport` and ECP/OWA returned 503. After running `ExchangeMitigations.ps1` rollback, everything went to normal again.

**Expected behavior**
Don't break the server

**Script Output**
Unfortunately I've lost. But was everything OK. I do have the rollback instead:

```
PS C:\Users\Administrator.TESTDOMAIN> .\ExchangeMitigations.ps1 -WebSiteNames "Default Web Site" -RollbackAllMitigation
WARNING: Waiting for service 'Microsoft Exchange Unified Messaging (MSExchangeUM)' to start...
WARNING: Waiting for service 'Microsoft Exchange Unified Messaging (MSExchangeUM)' to start...
WARNING: Waiting for service 'Microsoft Exchange Unified Messaging (MSExchangeUM)' to start...
WARNING: Waiting for service 'Microsoft Exchange Unified Messaging Call Router (MSExchangeUMCR)' to start...

Status   Name               DisplayName
------   ----               -----------
Running  MSExchangeUM       Microsoft Exchange Unified Messaging
Running  MSExchangeUMCR     Microsoft Exchange Unified Messagin...
VERBOSE: Performing operation "Set-Item" on Target "-path \\EXCH2013\AppPools\MSExchangeECPAppPool".
VERBOSE: Status of MSExchangeECPAppPool

Value : Started

WARNING: Waiting for service 'Microsoft Exchange Health Manager (MSExchangeHM)' to start...
WARNING: Waiting for service 'Microsoft Exchange Health Manager (MSExchangeHM)' to start...
WARNING: Waiting for service 'Microsoft Exchange Health Manager (MSExchangeHM)' to start...
Running  MSExchangeHM       Microsoft Exchange Health Manager
VERBOSE: Performing operation "Set-Item" on Target "-path \\EXCH2013\AppPools\MSExchangeOABAppPool".
VERBOSE: Status of MSExchangeOABAppPool

Value : Started
```

**Additional context**
`EOMT.ps1` says that everything is OK on the server even after rolling back `ExchangeMitigations.ps1`. So it may be the case to implement a block on `ExchangeMitigations.ps1` to avoid breaking up old servers.

Unfortunately I don't have that much logs, because during the failures I've ended up rebooting the server multiple times until realizing it was the mitigation script that may be not even relevant anymore after CU23.

Thanks.

**Comment by dpaulson45** [comment]
@viniciusferrao why are you running `ExchangeMitigations.ps1`? This was a stop gap if you couldn't install the security update from March of 2021 right away.
