### ISSUE TITLE
HealthChecker Check & Warn about Fast Search Memory Config Changes

### ISSUE THREAD

**Issue by dsureshb** [microsoft/CSS-Exchange#927]
Based on few articles in internet customers are changing Memory settings for Fast Search which causes Index to either Fail or remain in Unknown state or fails with Out Of memory Exception

Locate the Noderunner.exe.config file. By default, this file is located along the following path: C:\Program Files\Microsoft\Exchange Server\V15\Bin\Search\Ceres\Runtime\1.0
Edit the file, and then locate the following key: ```<nodeRunnerSettings memoryLimitMegabytes="0"/>```

Warning should be generated if the above value is changed from default.

**Comment by dpaulson45** [comment]
@dsureshb  what key?

**Comment by dsureshb** [comment]
Locate the Noderunner.exe.config file. By default, this file is located along the following path: C:\Program Files\Microsoft\Exchange Server\V15\Bin\Search\Ceres\Runtime\1.0
Edit the file, and then locate the following key: <nodeRunnerSettings memoryLimitMegabytes="0"/>

**Comment by dsureshb** [comment]
> @dsureshb what key?


For some reason Git is truncating the text its referenced here https://social.technet.microsoft.com/Forums/en-US/7e0e4ae9-6ce0-4f84-9f90-b070f2477a04/noderunner-occupying-high-memory-on-the-exchange-server

**Comment by dpaulson45** [comment]
Updated the original message to place the line in a code block to be seen.
