### ISSUE TITLE
[Feature Request] [HealthChecker.ps1] add check for self-signed cert bound to backend 444

### ISSUE THREAD

**Issue by boogieshafer** [microsoft/CSS-Exchange#955]
**Is your request related to a problem? Please describe.**
reference: https://docs.microsoft.com/en-us/exchange/troubleshoot/client-connectivity/owa-ecp-ems-cannot-connect-after-self-signed-certificate-removed

after replacing/renewing some self signed certs based on previous runs of the HealthChecker script to change the signing mechanism i noticed the previous bindings for the backend on 444 were missing and i wasnt seeing any indication of this in the HealthChecker script

**Describe The Request**
the HealthChecker script should probably check to make sure the backend IIS instance has the self signed cert bound to 444 as if its not present some functions dont work correctly

**Additional context**

**Comment by boogieshafer** [comment]
coming back to this issue as it looks like there might be a possible functionality addition here now that the HealthChecker.ps1 script does *report* on the certificates that are bound to the services

it does not appear to check if the certificate that is bound to the service still exists on the server....i.e. certificate removed after binding

example in the screenshots
<img width="922" alt="Screen Shot 2023-05-25 at 09 17 35" src="https://github.com/microsoft/CSS-Exchange/assets/714141/92e0e584-bcb2-4253-8891-8375fa727f0b">
<img width="917" alt="Screen Shot 2023-05-25 at 09 18 01" src="https://github.com/microsoft/CSS-Exchange/assets/714141/d14443b7-3490-4367-8885-9c78d1d33fe4">

**Comment by dpaulson45** [comment]
- If thumbprint isn't in the list of certificates, throw an error stating as such.
- If thumbprint isn't valid, throw an error stating the cert is no longer valid and will cause issues
- If thumbprint doesn't have hostname and FQDN, then call out an error stating that we don't have hostname and FQDN in the namespace as that is known to cause issues in particular scenarios.
