### ISSUE TITLE
Problem to get Test-ProxyLogon.ps1 working running local on Exchange Server 2013

### ISSUE THREAD

**Issue by DuncanMacLeod-WotU** [microsoft/CSS-Exchange#96]
running Test-ProxyLogon.ps1 on my Exchange Server 2013 throws an error...

.\Test-ProxyLogon.ps1 -OutPath $home\desktop\logs

[TESTMACHINE] Beim Verbinden mit dem Remoteserver "TESTMACHINE" ist folgender Fehler aufgetreten: Der Client kann keine Verbindung
mit dem in der Anforderung angegebenen Ziel herstellen. Stellen Sie sicher, dass der Dienst auf dem Ziel ausgeführt
wird und die Anforderungen akzeptiert. Lesen Sie die Protokolle und die Dokumentation für den WS-Verwaltungsdienst,
der auf dem Ziel ausgeführt wird. Hierbei handelt es sich meistens um IIS oder WinRM. Wenn das Ziel der WinRM-Dienst
ist, führen Sie den folgenden Befehl auf dem Ziel aus, um den WinRM-Dienst zu analysieren und zu konfigurieren: "winrm
quickconfig". Weitere Informationen finden Sie im Hilfethema "about_Remote_Troubleshooting".
    + CategoryInfo          : OpenError: (TESTMACHINE:String) [], PSRemotingTransportException
    + FullyQualifiedErrorId : CannotConnect,PSSessionStateBroken

sorry, the error message is in German language.
The machine on which I ran the script is an Windows Server 2008 R2 Standard Edition with Exchange 2013 Standard.
I already applied the Exchange patch KB5000871, so I don't know if this behavior is 'normal' when the patch has been applied.

I ran the command with my exchange admin account in powershell, with the elevated Administrator account in Powershell and in my Exchange Management shell. No success so far to get it working.

**Comment by bill-long** [comment]
This means PS Remoting is not working on that machine. You can either troubleshoot PS Remoting to get it working, or you can modify the script so that it can't run remotely. If you just want to get the script working locally, you could change this:

```
        process {
            Invoke-Command @parameters -ComputerName $ComputerName
        }
```

To this:

```
        process {
            Invoke-Command @parameters
        }
```

Note that this change will make it impossible to run the script against all servers remotely - you'll need to copy it to each server to run it.

**Comment by bill-long** [comment]
This workaround is no longer needed in the latest release. If you do not provide -ComputerName and do not pipe a name, the script no longer tries to invoke remotely.
