### ISSUE TITLE
 Undo decline of "untrusted issuer"

### ISSUE THREAD

**Issue by unitrix0** [microsoft/CSS-Exchange#964]
So when I first ran the EOMT.ps1 script powershell asked me if I trust the issuer of the script. And (because the translation to German were missleading) I accidentally declined that. How can I undo this?

**Comment by lusassl-msft** [comment]
Hi,
You must remove the certificate from the disallowed list. You can find the list under: 
`HKEY_CURRENT_USER\SOFTWARE\Microsoft\SystemCertificates\Disallowed\Certificates`

Remove the `BB983EC3E1F76DE6C1E8446C9976A82BD1798BB7` registry key (thumbprint of the signer certificate).
