### ISSUE TITLE
Script Fails to Complete with Error - Health Checker

### ISSUE THREAD

**Issue by tOADPie** [microsoft/CSS-Exchange#990]
**Provide Version Number**
22.04.22.1428

**Describe the issue**
While attempting to run the health checker there is a error stating parameter name cannot be found.

On line 1254 the parameter -DisplayCustomTabNumber 2 is incorrectly entered as -DisplayCustomTabNumbermber 2

**Comment by tOADPie** [comment]
Changing the parameter to -DisplayCustomTabNumber 2 had saving then re running the script works successfully.

**Comment by dpaulson45** [comment]
Will be in the next release of the script. 

Resolved #989

**Comment by dpaulson45** [comment]
@tOADPie issue is resolved with the latest release.
