### ISSUE TITLE
Health Checker 2316 requesting parameter

### ISSUE THREAD

**Issue by josemi73** [microsoft/CSS-Exchange#994]
Hi
I have just downloaded v 2316, and it is requesting a parameter:

- > .\HealthChecker.ps1
- > Exchange Health Checker version 22.04.24.2316
- > 
- > cmdlet Add-AnalyzedResultInformation at command pipeline position 1
- > Supply values for the following parameters:
- > AnalyzedInformation:

Older v 22.04.22.1428 was working fine.

**Comment by dpaulson45** [comment]
can you email the debug log to ExToolsFeedback@microsoft.com?

**Comment by josemi73** [comment]
> can you email the debug log to [ExToolsFeedback@microsoft.com](mailto:ExToolsFeedback@microsoft.com)?

I have just sent the debug file if you want to verify your discovery about multiple NICs.

**Comment by dpaulson45** [comment]
Confirm issue resolved.
